display_name = "Isaac Tests"

[dependencies]
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.commands" = {}
"omni.kit.window.tests" = {}
"omni.kit.window.toolbar" = {} # needed for simulation to happen
"omni.kit.primitive.mesh" = {} # needed for mesh creation commands
# "omni.graph.core" = {}
"omni.isaac.utils" = {}
"omni.kit.material.library" = {}
"omni.kit.window.viewport" = {}
"omni.kit.pip_archive" = {} # pulls in numpy
"omni.syntheticdata" = {}

[[python.module]]
name = "omni.isaac.tests"

[[python.module]]
name = "omni.isaac.tests.tests"