display_name = "Isaac Tests"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}
"omni.kit.window.tests" = {}
"omni.kit.window.toolbar" = {} # needed for simulation to happen
"omni.kit.primitive.mesh" = {} # needed for mesh creation commands

[[python.module]]
name = "omni.isaac.tests"

[[python.module]]
name = "omni.isaac.tests.tests"
