display_name = "Isaac Dofbot Robot"

[package]
version = "0.1.4"

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.kit" = {}
"omni.isaac.motion_generation" = {}

[[python.module]]
name = "omni.isaac.dofbot"

