[core]
reloadable = true
order = 0

[package]
version = "0.3.1"
category = "Simulation"
title = "Isaac Dofbot Robot"
description = "Isaac Dofbot Robot Helper Class"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.dofbot"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.motion_generation" = {}
"omni.isaac.manipulators" = {}

[[python.module]]
name = "omni.isaac.dofbot"

