# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#core-section
[core]
reloadable = true
order = 0

# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#package-section
[package]
version = "0.0.5"
category = "other"
title = "Isaac Sim Robot Wizard [Beta]"
description = "Wizard to guide through robot import and configuration"
authors = ["hmazhar@nvidia.com", "qwan@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.robot_setup.wizard"
keywords = ["wizard","import"," "]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#dependencies-section
writeTarget.kit = true

[dependencies]
"isaacsim.gui.components" = {}
"isaacsim.robot.schema" = {}


# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#python-section
[[python.module]]
name = "isaacsim.robot_setup.wizard"

# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html#settings-section
[settings]
# time out for resolving the robot wizard settings
exts."isaacsim.robot_setup.wizard".timeout = 5

# launch on startup
persistent.exts."isaacsim.robot_setup.wizard".launch_on_startup = false

[[test]]
name = "startup"
enabled = true
