[package]
version = "0.2.0"
category = "other"
title = "Isaac Sim Robot Wizard [Beta]"
description = "Wizard to guide through robot import and configuration"
authors = ["hmazhar@nvidia.com", "qwan@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.robot_setup.wizard"
keywords = ["wizard","import"," "]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.experimental.objects" = {}
"isaacsim.gui.components" = {}
"isaacsim.robot.schema" = {}

[[python.module]]
name = "isaacsim.robot_setup.wizard"

[settings]
# Timeout for resolving the robot wizard settings.
exts."isaacsim.robot_setup.wizard".timeout = 5

# Launch on startup.
persistent.exts."isaacsim.robot_setup.wizard".launch_on_startup = false

[[test]]
name = "startup"
enabled = true

[documentation]
pages = ["docs/Overview.md","docs/SETTINGS.md", "docs/CHANGELOG.md"]
