[core]
reloadable = true
order = 0

[package]
version = "0.3.2"
category = "Simulation"
title = "Robot Engine Bridge"
description = "Communication bridge for Isaac SDK"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.isaac.sensor" = {}
"omni.syntheticdata" = {}
"omni.usd.schema.isaac" = {}
"omni.kit.pip_archive" = {} # pulls in numpy
"omni.isaac.core_archive" = {} # pull in the rest of the pip dependencies
"omni.graph" = {}
"omni.graph.tools" = {}

[[python.module]]
name = "capnp"
path = "pip_prebundle"

[[python.module]]
name = "omni.isaac.robot_engine_bridge"

[[python.module]]
name = "omni.isaac.pyalice"

[[python.module]]
name = "omni.isaac.robot_engine_bridge.tests"
public = false

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[[native.library]]
path = "lib/libcudart.so.10.2"

[[native.library]]
path = "lib/libnppc.so.10"

[[native.library]]
path = "lib/libnppial.so.10"

[[native.library]]
path = "lib/libnppidei.so.10"

[[native.library]]
path = "lib/libnppif.so.10"

[[native.library]]
path = "lib/libnppig.so.10"

[[native.library]]
path = "lib/libnpps.so.10"

[fswatcher.patterns]
# include = ["*.ogn", "*.py"]
exclude = ["*/__pycache__*", "*/.git*", "*/packages", "Ogn*Database.py"]

[settings]
# this setting controls the log level of the isaac sdk application 
# A utility case which can be used for `SetSeverity` to disable all severity levels.
# NONE = -2,
# A utility case which can be used for `Redirect` and `SetSeverity`
# ALL = -1,
# The five different log severities in use from most severe to least severe.
# PANIC = 0,  
# ERROR = 1
# WARNING = 2
# INFO = 3
# DEBUG = 4
exts."omni.isaac.robot_engine_bridge".IsaacSDKLogLevel = 3