[package]
version = "2.1.5"
category = "Simulation"
title = "Isaac Sim Internal Utils"
description = "Internal Utilities"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.util.internal"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"omni.kit.menu.utils" = {}
"omni.kit.uiapp" = {}
"omni.kit.viewport.window" = {}
"omni.kit.widget.stage" = {}

[[python.module]]
name = "isaacsim.util.internal"

[[python.module]]
name = "isaacsim.util.internal.tests"

[[test]]
timeout = 900
dependencies = [
    "isaacsim.storage.native"
]