# SPDX-FileCopyrightText: Copyright (c) 2020-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import logging
import os
import sys
from typing import Any, Callable, Mapping

import omni.repo.man
import tomli

logger = logging.getLogger(os.path.basename(__file__))


def _load_extension_config(ext_path: str, error_as_warn: bool) -> Mapping[str, Any]:
    with open(os.path.join(ext_path, "config", "extension.toml"), "rb") as file:
        try:
            config = tomli.load(file)
        except Exception as e:
            if error_as_warn:
                omni.repo.man.print_log(f"  |-- Wrong extension.toml format in file {file.name}: {e}", logging.WARN)
            else:
                omni.repo.man.print_log(f"  |-- Wrong extension.toml format in file {file.name}: {e}", logging.ERROR)
                sys.exit(1)
            return {}
    return config


def parse_toctree(content: list[str]) -> list[dict]:
    # get extension sections
    start = [content.index(item) for item in content if item.strip().startswith("start extensions:")]
    end = [content.index(item) for item in content if item.strip().startswith("end extensions:")]
    content = content[start[0] : end[0]]
    # parse toctree
    toctree = {}
    toctrees = []
    for line in content:
        line = line.strip()
        if line.startswith(".. toctree::") or line == "..":
            if toctree.get("caption"):
                toctrees.append(toctree)
            toctree = {"caption": None, "extensions": []}
            # stop parsing the document
            if line == "..":
                break
            continue
        # get caption
        elif ":caption:" in line:
            toctree["caption"] = line.split(":caption:")[1].strip()
        # get extensions
        elif "<source/" in line:
            name = line.split(" <")[0]
            path = line.split("<")[1].split(">")[0]
            toctree["extensions"].append({"name": name, "path": path})
        elif "<docs/extsbuild/" in line:
            name = line.split(" <")[0]
            path = line.split("<")[1].split(">")[0]
            toctree["extensions"].append({"name": name, "path": path})

    return toctrees


def generate_tables(toctrees: list[dict], error_as_warn: bool) -> list[str]:
    content = []
    for toctree in toctrees:
        caption = toctree["caption"]
        content += [
            f"\n{caption}",
            f"{'~' * len(caption)}\n",
            ".. list-table::",
            "    :header-rows: 1\n",
            "    * - Extension",
            "      - Title",
            "      - Description",
        ]
        for extension in toctree["extensions"]:
            # get extension description
            try:
                extension_path = extension["path"].replace("/docs/index", "")
                ext_config = _load_extension_config(extension_path, error_as_warn=error_as_warn)
            except FileNotFoundError as e:
                omni.repo.man.print_log(f"Unable to load extension.toml: {e}", logging.WARN)
                continue
            title = ext_config.get("package", {}).get("title", "")
            description = ext_config.get("package", {}).get("description", "")
            content += [
                f"    * - :doc:`{extension['name']} <{extension['path']}>`",
                f"      - {title}",
                f"      - {description}",
            ]
    return content


def setup_repo_tool(parser: argparse.ArgumentParser, config: Mapping) -> Callable:
    parser.description = """
Generate extension TOC.
"""
    parser.formatter_class = argparse.RawTextHelpFormatter
    parser.add_argument(
        "--error-as-warn",
        required=False,
        default=False,
        action="store_true",
        help="Whether to treat errors as warnings. If not set, execution will terminate when an error is detected.",
    )
    omni.repo.man.add_config_arg(parser)

    def run_repo_tool(options: Mapping, config: Mapping):
        # load index.rst
        extensions_rst = omni.repo.man.resolve_tokens("${root}/index.rst")
        with open(extensions_rst, "r") as file:
            content = file.readlines()

        toctrees = parse_toctree(content)
        src = generate_tables(toctrees, options.error_as_warn)

        # write autogenerated-extension-toc.txt
        path = omni.repo.man.resolve_tokens("${root}/docs/autogenerated-extension-toc.txt")
        with open(path, "w") as file:
            file.write("\n".join(src))

    return run_repo_tool
