# SPDX-FileCopyrightText: Copyright (c) 2020-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import glob
import logging
import os
import re
import shutil
import sys
import textwrap
from typing import Any, Callable, Mapping, Sequence, Union

import omni.repo.man
import tomli

logger = logging.getLogger(os.path.basename(__file__))


DEFAULT_SECTIONS = [
    "reference",
    "title",
    "deprecation",
    "version",
    "description",
    "preview",
    "enable-extension",
    "settings",
    "ogn",
]


def _load_extension_config(ext_path: str, error_as_warn: bool) -> Mapping[str, Any]:
    with open(os.path.join(ext_path, "config", "extension.toml"), "rb") as file:
        try:
            config = tomli.load(file)
        except Exception as e:
            if error_as_warn:
                omni.repo.man.print_log(f"  |-- Wrong extension.toml format: {e}", logging.WARN)
            else:
                omni.repo.man.print_log(f"  |-- Wrong extension.toml format: {e}", logging.ERROR)
                sys.exit(1)
            return {}
    return config


def _apply_autogenerated_content(
    src: Union[str, Sequence[str]], placeholder: str, content: Union[str, Sequence[str], None]
):
    is_str = False
    if isinstance(src, str):
        src = src.split("\n")
        is_str = True
    # find placeholders
    begin = None
    begin_placeholder = f"    [begin {placeholder} autogenerated]"
    if f"{begin_placeholder}" in src:
        begin = src.index(f"{begin_placeholder}") + 1
    if f"{begin_placeholder}\n" in src:
        begin = src.index(f"{begin_placeholder}\n") + 1
    end = None
    end_placeholder = f"    [end {placeholder} autogenerated]"
    if f"{end_placeholder}" in src:
        end = src.index(f"{end_placeholder}") - 1
    if f"{end_placeholder}\n" in src:
        end = src.index(f"{end_placeholder}\n") - 1
    # check if placeholder is found
    if begin is None or end is None:
        return "\n".join(src) if is_str else src
    # erase content
    if content is None:
        dst = src[:begin] + src[end:]
        return "\n".join(dst) if is_str else dst
    # apply content
    if isinstance(content, str):
        content = content.split("\n")
    content = [""] + content + [""]
    dst = src[:begin] + [f"{item}\n" for item in content] + src[end:]
    return "\n".join(dst) if is_str else dst


def copy_files_from_folder(
    source_folder: str,
    destination_folder: str,
    file_patterns: Sequence[str] = None,
    recursive: bool = False,
    preserve_structure: bool = True,
    overwrite: bool = True,
) -> Sequence[str]:
    """Copy a set of files from one folder to another.

    This function copies files from a source folder to a destination folder based on
    specified file patterns. It supports recursive copying and can preserve or flatten
    the directory structure.

    Args:
        source_folder: Path to the source folder containing files to copy.
        destination_folder: Path to the destination folder where files will be copied.
        file_patterns: List of glob patterns to match files. If None, copies all files.
            Default patterns like ['*.rst', '*.md', '*.txt'] can be used for documentation.
        recursive: Whether to search for files recursively in subdirectories.
        preserve_structure: Whether to preserve the directory structure from source.
            If False, all files will be copied directly to destination_folder.
        overwrite: Whether to overwrite existing files in the destination.

    Returns:
        List of paths to the copied files in the destination folder.

    Raises:
        FileNotFoundError: If source_folder doesn't exist.
        OSError: If there are permission issues or other file system errors.

    Example:

    .. code-block:: python

        # Copy all .rst files from source to destination
        copied_files = copy_files_from_folder(
            "/path/to/source",
            "/path/to/destination",
            file_patterns=["*.rst"]
        )

        # Copy all documentation files recursively
        copied_files = copy_files_from_folder(
            "/path/to/source",
            "/path/to/destination",
            file_patterns=["*.rst", "*.md", "*.txt"],
            recursive=True
        )
    """
    if not os.path.exists(source_folder):
        raise FileNotFoundError(f"Source folder does not exist: {source_folder}")

    if not os.path.isdir(source_folder):
        raise ValueError(f"Source path is not a directory: {source_folder}")

    # Create destination folder if it doesn't exist
    os.makedirs(destination_folder, exist_ok=True)

    copied_files = []

    # Default file patterns for documentation if none provided
    if file_patterns is None:
        file_patterns = ["*.rst", "*.md", "*.txt", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.svg"]

    # Find all matching files
    matching_files = []
    for pattern in file_patterns:
        if recursive:
            # Use rglob for recursive search
            matching_files.extend(glob.glob(os.path.join(source_folder, "**", pattern), recursive=True))
        else:
            # Use glob for non-recursive search
            matching_files.extend(glob.glob(os.path.join(source_folder, pattern)))

    # Remove duplicates and sort
    matching_files = sorted(list(set(matching_files)))

    for source_file in matching_files:
        if not os.path.isfile(source_file):
            continue

        # Determine destination path
        if preserve_structure:
            # Preserve the relative path structure
            rel_path = os.path.relpath(source_file, source_folder)
            dest_file = os.path.join(destination_folder, rel_path)
            # Create subdirectories if needed
            dest_dir = os.path.dirname(dest_file)
            if dest_dir:
                os.makedirs(dest_dir, exist_ok=True)
        else:
            # Flatten structure - copy directly to destination folder
            filename = os.path.basename(source_file)
            dest_file = os.path.join(destination_folder, filename)

        # Copy the file
        try:
            if overwrite or not os.path.exists(dest_file):
                shutil.copy2(source_file, dest_file)
                copied_files.append(dest_file)
                logger.info(f"Copied: {source_file} -> {dest_file}")
            else:
                logger.warning(f"Skipped existing file: {dest_file}")
        except Exception as e:
            logger.error(f"Failed to copy {source_file}: {e}")
            raise OSError(f"Failed to copy {source_file}: {e}")

    return copied_files


def create_index(ext_path, ext_name, ext_config, sections, overwrite):
    file_path = os.path.join(ext_path, "docs", "index.rst")
    # check if index.rst exists
    if not overwrite:
        if os.path.isfile(file_path):
            omni.repo.man.print_log(f"  |-- Skipping existing docs/index.rst", logging.INFO)
            return
    # build template
    template = """..
    This file was auto-generated by the 'repo_extension_docs' tool.
    Run 'repo extension_docs --help' for more details.
"""
    for section in sections:
        if isinstance(section, dict):
            section = next(iter(section.keys()))
        template += f"\n..\n    [begin {section} autogenerated]\n..\n    [end {section} autogenerated]\n"
    # create index.rst
    with open(file_path, "w") as file:
        file.write(template)


def generate_extension_metadata(ext_path, ext_name, ext_config, error_as_warn):
    # read index.rst
    file_path = os.path.join(ext_path, "docs", "index.rst")
    with open(file_path, "r") as file:
        src = file.readlines()
    # build and apply content
    # - reference
    content = f".. _ext_{ext_name.replace('.', '_')}:"
    src = _apply_autogenerated_content(src, "reference", content)
    # - title
    title = ext_config.get("package", {}).get("title", "")
    if not title:
        if error_as_warn:
            omni.repo.man.print_log(f"  |-- extension 'title' not filled in extension.toml", logging.WARN)
        else:
            omni.repo.man.print_log(f"  |-- extension 'title' not filled in extension.toml", logging.ERROR)
            sys.exit(1)
    content = f"[{ext_name}] {title}"
    content = f'{content}\n{"#" * len(content)}'
    src = _apply_autogenerated_content(src, "title", content)
    # - version
    version = ext_config.get("package", {}).get("version")
    if not version:
        if error_as_warn:
            omni.repo.man.print_log(f"  |-- extension 'version' not filled in extension.toml", logging.WARN)
        else:
            omni.repo.man.print_log(f"  |-- extension 'version' not filled in extension.toml", logging.ERROR)
            sys.exit(1)
    content = f"**Version**: :guilabel:`{version}`"
    src = _apply_autogenerated_content(src, "version", content if version else None)
    # - deprecation
    deprecation = ext_config.get("deprecation", {}).get("warning")
    if deprecation:
        content = f".. warning::\n    **Deprecation:** {deprecation}"
        src = _apply_autogenerated_content(src, "deprecation", content)
    else:
        src = _apply_autogenerated_content(src, "deprecation", None)
    # - description
    description = ext_config.get("package", {}).get("description")
    if not description:
        if error_as_warn:
            omni.repo.man.print_log(f"  |-- extension 'description' not filled in extension.toml", logging.WARN)
        else:
            omni.repo.man.print_log(f"  |-- extension 'description' not filled in extension.toml", logging.ERROR)
            sys.exit(1)
    if len(description.split(" ")) <= 5:
        omni.repo.man.print_log(f"  |-- Short description: {description}", logging.WARN)
    # Skip description if Overview.md exists (it would be redundant)
    has_overview = os.path.isfile(os.path.join(ext_path, "docs", "Overview.md"))
    if has_overview:
        src = _apply_autogenerated_content(src, "description", None)
    else:
        src = _apply_autogenerated_content(src, "description", description if description else None)
    # - preview
    preview_image = ext_config.get("package", {}).get("preview_image", "")
    preview_image_path = os.path.join(ext_path, preview_image)
    if os.path.isfile(preview_image_path) and os.stat(preview_image_path).st_size > 1024:  # > 1KB
        content = f"""
.. image:: ../{preview_image}
    :align: center
    :alt: Preview
"""
        src = _apply_autogenerated_content(src, "preview", content)
    else:
        src = _apply_autogenerated_content(src, "preview", None)
    # write index.rst
    with open(file_path, "w") as file:
        file.writelines(src)


def generate_extension_enable(ext_path, ext_name, ext_config, error_as_warn):
    content = f"""
Enable Extension
================

The extension can be enabled (if not already) in one of the following ways:

.. tab-set::
    .. tab-item:: Command-line interface
        :sync: tab_cli

        Define the next entry as an application argument from a terminal.

        .. code-block:: bash

            APP_SCRIPT.(sh|bat) --enable {ext_name}

    .. tab-item:: Experience/extension configuration
        :sync: tab_toml

        Define the next entry under ``[dependencies]`` in an experience (``.kit``) file or an extension configuration (``extension.toml``) file.

        .. code-block:: ini

            [dependencies]
            "{ext_name}" = {{}}

    .. tab-item:: Extension Manager UI
        :sync: tab_gui

        Open the *Window > Extensions* menu in a running application instance and search for ``{ext_name}``.
        Then, toggle the enable control button if it is not already active.
"""
    # read index.rst
    file_path = os.path.join(ext_path, "docs", "index.rst")
    with open(file_path, "r") as file:
        src = file.readlines()
    # apply content
    src = _apply_autogenerated_content(src, "enable-extension", content)
    # write index.rst
    with open(file_path, "w") as file:
        file.writelines(src)


def generate_extension_settings(ext_path, ext_name, ext_config, error_as_warn):
    def parse_settings(settings, content_lines):
        def get_subkeys(nested_dict, parent_keys=[], include=[".*"]):
            items = []
            for key, value in nested_dict.items():
                valid = False
                for item in include:
                    if key == item or re.match(item, key):
                        valid = True
                        break
                if valid:
                    new_parent_keys = parent_keys + [key]
                    if isinstance(value, dict):
                        items.extend(get_subkeys(value, new_parent_keys))
                    items.append(new_parent_keys)
            return items

        def get_entry_value_description(keys, settings, content_lines):
            # get formatted key
            if keys[:2] == ["exts", ext_name]:
                key_entry_toml = ".".join([f'"{key}"' if "." in key else key for key in keys[2:]])
                key_entry_cli = "/".join([""] + keys[2:])
                prefix_toml = ".".join([f'"{key}"' if "." in key else key for key in keys[:2]])
                prefix_cli = "/".join([""] + keys[:2])
            else:
                prefix_toml = ""
                prefix_cli = ""
                key_entry_toml = ".".join([f'"{key}"' if "." in key else key for key in keys])
                key_entry_cli = "/".join([""] + keys)
            # get value
            value = settings
            for key in keys:
                value = value[key]
            # check if key if in toml content
            key_toml = ".".join([f'"{key}"' if "." in key else key for key in keys])
            index = None
            for i, line in enumerate(content_lines):
                if line.startswith(f"{key_toml} =") or line.startswith(f"{key_toml}="):
                    index = i
                    break
            if index is None:
                return {}
            # get description
            description = []
            for i in reversed(range(index)):
                if content_lines[i].startswith("# "):
                    description.append(content_lines[i][2:])
                elif content_lines[i].startswith("#"):
                    description.append(content_lines[i][1:])
                else:
                    break
            description = "".join(reversed(description))
            return {
                "entry": {"toml": key_entry_toml, "cli": key_entry_cli},
                "prefix": {"toml": prefix_toml, "cli": prefix_cli},
                "type": type(value).__name__,
                "value": f"'{value}'" if type(value) is str else value,
                "description": description,
            }

        result = []
        for key in get_subkeys(settings):
            data = get_entry_value_description(key, settings, content_lines)
            if data:
                result.append(data)
        return result

    # check for a manually-authored SETTINGS.md first
    # If SETTINGS.md exists, skip inline include since it's linked via the toctree section
    settings_md_path = os.path.join(ext_path, "docs", "SETTINGS.md")
    if os.path.isfile(settings_md_path):
        return

    # fall back to auto-generating settings from extension.toml
    config_path = os.path.join(ext_path, "config", "extension.toml")
    with open(config_path, "r") as file:
        lines = file.readlines()
    # get extension settings
    settings = ext_config.get("settings", {})
    if settings:
        result = parse_settings(settings, lines)
        content = ["Settings", "========\n"] if result else []
        ext_result = [item for item in result if item["prefix"]["toml"]]
        app_result = [item for item in result if not item["prefix"]["toml"]]

        if ext_result:
            # extension-settings table
            content += [
                "Extension Settings",
                "------------------\n",
                "The table list the extension-specific settings.\n",
                ".. list-table::",
                "    :header-rows: 1\n",
                "    * - Setting name",
                "      - Description",
                "      - Type",
                "      - Default value",
            ]
            for item in ext_result:
                if not item["description"]:
                    entry = item["entry"]["toml"]
                    if error_as_warn:
                        omni.repo.man.print_log(
                            f"  |-- '{entry}' setting description not filled in extension.toml", logging.WARN
                        )
                    else:
                        omni.repo.man.print_log(
                            f"  |-- '{entry}' setting description not filled in extension.toml", logging.ERROR
                        )
                        sys.exit(1)
                content += [
                    f"    * - ``{item['entry']['toml']}``",
                    f"      - {textwrap.indent(item['description'], prefix=' ' * 8)[8:]}",
                    f"      - ``{item['type']}``",
                    f"      - ``{item['value']}``",
                ]
            # extension-settings usage
            content += [
                f"""
The extension-specific settings can be either specified (set) or retrieved (get) in one of the following ways:

.. tab-set::
    .. tab-item:: Set setting

        .. tab-set::
            .. tab-item:: Command-line interface
                :sync: tab_cli

                Define the key and value of the setting as an application argument from a terminal.

                .. code-block:: bash

                    APP_SCRIPT.(sh|bat) --/exts/{ext_name}/SETTING_NAME=SETTING_VALUE

            .. tab-item:: Experience/extension configuration
                :sync: tab_toml

                Define the key and value of the setting under ``[settings]`` in an experience (``.kit``) file or an extension configuration (``extension.toml``) file.

                .. code-block:: ini

                    [settings]
                    exts."{ext_name}".SETTING_NAME = SETTING_VALUE

            .. tab-item:: By programming
                :sync: tab_carb

                Define the key and value of the setting using the carb framework (in Python).

                .. code-block:: python

                    import carb

                    settings = carb.settings.get_settings()
                    settings.set("/exts/{ext_name}/SETTING_NAME", SETTING_VALUE)

    .. tab-item:: Get setting

        .. tab-set::
            .. tab-item:: By programming
                :sync: tab_carb

                Define the key to query the value of the setting using the carb framework (in Python).

                .. code-block:: python

                    import carb

                    settings = carb.settings.get_settings()
                    value = settings.get("/exts/{ext_name}/SETTING_NAME")
"""
            ]

        if app_result:
            # app-settings table
            content += [
                "Other Settings",
                "--------------\n",
                "The extension changes some settings of the application or other extensions, which are listed in the table below.\n",
                ".. list-table::",
                "    :header-rows: 1\n",
                "    * - Application/extension setting",
                "      - Description",
                "      - Value",
            ]
            for item in app_result:
                content += [
                    f"    * - ``{item['entry']['toml']}``",
                    f"      - {textwrap.indent(item['description'], prefix=' ' * 8)[8:]}",
                    f"      - ``{item['value']}``",
                ]

        # read index.rst
        file_path = os.path.join(ext_path, "docs", "index.rst")
        with open(file_path, "r") as file:
            src = file.readlines()
        # apply content
        src = _apply_autogenerated_content(src, "settings", content if content else None)
        # write index.rst
        with open(file_path, "w") as file:
            file.writelines(src)


def generate_extension_toctree(ext_path, ext_name, ext_config, error_as_warn):
    # Include available doc files inline into index.rst and add them to a hidden toctree
    # to prevent Sphinx "not included in any toctree" warnings.
    docs_dir = os.path.join(ext_path, "docs")

    # Files to inline via include directive
    include_candidates = [
        ("Overview.md", os.path.join(docs_dir, "Overview.md")),
        ("commands_api.md", os.path.join(docs_dir, "commands_api.md")),
        ("USD_SCHEMAS.md", os.path.join(docs_dir, "USD_SCHEMAS.md")),
        ("SETTINGS.md", os.path.join(docs_dir, "SETTINGS.md")),
    ]

    content_lines = []
    hidden_toctree_entries = []  # suppress Sphinx warnings for inlined files
    visible_toctree_entries = []  # shown as clickable links

    for include_path, abs_path in include_candidates:
        if not os.path.isfile(abs_path):
            continue
        toctree_entry = include_path.rsplit(".", 1)[0]  # strip extension
        hidden_toctree_entries.append(f"    {toctree_entry}")
        # Build include directive (use myst parser for .md files)
        if include_path.endswith(".md"):
            content_lines.append(f".. include:: {include_path}")
            content_lines.append(f"   :parser: myst_parser.sphinx_\n")
        else:
            content_lines.append(f".. include:: {include_path}\n")

    # Include python_api.md in the hidden toctree only when generate_extension_python_api
    # will skip it (i.e. "No public API" files). Extensions with real API content get a
    # visible toctree entry from generate_extension_python_api instead.
    python_api_path = os.path.join(ext_path, "config", "python_api.md")
    if os.path.isfile(python_api_path):
        with open(python_api_path, "r") as f:
            if "No public API" in f.read():
                hidden_toctree_entries.append("    ../config/python_api")

    # Add hidden toctree to suppress Sphinx warnings for inlined files
    if hidden_toctree_entries:
        content_lines.append(".. toctree::")
        content_lines.append("    :hidden:\n")
        content_lines.extend(hidden_toctree_entries)

    if not content_lines:
        return

    # read index.rst
    file_path = os.path.join(ext_path, "docs", "index.rst")
    with open(file_path, "r") as file:
        src = file.readlines()
    # apply content
    src = _apply_autogenerated_content(src, "toctree", content_lines)
    # write index.rst
    with open(file_path, "w") as file:
        file.writelines(src)


def generate_extension_python_api(ext_path, ext_name, ext_config, error_as_warn):
    # Add a visible toctree link to python_api.md at the bottom of the page
    python_api_path = os.path.join(ext_path, "config", "python_api.md")
    if not os.path.isfile(python_api_path):
        return
    with open(python_api_path, "r") as f:
        if "No public API" in f.read():
            return
    content = [
        ".. toctree::",
        "    :maxdepth: 1\n",
        "    Python API <../config/python_api>",
    ]
    # read index.rst
    file_path = os.path.join(ext_path, "docs", "index.rst")
    with open(file_path, "r") as file:
        src = file.readlines()
    # apply content
    src = _apply_autogenerated_content(src, "python-api", content)
    # write index.rst
    with open(file_path, "w") as file:
        file.writelines(src)


def generate_extension_ogn(ext_path, ext_name, ext_config, error_as_warn):
    # copy ogn/docs
    src_dir = os.path.join(ext_path, "ogn", "docs")
    dst_dir = os.path.join(ext_path, "docs", "ogn")
    ogn_docs_files = glob.glob(os.path.join(src_dir, "*.rst"))
    if not ogn_docs_files:
        return
    # copy ogn/docs to docs/ogn
    omni.repo.man.print_log(f"  |-- Collecting ogn docs", logging.INFO)
    shutil.copytree(src_dir, dst_dir, dirs_exist_ok=True)
    ogn_docs_files = glob.glob(os.path.join(dst_dir, "*.rst"))
    if not ogn_docs_files:
        omni.repo.man.print_log(f"  |-- Skipping ogn docs generation: no .rst files found", logging.WARN)
        return
    # build content
    content = [
        "Omnigraph Nodes",
        "===============\n",
        "The extension exposes the following Omnigraph nodes:\n",
        ".. toctree::",
        "    :glob:",
        "    :maxdepth: 1\n",
        "    ogn/*",
    ]
    # read index.rst
    file_path = os.path.join(ext_path, "docs", "index.rst")
    with open(file_path, "r") as file:
        src = file.readlines()
    # apply content
    src = _apply_autogenerated_content(src, "ogn", content)
    # write index.rst
    with open(file_path, "w") as file:
        file.writelines(src)


def generate_extension_custom(ext_path, ext_name, ext_config, sections, error_as_warn):
    # read index.rst
    file_path = os.path.join(ext_path, "docs", "index.rst")
    with open(file_path, "r") as file:
        src = file.readlines()
    # iterate for each custom section
    for section in sections:
        if isinstance(section, dict):
            # apply content
            custom_file_path = next(iter(section.values()))
            section_name = next(iter(section.keys()))

            # Check if the path is relative to docs or has a parent directory reference
            if custom_file_path.startswith("../"):
                # Handle paths that point outside of docs directory
                absolute_custom_file_path = os.path.normpath(os.path.join(ext_path, "docs", custom_file_path))
            else:
                # Regular path within docs directory
                absolute_custom_file_path = os.path.join(ext_path, "docs", custom_file_path)

            if os.path.isfile(absolute_custom_file_path):
                # Check if it's a Markdown file
                if custom_file_path.endswith(".md"):
                    # For Markdown files, use the myst-parser directive
                    content = f".. include:: {custom_file_path}\n   :parser: myst_parser.sphinx_"
                else:
                    # For RST files, use the standard include directive
                    content = f".. include:: {custom_file_path}"

                src = _apply_autogenerated_content(src, section_name, content)
            else:
                src = _apply_autogenerated_content(src, section_name, None)
    # write index.rst
    with open(file_path, "w") as file:
        file.writelines(src)


def setup_repo_tool(parser: argparse.ArgumentParser, config: Mapping) -> Callable:
    parser.description = """
Generate extension documentations.

Document sections
=================

The tool allows configuring how the sections are organized via the 'sections'
list (in 'repo_extension_docs' config). If not specified, the default order is:

  Section name     Description
  ---------------- --------------------------------------------------------------
  reference        Cross-referencing label. This should be always the first one!
  title            Extension name and title (from extension.toml)
  deprecation      Deprecation warning (from extension.toml)
  version          Extension version (from extension.toml)
  description      Extension description (from extension.toml, if any)
  preview          Preview image (from extension.toml, if file size > 1KB)
  enable-extension Autogenerated steps to enable the extension
  settings         Autogenerated extension settings (from extension.toml, if any)
  ogn              OmniGraph post-build generated documentation (if any)

Custom sections can also be specified as a dictionary where the key is the custom
section name and the value is the path to the .rst file with the custom content.
Path should be relative to the 'index.rst' file in the extension 'docs' folder.
Example:

  sections = [
    "reference",
    { "api": "api.rst" },
    ...
  ]

Documenting custom sections
===========================

Custom sections are included as document fragments via the 'include' directive.
Therefore, they should only use the following section headers:

  =  for sections
  -  for sub-sections
  ^  for sub-sub-sections
  "  for paragraphs

Since C++ API documentation is generated via breathe (Sphinx/Doxygen bridge) in
a unique location, mention to C++ API in extension docs should be created using
cross-referencing to extension namespace via the :any: or :ref: tags.
Example:

  Give the extension: MY.CUSTOM.EXTENSION

  * :any:`MY::CUSTOM::EXTENSION`
  * :ref:`MY::CUSTOM::EXTENSION <namespaceMY_1_1CUSTOM_1_1EXTENSION>`

CLI arguments
=============
"""
    parser.formatter_class = argparse.RawTextHelpFormatter
    parser.add_argument(
        "--no-overwrite-index",
        required=False,
        default=False,
        action="store_true",
        help=(
            "Whether not to overwrite existing 'docs/index.rst' files. "
            "Note that only content outside the autogenerated sections will not be overwritten."
        ),
    )
    parser.add_argument(
        "--error-as-warn",
        required=False,
        default=False,
        action="store_true",
        help="Whether to treat errors as warnings. If not set, execution will terminate when an error is detected.",
    )
    omni.repo.man.add_config_arg(parser)

    def run_repo_tool(options: Mapping, config: Mapping):
        # get repo config
        repo_tool_config = config["repo_extension_docs"]
        sections = repo_tool_config.get("sections", DEFAULT_SECTIONS)
        build_extension_paths = repo_tool_config["build_extension_paths"]
        source_extension_paths = repo_tool_config["source_extension_paths"]
        excluded_extensions = repo_tool_config.get("excluded_extensions", [])

        for build_extension_path in build_extension_paths:
            # resolve and check path
            build_extension_path = omni.repo.man.resolve_tokens(build_extension_path)
            if not os.path.isdir(build_extension_path):
                omni.repo.man.print_log(f"Search path ({build_extension_path}) doesn't exist", logging.WARN)
                continue
            directories = [
                item
                for item in os.listdir(build_extension_path)
                if os.path.isdir(os.path.join(build_extension_path, item))
            ]
            for ext_name in sorted(directories):
                # check for excluded extensions
                if ext_name in excluded_extensions:
                    omni.repo.man.print_log(f"[SKIPPED] {ext_name} (marked as excluded)", logging.INFO)
                    continue
                # setup extension path and config
                omni.repo.man.print_log(f"{ext_name}", logging.INFO)
                ext_path = os.path.join(build_extension_path, ext_name)
                try:
                    ext_config = _load_extension_config(ext_path, options.error_as_warn)
                except FileNotFoundError as e:
                    omni.repo.man.print_log(f"  |-- Skipping (no config/extension.toml): {e}", logging.WARN)
                    continue
                # create docs/index.rst file
                create_index(ext_path, ext_name, ext_config, sections, overwrite=not options.no_overwrite_index)
                # generate extension docs
                generate_extension_metadata(ext_path, ext_name, ext_config, options.error_as_warn)
                generate_extension_enable(ext_path, ext_name, ext_config, options.error_as_warn)
                generate_extension_settings(ext_path, ext_name, ext_config, options.error_as_warn)
                generate_extension_toctree(ext_path, ext_name, ext_config, options.error_as_warn)
                generate_extension_ogn(ext_path, ext_name, ext_config, options.error_as_warn)
                generate_extension_custom(ext_path, ext_name, ext_config, sections, options.error_as_warn)
                generate_extension_python_api(ext_path, ext_name, ext_config, options.error_as_warn)

                # included extsbuild extensions needs to be copied to docs/extsbuild
                extsbuild_exts_includes = repo_tool_config.get("extsbuild_exts_includes", [])
                if ext_name in extsbuild_exts_includes:
                    # Get the root directory by going up from source_extension_paths[0]
                    root_dir = os.path.dirname(os.path.dirname(source_extension_paths[0]))
                    destination_dir = os.path.join(root_dir, "docs", "extsbuild", ext_name)

                    copy_files_from_folder(
                        ext_path,
                        destination_dir,
                        ["*.rst", "*.toml"],
                        recursive=True,
                        preserve_structure=True,
                        overwrite=True,
                    )

    return run_repo_tool
