config = {
    "task_name": "Cartpole",
    "seed": 42,
    "torch_deterministic": False,
    "pipeline": "gpu",
    "sim_device": "cuda:0",
    "device_id": 0,
    "rl_device": "cuda:0",
    "test": False,
    "checkpoint": "",
    "evaluation": False,
    "mt_timeout": 90,
}

task_config = {
    "name": "Cartpole",
    "physics_engine": "physx",
    "env": {
        "numEnvs": 512,
        "envSpacing": 4.0,
        "resetDist": 3.0,
        "maxEffort": 400.0,
        "clipObservations": 5.0,
        "clipActions": 1.0,
        "controlFrequencyInv": 2,
    },
    "sim": {
        "dt": 0.0083,
        "use_gpu_pipeline": True,
        "gravity": [0.0, 0.0, -9.81],
        "add_ground_plane": True,
        "add_distant_light": False,
        "use_fabric": True,
        "enable_scene_query_support": False,
        "disable_contact_processing": False,
        "enable_cameras": False,
        "default_physics_material": {"static_friction": 1.0, "dynamic_friction": 1.0, "restitution": 0.0},
        "physx": {
            "worker_thread_count": 4,
            "solver_type": 1,
            "use_gpu": True,
            "solver_position_iteration_count": 4,
            "solver_velocity_iteration_count": 0,
            "contact_offset": 0.02,
            "rest_offset": 0.001,
            "bounce_threshold_velocity": 0.2,
            "friction_offset_threshold": 0.04,
            "friction_correlation_distance": 0.025,
            "enable_sleeping": True,
            "enable_stabilization": True,
            "max_depenetration_velocity": 100.0,
            "gpu_max_rigid_contact_count": 524288,
            "gpu_max_rigid_patch_count": 81920,
            "gpu_found_lost_pairs_capacity": 1024,
            "gpu_found_lost_aggregate_pairs_capacity": 262144,
            "gpu_total_aggregate_pairs_capacity": 1024,
            "gpu_max_soft_body_contacts": 1048576,
            "gpu_max_particle_contacts": 1048576,
            "gpu_heap_capacity": 67108864,
            "gpu_temp_buffer_capacity": 16777216,
            "gpu_max_num_partitions": 8,
        },
        "Cartpole": {
            "override_usd_defaults": False,
            "enable_self_collisions": False,
            "enable_gyroscopic_forces": True,
            "solver_position_iteration_count": 4,
            "solver_velocity_iteration_count": 0,
            "sleep_threshold": 0.005,
            "stabilization_threshold": 0.001,
            "density": -1,
            "max_depenetration_velocity": 100.0,
            "contact_offset": 0.02,
            "rest_offset": 0.001,
        },
    },
}
