[core]
reloadable = true
order = 0

[package]
version = "2.2.4"
category = "Simulation"
title = "ROS Bridge"
description = "The ROS Bridge extension enables communication between the Isaac Sim and ROS 1 systems. It allows for the publishing and subscribing of ROS topics and services via OmniGraph nodes and Action graphs. ROS publishers, subscribers and services are only active when play is pressed. A lightweight set of ROS libraries included with Isaac Sim are automatically loaded when enabling this extension."
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.ros1.bridge"
keywords = ["isaac", "ROS"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.platform = true
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.dynamic_control" = {}
"isaacsim.sensors.physx" = {}
"isaacsim.core.api" = {}
"isaacsim.core.deprecation_manager" = {}
"isaacsim.core.nodes" = {}
"isaacsim.sensors.physics" = {}
"isaacsim.sensors.camera" = {}
"isaacsim.sensors.rtx" = {}
"omni.syntheticdata" = {}
"omni.replicator.core" = {}
"isaacsim.robot.schema" = {}
"omni.graph" = {}
"omni.graph.tools" = {}
"usdrt.scenegraph" = {}
"isaacsim.storage.native" = {}
"isaacsim.gui.components" = {}
"isaacsim.examples.browser" = {}

[[python.module]]
name = "isaacsim.ros1.bridge"

[[python.module]]
name = "omni.isaac.rospy"

[[python.module]]
name = "isaacsim.ros1.bridge.tests"
public = false

#[[python.module]]
#name = "isaacsim.ros1.bridge.ogn.tests"

[[python.module]]
name = "isaacsim.ros1.bridge.scripts.samples.ros_samples"

[[python.module]]
name = "isaacsim.ros1.bridge.scripts.samples.ros_moveit_sample"

[[native.plugin]]
path = "bin/isaacsim.ros1.bridge.plugin"
recursive = false

[fswatcher.paths]
exclude = ["*/noetic*", "*/bin", "*/__pycache__/*", "*/.git/*"]

[fswatcher.patterns]
include = ["*.ogn", "*.py", "*.toml"]
exclude = ["Ogn*Database.py"]

[settings]
# Name of the ROS node created by the extension.
exts."isaacsim.ros1.bridge".nodeName = "OmniIsaacRosBridge"

[[test]]
timeout = 1200
dependencies = [
    "omni.graph.ui",
    "isaacsim.robot.wheeled_robots",
]

args = [
    "--/app/gatherRenderResults=false"
]

stdoutFailPatterns.exclude = [
    "*WARNING: cannot load logging configuration file*", # exclude warning as failure
    "*[Error] [omni.graph.core.plugin] /ActionGraph/PublishTF: [/ActionGraph] Please specify atleast one target prim for the ROS pose tree component*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_isaacsim_ros1_bridge_ROS1PublishJointState: [/TestGraph] Could not find target prim*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_isaacsim_ros1_bridge_ROS1PublishTransformTree: [/TestGraph] Please specify atleast one target prim for the ROS pose tree component*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_isaacsim_ros1_bridge_ROS1PublishImage: [/TestGraph] Width 0 or height 0 is not valid*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_isaacsim_ros1_bridge_ROS1PublishLaserScan: [/TestGraph] Number of rows must be equal to 1. High LOD not supported for LaserScan, only 2D Lidar Supported for LaserScan. Please disable Lidar High LOD setting*",
]

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.0.0"