[core]
reloadable = true
order = 0

[package]
version = "2.0.0"
category = "Simulation"
title = "Benchmark Services"
description = "This extension provides benchmarking utilities"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.benchmark.services"
keywords = ["isaac", "benchmark", "analyze"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.benchmark.services" = {}
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "omni.isaac.benchmark.services"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.benchmark.services."