[core]
reloadable = true
order = 0

[package]
version = "1.0.2"
category = "SyntheticData"
title = "Isaac Sim Replicator Scene Blox"
description = "The extension implements SceneBlox, a rule-based randomized scene generation workflow using the wave function collapse algorithm."
authors = ["Isaac Sim Team"]
keywords = ["isaac", "omniverse", "scene blox"]
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}
"isaacsim.storage.native" = {}

[[python.module]]
name = "isaacsim.replicator.scene_blox"