[core]
reloadable = true
order = 0

[package]
version = "1.0.2"
category = "Simulation"
title = "Isaac Sim Example Nodes"
description = "This extension adds Omnigraph example nodes for Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.examples_nodes"
keywords = ["isaac", "omnigraph", "examples"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0."

[dependencies]
"isaacsim.core.deprecation_manager" = {}