[core]
reloadable = true
order = 0

[package]
version = "0.1.3"
category = "Simulation"
title = "Isaac Sim Physics Utilities"
description = "Collision and Physics Utils"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.physics_utilities"
keywords = ["isaac", "physics", "utils",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.physx" = {}
"omni.isaac.ui" = {}

[[python.module]]
name = "omni.isaac.physics_utilities"

[[python.module]]
name = "omni.isaac.physics_utilities.tests"
