[package]
version = "0.3.3"
category = "Setup"
title = "Isaac Sim Assets Check"
description = "This Extension checks if the assets are updated."
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.assets_check"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
toggleable = false

[dependencies]
"omni.usd" = {}
"omni.ui" = { order = -100 }

# Isaac Sim Core Extensions
"omni.isaac.core" = {}

[[python.module]]
name = "omni.isaac.assets_check"


