[manipulators]
reloadable = true
order = 0

[package]
version = "3.0.0"
category = "Simulation"
title = "Isaac Sim Manipulators"
description = "Manipulators"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.manipulators"
keywords = ["isaac", "manipulators"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[deprecation] 
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.robot.manipulators."


[dependencies]

"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot.manipulators" = {}


[[python.module]]
name = "omni.isaac.manipulators"
