display_name = "Domain Randomization"

[package]
version = "0.1.1"
title = "Domain Randomization"
description = "This extension randomizes domain parameters in Omniverse Kit"
authors = ["Shoubhik Debnath <sdebnath@nvidia.com>", "Hammad Mazhar <hmazhar@nvidia.com>"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac/dr"
keywords = ["kit", "domain", "randomizer"]
changelog = "docs/CHANGELOG.md"
category = "Isaac Sim"
readme = "docs/README.md"
preview_image = "package/preview.png"
icon = "package/icon.png"

[dependencies]
"omni.kit.editor" = {}
"omni.client" = {}

[[python.modules]]
name = "omni.isaac.dr"

[[python.modules]]
name = "omni.isaac.dr.scripts.samples"

[[python.modules]]
name = "omni.isaac.dr.scripts.random_room_sample"

[[python.modules]]
name = "omni.isaac.DrSchema"
public = false

[[native.plugins]]
path = "bin/*.plugin"
recursive = false

[[libraries]]
path = "bin/${lib_prefix}drSchema${lib_ext}"
