# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Copy .pyi stub files from the build directory to source directories.

This script finds .pyi files generated by stubgen in the build directory and copies
them back to the corresponding source directories. It uses symlinks in the build
directory to determine the correct source location.

This is a workaround for bugs in the kit-kernel's pybind11_stubgen.py script where
the --copyback feature doesn't work on Linux due to:
1. Missing 'import shutil'
2. Using Windows path separators ('\\') instead of os.sep

Usage:
    python tools/isaac/copy_pyi_stubs.py
    python tools/isaac/copy_pyi_stubs.py --config release
    python tools/isaac/copy_pyi_stubs.py --dry-run
    python tools/isaac/copy_pyi_stubs.py --verbose
"""

import argparse
import os
import shutil
import sys
from pathlib import Path
from typing import Dict


def find_pyi_files(build_exts_dir: str, verbose: bool = False) -> list[tuple[Path, Path]]:
    """Find all .pyi files in the build extensions directory.

    Args:
        build_exts_dir: Path to the build extensions directory.
        verbose: If True, print detailed information.

    Returns:
        List of tuples (pyi_file_path, containing_directory).
    """
    pyi_files = []
    build_path = Path(build_exts_dir)

    if not build_path.exists():
        print(f"Error: Build directory does not exist: {build_exts_dir}")
        return pyi_files

    # Walk the directory tree manually to handle symlinks properly
    for root, dirs, files in os.walk(build_path, followlinks=False):
        root_path = Path(root)
        for filename in files:
            if not filename.endswith(".pyi"):
                continue

            pyi_file = root_path / filename

            # Skip __init__.pyi files as they are typically not C++ bindings
            if filename == "__init__.pyi":
                if verbose:
                    print(f"  Skipping __init__.pyi: {pyi_file}")
                continue

            # Only include _*.pyi files (C++ binding stubs)
            if not filename.startswith("_"):
                if verbose:
                    print(f"  Skipping non-binding stub: {pyi_file}")
                continue

            pyi_files.append((pyi_file, pyi_file.parent))
            if verbose:
                print(f"  Found: {pyi_file}")

    return pyi_files


def find_source_target(pyi_dir: Path, verbose: bool = False) -> Path | None:
    """Find the source directory target by looking for symlinks in the pyi directory.

    The build directory typically contains symlinks like:
        impl -> /path/to/source/extensions/ext.name/python/impl

    We use these to determine where the .pyi file should be copied.

    Args:
        pyi_dir: Directory containing the .pyi file.
        verbose: If True, print detailed information.

    Returns:
        Path to the source directory where the .pyi should be copied, or None if not found.
    """
    for item in pyi_dir.iterdir():
        if item.is_symlink():
            link_target = item.resolve()
            if link_target.exists():
                # The parent of the symlink target is the source directory
                source_dir = link_target.parent
                if verbose:
                    print(f"    Found symlink: {item.name} -> {link_target}")
                    print(f"    Source target: {source_dir}")
                return source_dir

    return None


def copy_pyi_to_source(
    pyi_file: Path,
    source_dir: Path,
    dry_run: bool = False,
    verbose: bool = False,
) -> bool:
    """Copy a .pyi file to the source directory.

    Args:
        pyi_file: Path to the .pyi file.
        source_dir: Path to the source directory.
        dry_run: If True, don't actually copy, just print what would be done.
        verbose: If True, print detailed information.

    Returns:
        True if successful (or would be successful in dry-run mode), False otherwise.
    """
    dest_file = source_dir / pyi_file.name

    if dry_run:
        print(f"  Would copy: {pyi_file.name}")
        print(f"    From: {pyi_file}")
        print(f"    To:   {dest_file}")
        return True

    try:
        shutil.copy2(pyi_file, dest_file)
        if verbose:
            print(f"  Copied: {pyi_file.name} -> {dest_file}")
        return True
    except Exception as e:
        print(f"  Error copying {pyi_file}: {e}")
        return False


def copy_pyi_stubs(
    config: str = "release",
    platform: str | None = None,
    dry_run: bool = False,
    verbose: bool = False,
) -> bool:
    """Copy all .pyi stub files from build to source directories.

    Args:
        config: Build configuration (e.g., "release", "debug").
        platform: Platform string (e.g., "linux-x86_64"). Auto-detected if None.
        dry_run: If True, don't actually copy, just print what would be done.
        verbose: If True, print detailed information.

    Returns:
        True if all copies succeeded, False otherwise.
    """
    # Determine platform
    if platform is None:
        if sys.platform == "linux":
            platform = "linux-x86_64"
        elif sys.platform == "win32":
            platform = "windows-x86_64"
        else:
            print(f"Warning: Unknown platform {sys.platform}, defaulting to linux-x86_64")
            platform = "linux-x86_64"

    # Find the script's root directory (repo root)
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent.parent

    # Build paths to search
    build_base = repo_root / "_build" / platform / config
    ext_dirs = [
        build_base / "exts",
        build_base / "extsDeprecated",
        build_base / "extsInternal",
    ]

    if verbose:
        print(f"Repository root: {repo_root}")
        print(f"Build base: {build_base}")
        print(f"Config: {config}")
        print(f"Platform: {platform}")
        print()

    if dry_run:
        print("=== DRY RUN MODE - No files will be copied ===\n")

    total_copied = 0
    total_failed = 0
    total_skipped = 0

    for ext_dir in ext_dirs:
        if not ext_dir.exists():
            if verbose:
                print(f"Skipping non-existent directory: {ext_dir}")
            continue

        print(f"Scanning: {ext_dir}")
        pyi_files = find_pyi_files(str(ext_dir), verbose)

        if not pyi_files:
            print("  No .pyi stub files found.\n")
            continue

        print(f"  Found {len(pyi_files)} .pyi stub file(s)")

        for pyi_file, pyi_dir in pyi_files:
            if verbose:
                print(f"\nProcessing: {pyi_file}")

            source_dir = find_source_target(pyi_dir, verbose)

            if source_dir is None:
                if verbose:
                    print(f"  Warning: No symlink found in {pyi_dir}, skipping")
                total_skipped += 1
                continue

            # Verify source directory is within the repo and not in build directory
            try:
                source_dir.relative_to(repo_root)
            except ValueError:
                if verbose:
                    print(f"  Warning: Source dir {source_dir} is outside repo, skipping")
                total_skipped += 1
                continue

            # Skip if source directory is inside the build directory
            try:
                source_dir.relative_to(build_base)
                if verbose:
                    print(f"  Warning: Source dir {source_dir} is inside build directory, skipping")
                total_skipped += 1
                continue
            except ValueError:
                pass  # Good - source_dir is not inside build_base

            # Skip if destination would be the same as source
            dest_file = source_dir / pyi_file.name
            if dest_file == pyi_file:
                if verbose:
                    print(f"  Warning: Destination same as source, skipping")
                total_skipped += 1
                continue

            if copy_pyi_to_source(pyi_file, source_dir, dry_run, verbose):
                total_copied += 1
            else:
                total_failed += 1

        print()

    # Summary
    print("=" * 60)
    print("Summary:")
    print(f"  Copied:  {total_copied}")
    print(f"  Failed:  {total_failed}")
    print(f"  Skipped: {total_skipped}")

    if dry_run:
        print("\n(Dry run - no files were actually copied)")

    return total_failed == 0


def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description="""
Copy .pyi stub files from the build directory to source directories.

This script finds .pyi files generated by stubgen in the build directory and copies
them back to the corresponding source directories. It uses symlinks in the build
directory to determine the correct source location.

This enables mypy to find type stubs for C++ extension modules when checking
source files directly.
        """,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "-c",
        "--config",
        default="release",
        help="Build configuration (default: release)",
    )
    parser.add_argument(
        "-p",
        "--platform",
        default=None,
        help="Platform string (default: auto-detect)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without actually copying files",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable verbose output for debugging",
    )

    args = parser.parse_args()

    success = copy_pyi_stubs(
        config=args.config,
        platform=args.platform,
        dry_run=args.dry_run,
        verbose=args.verbose,
    )

    sys.exit(0 if success else 1)


def setup_repo_tool(parser: argparse.ArgumentParser, config: Dict):
    """Set up the repo tool for copying .pyi stub files.

    Args:
        parser: ArgumentParser instance to add arguments to.
        config: Configuration dictionary from repo.toml/repo_internal.toml.

    Returns:
        Callable that runs the tool with parsed arguments.
    """
    parser.add_argument(
        "-c",
        "--config",
        default="release",
        help="Build configuration (default: release)",
    )
    parser.add_argument(
        "-p",
        "--platform",
        default=None,
        help="Platform string (default: auto-detect)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without actually copying files",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable verbose output for debugging",
    )

    def run_tool(args, config=config):
        """Run the copy_pyi_stubs tool with the given arguments.

        Args:
            args: Parsed command-line arguments.
            config: Configuration dictionary.

        Returns:
            Exit code (0 for success, 1 for failure).
        """
        success = copy_pyi_stubs(
            config=args.config,
            platform=args.platform,
            dry_run=args.dry_run,
            verbose=args.verbose,
        )
        return 0 if success else 1

    return run_tool


if __name__ == "__main__":
    main()
