[core]
reloadable = true
order = 0

[package]
version = "4.0.0"
category = "Simulation"
title = "Isaac Sim Samples"
description = "Sample extensions for Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.examples.interactive"
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.ui" = {}
"isaacsim.core.api" = {}
"isaacsim.robot.manipulators" = {}
"isaacsim.robot.manipulators.examples" = {}
"omni.isaac.motion_generation" = {}
"omni.graph.action" = {}
"omni.graph.nodes" = {}
"omni.graph.core" = {}
"omni.isaac.quadruped" = {}
"omni.isaac.wheeled_robots" = {}
"isaacsim.cortex.framework" = {}
"isaacsim.cortex.behaviors" = {}
"omni.isaac.nucleus" = {}

[[python.module]]
name = "isaacsim.examples.interactive.tests"


[[python.module]]
name = "isaacsim.examples.interactive.kaya_gamepad"

[[python.module]]
name = "isaacsim.examples.interactive.omnigraph_keyboard"

[[python.module]]
name = "isaacsim.examples.interactive.follow_target"

[[python.module]]
name = "isaacsim.examples.interactive.path_planning"

[[python.module]]
name = "isaacsim.examples.interactive.simple_stack"

[[python.module]]
name = "isaacsim.examples.interactive.bin_filling"

[[python.module]]
name = "isaacsim.examples.interactive.robo_factory"

[[python.module]]
name = "isaacsim.examples.interactive.robo_party"

[[python.module]]
name = "isaacsim.examples.interactive.hello_world"

[[python.module]]
name = "isaacsim.examples.interactive.replay_follow_target"

[[python.module]]
name = "isaacsim.examples.interactive.surface_gripper"

[[python.module]]
name = "isaacsim.examples.interactive.quadruped"

[[python.module]]
name = "isaacsim.examples.interactive.user_examples"

[[python.module]]
name = "isaacsim.examples.interactive.ur10_palletizing"

[[python.module]]
name = "isaacsim.examples.interactive.franka_cortex"

[[python.module]]
name = "isaacsim.examples.interactive.humanoid"

[[test]]
timeout = 1200

stdoutFailPatterns.exclude = [
    '*[Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.*', # feature not included in Windows
]