[core]
reloadable = true
order = 0

[package]
title = "Isaac Sim Kit Helpers"
description = "This Extension that provides a way to launch a python app"
authors = ["Isaac Sim Team"]
toggleable = false

[dependencies]
"omni.physx" = {} # loads usd libs we import
"omni.isaac.core" = {} 

[[python.module]]
name = "omni.isaac.kit"
