[package]
version = "2.0.18"
category = "Simulation"
title = "Isaac Sim Occupancy Map"
description = "The Isaac Sim Occupancy Map extension provides tools to generate occupancy maps for a Scene"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.asset.gen.omap"
keywords = ["isaac", "occupancy map"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.util.debug_draw" = {}
"omni.kit.pip_archive" = {}
"omni.physx" = {}

[[python.module]]
name = "isaacsim.asset.gen.omap"

[[python.module]]
name = "isaacsim.asset.gen.omap.tests"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[[test]]
timeout = 900
dependencies = [
    "isaacsim.core.utils",
    "isaacsim.storage.native",
]
args = [
    '--/persistent/isaac/asset_root/default = "omniverse://isaac-dev.ov.nvidia.com"',
]