[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Simulation"
title = "Isaac Sim Synthetic Data Utilities"
description = "Utility functions for generating synthetic data"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.synthetic_utils"
keywords = ["isaac", "synthetic", "utils"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.syntheticdata" = {}
"omni.kit.asset_converter" = {}

[[python.module]]
name = "omni.isaac.synthetic_utils"

[[python.module]]
name = "omni.isaac.synthetic_utils.scripts.syntheticdata_recorder"
public = false

[python.pipapi]
# "matplotlib==3.3.1" Fails on TC, removing temporarily
requirements = ["pillow==7.2.0"]