[core]
reloadable = true
order = 0

[package]
version = "0.1.6"
category = "Simulation"
title = "Isaac Sim Motion Planning"
description = "Extension that provides support for RMPs"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.motion_planning"
keywords = ["isaac", "motion planning", "rmp"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.test" = {}
"omni.isaac.dynamic_control" = {}

[[python.module]]
name = "omni.isaac.motion_planning"

[[python.module]]
name = "omni.isaac.motion_planning.tests"

[[python.module]]
name = "lula"

[[native.library]]
path = "bin/libconsole_bridge.so"

[[native.library]]
path = "bin/libtinyxml.so"

[[native.library]]
path = "bin/liburdfdom_model.so"

[[native.library]]
path = "bin/libyaml-cpp.so"

[[native.library]]
path = "bin/liblula_util.so"

[[native.library]]
path = "bin/liblula_math.so"

[[native.library]]
path = "bin/liblula_world.so"

[[native.library]]
path = "bin/liblula_fabrics.so"

[[native.library]]
path = "bin/liblula_interface.so"

[[native.library]]
path = "bin/liblula_opt.so"

[[native.library]]
path = "bin/liblula_kinematics.so"

[[native.library]]
path = "bin/liblula_motion_opt.so"

[[native.library]]
path = "bin/liblula_motion_planning.so"

[[native.library]]
path = "bin/liblula_rmpflow.so"

[[native.library]]
path = "bin/liblula_visualization.so"

[[native.library]]
path = "bin/liblula_scenario.so"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

