@echo off
setlocal

:: Setup python env from generated file (generated by tools/repoman/build.py)
if exist "%~dp0setup_python_env.bat" (
    call "%~dp0setup_python_env.bat"
)

:: The executable path will be where python is located. So we set Cabonite app path through env var:
set CARB_APP_PATH=%~dp0kit
set ISAAC_PATH=%~dp0
set EXP_PATH=%~dp0apps

:: By default use our python, but allow overriding it by checking if PYTHONEXE env var is defined:
IF "%PYTHONEXE%"=="" (
    set PYTHONEXE="%~dp0kit\python\python.exe"
)

call %PYTHONEXE% %*

if errorlevel 1 ( goto ErrorRunningPython )

:Success
endlocal
exit /B 0

:ErrorRunningPython
echo There was an error running python.
endlocal
exit /B 1
