// Generated by gencpp from file isaac_bridge/IsaacJSONRequest.msg
// DO NOT EDIT!


#ifndef ISAAC_BRIDGE_MESSAGE_ISAACJSONREQUEST_H
#define ISAAC_BRIDGE_MESSAGE_ISAACJSONREQUEST_H


#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>
#include <std_msgs/Header.h>

#include <map>
#include <string>
#include <vector>

namespace isaac_bridge
{
template <class ContainerAllocator>
struct IsaacJSONRequest_
{
    typedef IsaacJSONRequest_<ContainerAllocator> Type;

    IsaacJSONRequest_() : header(), json()
    {
    }
    IsaacJSONRequest_(const ContainerAllocator& _alloc) : header(_alloc), json(_alloc)
    {
        (void)_alloc;
    }


    typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
    _header_type header;

    typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other> _json_type;
    _json_type json;


    typedef boost::shared_ptr<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacJSONRequest_

typedef ::isaac_bridge::IsaacJSONRequest_<std::allocator<void>> IsaacJSONRequest;

typedef boost::shared_ptr<::isaac_bridge::IsaacJSONRequest> IsaacJSONRequestPtr;
typedef boost::shared_ptr<::isaac_bridge::IsaacJSONRequest const> IsaacJSONRequestConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>>::stream(s, "", v);
    return s;
}

} // namespace isaac_bridge

namespace ros
{
namespace message_traits
{


// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'isaac_bridge':
// ['/home/hmazhar/repos/srl_system/workspace/src/isaac_bridge/msg'], 'std_msgs':
// ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs':
// ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__',
// '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__',
// '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name',
// 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']


template <class ContainerAllocator>
struct IsFixedSize<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator> const> : TrueType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>>
{
    static const char* value()
    {
        return "bba21b380002512f5222266cbd4dc034";
    }

    static const char* value(const ::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0xbba21b380002512fULL;
    static const uint64_t static_value2 = 0x5222266cbd4dc034ULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_bridge/IsaacJSONRequest";
    }

    static const char* value(const ::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>>
{
    static const char* value()
    {
        return "std_msgs/Header header\n"
               "string json\n"
               "\n"
               "================================================================================\n"
               "MSG: std_msgs/Header\n"
               "# Standard metadata for higher-level stamped data types.\n"
               "# This is generally used to communicate timestamped data \n"
               "# in a particular coordinate frame.\n"
               "# \n"
               "# sequence ID: consecutively increasing ID \n"
               "uint32 seq\n"
               "#Two-integer timestamp that is expressed as:\n"
               "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
               "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
               "# time-handling sugar is provided by the client library\n"
               "time stamp\n"
               "#Frame this data is associated with\n"
               "string frame_id\n";
    }

    static const char* value(const ::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.header);
        stream.next(m.json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacJSONRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream& s, const std::string& indent, const ::isaac_bridge::IsaacJSONRequest_<ContainerAllocator>& v)
    {
        s << indent << "header: ";
        s << std::endl;
        Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
        s << indent << "json: ";
        Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other>>::stream(
            s, indent + "  ", v.json);
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_BRIDGE_MESSAGE_ISAACJSONREQUEST_H
