pages:
  tags: 
    - pages
  image:
    alpine:latest
  script:
    - apk add --no-cache p7zip wget
    - mkdir .public
    - echo "10.36.168.30 teamcity.nvidia.com" >> /etc/hosts
    - wget --no-verbose --output-document=docs.7z --no-check-certificate --http-user=svcgtlautomate '--http-password=@ut0M@t3GTL$cr1pt$' https://teamcity.nvidia.com/repository/download/Omniverse_IsaacSim_Develop_BuildAndPackaging_OmniDocsBuildLinuxX8664/.lastSuccessful/omniverse-robotics-docs%40%7Bbuild.number%7D.7z
    - 7z x docs.7z -o.public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - develop@Isaac/omni_isaac_sim