include:
# external
- project: 'omniverse/devplat/gitlab/templates/runners'
  file: 'modules/include.yml'
  ref: 1.9.3
- project: 'omniverse/devplat/gitlab/templates/common/utilities'
  file: 'modules/include.yml'
  ref: v1_latest
- project: 'omniverse/sectools/vault'
  file: ['templates/v2/omni-codesign-creds.yml', 'templates/v3/linux/codesign.gitlab-ci.yml']
- project: 'omniverse/sectools/vault'
  file: ['templates/v2/windows/repo-codesign-creds.yml', 'templates/v3/windows/codesign.gitlab-ci.yml']
- project: 'omniverse/sectools/vault'
  file: ['templates/v2/omni-packman-s3-creds.yml', 'templates/v3/linux/packman_s3.gitlab-ci.yml']
- project: 'omniverse/sectools/vault'
  file: ['templates/v2/windows/packman-s3-creds.gitlab-ci.yml', 'templates/v3/windows/packman_s3.gitlab-ci.yml']
- project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
  # local to devplat/gitlab/templates/runners, external to this repo:
  file: 'modules/common.yml'
- project: omniverse/benchmark/reggie
  #- project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
  #  file: 'modules/benchmarks.yml'
  ref: release/v2
  file: /ci/detect.yml
- project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
  # - project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
  #   file: 'modules/stage-build.yml'
  # - project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
  #   file: 'modules/etm.yml'
  file: 'modules/stage-deploy.yml'
- project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
  file: 'modules/stage-security.yml'
- project: 'omniverse/devplat/gitlab/templates/common/kit-extension'
  file: 'modules/sanitizers.yml'


# ==============================================================================================================
stages:
- check
- build
- test
- security
- deploy
- prod-test
- pages


# ==============================================================================================================
# Default values applied to all jobs
default:
  # Only retry on Gitlab failures (not on script failures for example)
  retry:
    max: 2
    when:
    - api_failure
    - runner_system_failure
    - stuck_or_timeout_failure
    - scheduler_failure
    - unknown_failure

workflow:
  auto_cancel:
    on_new_commit: interruptible
    on_job_failure: all
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    auto_cancel:
      on_new_commit: conservative
  - if: $CI_COMMIT_BRANCH == "develop"
    auto_cancel:
        on_new_commit: conservative
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_PROTECTED
    auto_cancel:
      on_new_commit: none
  - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_PROTECTED
    auto_cancel:
      on_new_commit: none



# ==============================================================================================================
# More variables can be found in common.yml - here we put the ones controlling the jobs workflow
variables:
  OSEC_NSPECT_ID: "NSPECT-8CX1-LP1G"
  OSEC_CHECKMARX_ENABLED: 'false'
  OSEC_GITLAB_SAST_ENABLED: 'false'
  OSEC_PULSE_TRUFFLEHOG_ENABLED: 'false'
  OSEC_OMNI_PULSE_ENABLED: 'false'
  OSEC_README_ENABLED: 'false' # WARNING: Also have the init() function get_nspectid_from_repo_toml() in there...
  ALLOW_PUBLISH_DOCS:
    value: "false"
    description: "Set to true to publish docs"
  ALLOW_PUBLISH_TO_LAUNCHER:
    value: "true"
    description: "Set to true to for Kit apps that are published to the Launcher. That adds jobs for that."
  ALLOW_PUBLISH_PYTHON_PACKAGES:
    value: "true"
    description: "Set to true to create and publish python packages."
  ALLOW_PUBLISH_EXTENSIONS:
    value: "true"
    description: "Set to true to publish extension updates."
  ALLOW_PUBLISH_CONTAINERS:
    value: "true"
    description: "Set to true to publish containers to NGC."
  ALLOW_SECURITY_SCAN:
    value: "false"
    description: "Set to true to trigger a security scan as a child pipeline (non blocking)"
  ALLOW_SCHEDULE_PIPELINE:
    value: "true"
    description: "Set to 'false' to disable schedule pipeline on a all jobs, useful to set it back on only some jobs."
  ALLOW_TAG_PIPELINE:
    value: "true"
    description: "Set to 'false' to disable tag pipeline on a all push jobs."
  RUN_EXTENSION_BENCHMARKS:
    value: "false"
    description: "Set to true to run benchmarks for kit extensions."
  RUN_ETM_TESTS:
    value: "false"
    description: "Set to true to run ETM tests for kit extensions. Only happens on push (extensions need to be published first)."
  DATADOG_TEST_VISIBILITY:
    value: "true"
    description: "Set to false to skip sending tests results to Datadog (internal)"
  OMNI_CI_ENABLE_CXX_COVERAGE:
    value: "false"
    description: "Set to 'true' to enable C++ code coverage testing."
  OMNI_CI_ENABLE_SANITIZERS:
    value: "false"
    description: "Set to 'true' to enable C++ sanitizer builds."
  RUN_BUMP_VERSION:
    value: "false"
    description: "Set to true to run bump version. Only happens on schedule."
  RUN_NIGHTLY_TESTS:
    value: "false"
    description: "Set to true to run nightly tests. Only happens on schedule."
  RUN_DOCS_BUILD:
    value: "false"
    description: "Set to true to build omni docs. Only happens on schedule."


# ==============================================================================================================
.check-common:
  stage: check
  timeout: 20 minutes
  interruptible: true
  rules:
  - if: $RUN_BUMP_VERSION == "true"
    when: never
  - !reference [.rules-workflow, rules]

.repo-artifacts:
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
    - _repo/repo.log
    - _repo/repolog*.txt


# ==============================================================================================================
# Rule for running nightly tests on scheduled pipeline on develop and release branches
.rules-bump-version:
  rules:
  - if: $CI_COMMIT_TITLE =~ /^Bumped version/
    when: never
  - if: $CI_PIPELINE_SOURCE == "schedule" && $RUN_BUMP_VERSION == "true" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /^release\/.*/)


# ==============================================================================================================
# Rule for running nightly tests on scheduled pipeline on protected and release branches
.rules-nightly-tests:
  rules:
  # allow schedule pipeline if RUN_NIGHTLY_TESTS is set to "true" and on protected and release/* branches
  - if: $CI_PIPELINE_SOURCE == "schedule" && $RUN_NIGHTLY_TESTS == "true" && ($CI_COMMIT_REF_PROTECTED == "true" || $CI_COMMIT_BRANCH =~ /^release\/.*/)
  - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /^release\/.*/)
    # allow on bump version
    changes:
    - VERSION.md
    - VERSION

.rules-build-docs:
  rules:
  # allow schedule pipeline if RUN_DOCS_BUILD is set to "true" and its scheduled
  - if: $CI_PIPELINE_SOURCE == "schedule" && $RUN_DOCS_BUILD == "true"
    when: always
  - when: never


# ==============================================================================================================
# Rule for running publisher on push on develop and release branches
.rules-version-changed:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /^release\/.*/)
    changes:
    - VERSION.md
    - VERSION


# ==============================================================================================================
# Job that ensures that the MR has a JIRA ticket reference in the title
check-jira-ticket:
  extends:
  - .check-common
  - .check-jira-ticket
  - .omni_nvks_runner
  allow_failure: true
  rules:
  - !reference [.rules-mr, rules]


# ==============================================================================================================
# Job to dump out the current configuration environment variables
dump-env-vars:
  extends:
  - .check-common
  - .dump-env-vars
  - .omni_nvks_runner
  allow_failure: true
  when: manual
  rules:
  - !reference [.rules-workflow, rules]


# ==============================================================================================================
check-code-format:
  extends:
  - .check-common
  - .repo-artifacts
  - .runner-utility-linux-x86_64
  variables:
    GIT_DEPTH: 0 # needed to update copyrights
  script:
  - ./repo.sh format --verify


# ==============================================================================================================
.build-artifacts:
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
    - _build/**/*.gcno # produced by the coverage build
    - _build/**/*.log
    - _build/packages/
    - _repo/repo.log
    - _repo/repolog*.txt


# ==============================================================================================================
.build-common:
  stage: build
  timeout: 3 hours
  interruptible: true
  extends:
  - .build-artifacts
  retry:
    max: 2
    when:
    - always
  rules:
  - if: $RUN_BUMP_VERSION == "true"
    when: never
  - !reference [.rules-workflow, rules]


# ==============================================================================================================
build-linux-x86_64-release:
  extends:
  - .build-common
  - .runner-build-linux-x86_64
  before_script:
  - set -eu
  - yum install -y bsdtar
  - yum install -y rdfind
  - !reference [.omni_s3_write_get_secrets, omni_s3_write_get_secrets]
  script:
  - ./repo.sh ci build -c release

# ==============================================================================================================
build-linux-x86_64-debug:
  extends:
  - .build-common
  - .runner-build-linux-x86_64
  before_script:
  - set -eu
  - yum install -y bsdtar
  - yum install -y rdfind
  - !reference [.omni_s3_write_get_secrets, omni_s3_write_get_secrets]
  script:
  - ./repo.sh ci build -c debug

# ==============================================================================================================
build-windows-x86_64-release:
  extends:
  - .build-common
  - .runner-build-windows-x86_64
  before_script:
  - !reference [.windows_packman_s3_creds_get_powershell, windows_packman_s3_creds_get_powershell]
  script:
  - ./repo.bat ci build -c release

# ==============================================================================================================
build-windows-x86_64-debug:
  extends:
  - .build-common
  - .runner-build-windows-x86_64
  before_script:
  - !reference [.windows_packman_s3_creds_get_powershell, windows_packman_s3_creds_get_powershell]
  script:
  - ./repo.bat ci build -c debug



# ==============================================================================================================
.test-artifacts:
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
    - _build/**/*.log
    - _build/**/debug/*.xml
    - _build/**/release/*.xml
    - _build/coverage.info
    - _build/coverage/**
    - _repo/repo.log
    - _repo/repolog*.txt
    - _build/**/_testoutput/
    reports:
      junit:
      - _build/**/debug/*.xml
      - _build/**/release/*.xml
      - _build/**/_testoutput/results.xml


# ==============================================================================================================
.test-common:
  stage: test
  timeout: 3 hour
  interruptible: true
  extends:
  - .test-artifacts
  allow_failure: true
  rules:
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - !reference [.rules-workflow, rules]

.test-linux-common:
  after_script:
  - !reference [.datadog-test-visibility-linux-x86_64, script]
  - ./repo.sh ci test -- --generate-report
  needs:
  - job: build-linux-x86_64-release
    artifacts: true

.test-windows-common:
  after_script:
  - !reference [.datadog-test-visibility-windows-x86_64, script]
  - ./repo.bat ci test -- --generate-report
  needs:
  - job: build-windows-x86_64-release
    artifacts: true

# ==============================================================================================================
test-linux-x86_64-startuptests:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s startuptests

test-linux-x86_64-pythontests-1:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 1

test-linux-x86_64-pythontests-2:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 2

test-linux-x86_64-pythontests-3:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 3

test-linux-x86_64-pythontests-4:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 4

test-linux-x86_64-pythontests-5:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 5

test-linux-x86_64-pythontests-6:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 6

test-linux-x86_64-pythontests-7:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 7

test-linux-x86_64-pythontests-8:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 8

test-linux-x86_64-pythontests-9:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s pythontests -b 9

test-linux-x86_64-selectortests:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s selectortests

test-linux-x86_64-warmuptests:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s warmuptests

test-linux-x86_64-postinstalltests:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s postinstalltests


test-linux-x86_64-nativepythontests-1:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s nativepythontests -b 1 --generate-report
  after_script:
  - !reference [.datadog-test-visibility-linux-x86_64, script]

test-linux-x86_64-nativepythontests-2:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s nativepythontests -b 2 --generate-report
  after_script:
  - !reference [.datadog-test-visibility-linux-x86_64, script]

test-linux-x86_64-internalnativepythontests:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s internalnativepythontests --generate-report
  rules:
  - !reference [.rules-nightly-tests, rules]
  after_script:
  - !reference [.datadog-test-visibility-linux-x86_64, script]


test-linux-x86_64-benchmarks:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - export ISAAC_TEST_MODE=1
  - ./repo.sh ci test -- -s benchmarks --generate-report
  rules:
  - !reference [.rules-nightly-tests, rules]
  after_script:
  - !reference [.datadog-test-visibility-linux-x86_64, script]


test-linux-x86_64-internalpythontests-1:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s internalpythontests -b 1
  rules:
  - !reference [.rules-nightly-tests, rules]

test-linux-x86_64-internalpythontests-2:
  extends:
  - .test-common
  - .test-linux-common
  - .install-linux-test-packages
  - .runner-test-linux-x86_64-gpu
  - .omni_nvks_gpu
  script:
  - ./repo.sh ci test -- -s internalpythontests -b 2
  rules:
  - !reference [.rules-nightly-tests, rules]

test-windows-x86_64-startuptests:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s startuptests

test-windows-x86_64-pythontests-1:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 1

test-windows-x86_64-pythontests-2:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 2

test-windows-x86_64-pythontests-3:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 3

test-windows-x86_64-pythontests-4:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 4

test-windows-x86_64-pythontests-5:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 5

test-windows-x86_64-pythontests-6:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 6

test-windows-x86_64-pythontests-7:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 7

test-windows-x86_64-pythontests-8:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 8

test-windows-x86_64-pythontests-9:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s pythontests -b 9

test-windows-x86_64-selectortests:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s selectortests

test-windows-x86_64-warmuptests:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s warmuptests

test-windows-x86_64-postinstalltests:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s postinstalltests

test-windows-x86_64-internalpythontests-1:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s internalpythontests -b 1
  rules:
  - !reference [.rules-nightly-tests, rules]

test-windows-x86_64-internalpythontests-2:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s internalpythontests -b 2
  rules:
  - !reference [.rules-nightly-tests, rules]

test-windows-x86_64-nativepythontests-1:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s nativepythontests -b 1 --generate-report
  rules:
  - !reference [.rules-nightly-tests, rules] #only run linux ones per MR and these nightly

test-windows-x86_64-nativepythontests-2:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s nativepythontests -b 2 --generate-report
  rules:
  - !reference [.rules-nightly-tests, rules] #only run linux ones per MR and these nightly

test-windows-x86_64-internalnativepython:
  extends:
  - .test-common
  - .test-windows-common
  - .runner-test-windows-x86_64-gpu
  script:
  - ./repo.bat ci test -- -s internalnativepython --generate-report
  rules:
  - !reference [.rules-nightly-tests, rules]


# ==============================================================================================================
.deploy-artifacts:
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
    - _build/**/*.log
    - _repo/repo.log
    - _repo/repolog*.txt
    - _logs/**/*.log


# ==============================================================================================================
.deploy-common:
  stage: deploy
  extends:
  - .deploy-artifacts
  timeout: 3 hour
  interruptible: false
  before_script:
  - set -eu
  - !reference [.omni_codesign_get_secrets, omni_codesign_get_secrets]
  - !reference [.omni_s3_write_get_secrets, omni_s3_write_get_secrets]
  rules:
  - if: $RUN_DOCS_BUILD == "true" || RUN_NIGHTLY_TESTS=="true"
    when: never

pages:
  stage: pages
  extends:
  - .build-common
  - .runner-build-linux-x86_64
  before_script:
  - set -eu
  - yum install -y p7zip p7zip-plugins
  script:
  - mkdir .public
  - ls
  - mv omni-docs/_build/docs/* .public/
  - ls .public
  - 7z x _build/packages/docs@*.7z -oisaacsim
  - mkdir -p .public/py/
  - mv isaacsim .public/py/
  - ls .public/py/isaacsim
  - mv .public public
  artifacts:
    paths:
    - public
  rules:
  - !reference [.rules-build-docs, rules]
  needs:
  - job: build-linux-x86_64-release
    artifacts: true
  - job: build-docs
    artifacts: true

build-docs:
  extends:
  - .build-common
  - .runner-build-linux-x86_64
  timeout: 3 hours
  before_script:
  - set -eu
  - yum install -y bsdtar
  - !reference [.omni_s3_write_get_secrets, omni_s3_write_get_secrets]
  script:
  - git clone --depth=1 -b isaac_sim --single-branch https://gitlab-master.nvidia.com/omniverse/omni-docs.git
  - pushd omni-docs
  - ./repo docs --warn-as-error=0
  - ./repo docs --stage sphinx
  - ./repo docs --stage post
  - popd
  rules:
  - !reference [.rules-build-docs, rules]
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
    - omni-docs/_build/docs


# ==============================================================================================================
.benchmark-artifacts:
  artifacts:
    when: always
    expire_in: 2 weeks
    paths:
    - '_testoutput/benchmark.*.json'
    - .reggie-out/

# ==============================================================================================================
.benchmark-common:
  stage: test
  timeout: 1 hour
  interruptible: true
  extends:
  - .benchmark-artifacts
  variables:
    MAX_RETRIES: 2
  retry: 2
  rules:
  - if: $RUN_EXTENSION_BENCHMARKS != "true"
    when: never
  - !reference [.rules-workflow, rules]


# ==============================================================================================================
benchmark-linux-x86_64:
  extends:
  - .benchmark-common
  tags:
  - instance/gitlab-gtl-performance
  - omni-perf-only/linux
  variables:
    MACHINE_OS: "ubuntu22"
    MACHINE_KIND: "AMD EPYC 7313P"
    MACHINE_DRIVER: "NVIDIA-Linux-x86_64-525.85.05"
  script:
  - ./repo.sh bench
  - !reference [.reggie_detect_ubuntu, commands]
  needs:
  - job: build-linux-x86_64-release
    artifacts: true


# ==============================================================================================================
benchmark-windows-x86_64:
  extends:
  - .benchmark-common
  tags:
  - instance/gitlab-gtl-performance
  - omni-perf-only/windows
  variables:
    MACHINE_OS: "windows10-20H2"
    MACHINE_KIND: "AMD EPYC 7313P"
    MACHINE_DRIVER: "537.70-sandbag_UDA_QuadroWeb_Public-wddm2-x64-dch-AttestedDriverSigning"
  script:
  - ./repo.bat bench
  - !reference [.reggie_detect_windows, commands]
  needs:
  - job: build-windows-x86_64-release
    artifacts: true



# autoupdate-kit:
#   rules:
#    - when: never

# include:
#   - project: 'omniverse/sectools/omni-pulse'
#     file: '/templates/nspect-pulse-scan.yml'
#     # ref: main

# nspect:
#   extends: .nspect-scan
#   stage: test
#   tags: ['os/linux', 'type/docker']
#   # allow_failure: true
#   variables:
#     PULSE_NSPECT_ID: "NSPECT-8CX1-LP1G"
#     PULSE_SCAN_PROJECT: "Omniverse Isaac Sim"
#     PULSE_SCAN_PROJECT_VERSION: "${CI_COMMIT_REF_SLUG}"

#     OMNI_PULSE_TOOL_ARGS: "
#     --target-deps-platforms linux-x86_64 windows-x86_64 \
#     --target-deps-paths \
#         deps/kit-sdk.packman.xml \
#         deps/rtx-plugins.packman.xml \
#         deps/target-deps.packman.xml \
#         deps/isaac-sim.packman.xml \
#     --additional-sources-path \
#         source \
#     --override-branches master develop 'release/*'' \
#         "
#   script:
#     - set e
#     # WAR for omni.pulse not knowing how to magically create <import path="../_build/${platform}/${config}/kit/dev/deps/rtx-target-deps.packman.xml.user">
#     - tools/packman/packman pull deps/kit-sdk.packman.xml --platform linux-x86_64 -t config=release
#     - tools/packman/packman pull deps/rtx-plugins.packman.xml --platform linux-x86_64 -t config=release
#     - tools/packman/packman pull deps/omni-physics.packman.xml --platform linux-x86_64 -t config=release
#     # - tools/packman/packman pull deps/target-deps.packman.xml --platform linux-x86_64 -t config=release
#     # - tools/packman/packman pull deps/isaac-sim.packman.xml --platform linux-x86_64 -t config=release
#     - tools/packman/packman pull deps/kit-sdk.packman.xml --platform windows-x86_64 -t config=release
#     - tools/packman/packman pull deps/rtx-plugins.packman.xml --platform windows-x86_64 -t config=release
#     - tools/packman/packman pull deps/omni-physics.packman.xml --platform windows-x86_64 -t config=release
#     # - tools/packman/packman pull deps/target-deps.packman.xml --platform windows-x86_64 -t config=release
#     # - tools/packman/packman pull deps/isaac-sim.packman.xml --platform windows-x86_64 -t config=release
#     - !reference ['.nspect-scan', 'script']
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       when: manual
#     - if: '$CI_PIPELINE_SOURCE == "schedule"'
#       when: always
#     # the default branch has a scheduled scanner, disable per-commit automatic scan
#     - if: '$CI_COMMIT_BRANCH == "develop"'
#       when: manual
#     - if: '$CI_COMMIT_BRANCH == "master"'
#       when: manual
#     # we probably don't have a scheduled scan setup for each release branch (though we should),
#     # scan per-commit to catch some updates
#     - if: $CI_COMMIT_REF_NAME =~ /^release\/.*$/
#       when: always
#     - when: never


# ==============================================================================================================
# By default, all platforms (windows-x86_64, linux-x86_64) are published,
# but this can be changed in repo.toml config if necessary:
#    [repo_publish_exts]
#    platforms = ["linux-x86_64"]
verify-publish-extensions:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ./repo.sh build --fetch-only -rd
  - ./repo.sh publish_exts -a --from-package -c release --verify
  - ./repo.sh publish_exts -a --from-package -c debug --verify
  # - ./repo.sh ci publish_extensions
  needs:
  # We set all dependencies as optional just in case a platform is not needed,
  # then the yml file can override both build/test on one platform and deploy will still work.
  - job: build-windows-x86_64-release
    artifacts: true
    optional: false
  - job: build-linux-x86_64-release
    artifacts: true
    optional: false
  - job: build-windows-x86_64-debug
    artifacts: true
    optional: false
  - job: build-linux-x86_64-debug
    artifacts: true
    optional: false
  #   - job: test-windows-x86_64-startuptests
  #     artifacts: false
  #     optional: true
  #   - job: test-linux-x86_64-startuptests
  #     artifacts: false
  #     optional: true
  rules:
  - if: $ALLOW_PUBLISH_EXTENSIONS != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true"
    when: never
  - !reference [.rules-push, rules]
  # - !reference [.rules-version-changed, rules]


# ==============================================================================================================
# By default, all platforms (windows-x86_64, linux-x86_64) are published,
# but this can be changed in repo.toml config if necessary:
#    [repo_publish_exts]
#    platforms = ["linux-x86_64"]
publish-extensions:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ./repo.sh build --fetch-only -rd
  - ./repo.sh publish_exts -a --from-package -c release
  - ./repo.sh publish_exts -a --from-package -c debug
  needs:
  # We set all dependencies as optional just in case a platform is not needed,
  # then the yml file can override both build/test on one platform and deploy will still work.
  - job: sign-windows-x86_64-release
    artifacts: true
    optional: false
  - job: build-linux-x86_64-release
    artifacts: true
    optional: false
  - job: build-windows-x86_64-debug
    artifacts: true
    optional: false
  - job: build-linux-x86_64-debug
    artifacts: true
    optional: false
  rules:
  - if: $ALLOW_PUBLISH_EXTENSIONS != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]


# ==============================================================================================================
.publish-python-packages-deploy-common:
  stage: deploy
  extends:
  - .deploy-artifacts
  timeout: 3 hour
  interruptible: false
  rules:
  - if: $RUN_DOCS_BUILD == "true" || RUN_NIGHTLY_TESTS=="true"
    when: never

publish-python-packages-linux:
  extends:
  - .publish-python-packages-deploy-common
  - .runner-build-linux-x86_64
  script:
  - ./repo.sh unzip_file --file _build/packages/isaac-sim-standalone*.linux-x86_64.release.7z --dst _build/linux-x86_64/release
  - ls _build/linux-x86_64/release
  - ./repo.sh python_package --create
  - ./repo.sh comment_archive_deps
  - ./repo.sh python_package --wheel
  - ls _build/packages/dist
  - ./repo.sh python_package --publish
  needs:
  - job: build-linux-x86_64-release
    artifacts: true
  rules:
  - if: $ALLOW_PUBLISH_PYTHON_PACKAGES != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]

publish-python-packages-windows:
  extends:
  - .publish-python-packages-deploy-common
  - .runner-build-windows-x86_64
  script:
  - ./repo.bat unzip_file --file _build/packages/isaac-sim-standalone*.windows-x86_64.release.7z --dst _build/windows-x86_64/release
  - ls _build/windows-x86_64/release
  - ./repo.bat python_package --create
  - ./repo.bat comment_archive_deps
  - ./repo.bat python_package --wheel
  - ls _build/packages/dist
  - ./repo.bat python_package --publish
  needs:
  - job: sign-windows-x86_64-release
    artifacts: true
  rules:
  - if: $ALLOW_PUBLISH_PYTHON_PACKAGES != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]


# ==============================================================================================================
publish-docs:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  variables:
    # Required access tokens for publishing to S3
    AWS_ACCESS_KEY_ID: $AWS_OMNIVERSEDOCS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_OMNIVERSEDOCS_SECRET_ACCESS_KEY
  needs:
  - job: build-windows-x86_64-release
    artifacts: true
  script:
  - ./repo.sh ci publish_docs
  rules:
  - if: $ALLOW_PUBLISH_DOCS != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]


# ==============================================================================================================
publish-to-launcher:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ls _build/packages/
  - ./repo.sh publish_launcher
  needs:
  - job: sign-windows-x86_64-release
    artifacts: true
  - job: build-linux-x86_64-release
    artifacts: true
  #   - job: test-windows-x86_64-startuptests
  #     artifacts: false
  #     optional: true
  #   - job: test-linux-x86_64-startuptests
  #     artifacts: false
  #     optional: true
  retry:
    max: 2
    when:
    - always
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true

#   extends:
#   - .deploy-common
#   - .omni_nvks_runner_with_docker
#   script:
#   - ./repo.sh ci publish_to_launcher
#   needs:
#   - job: build-windows-x86_64-release
#     artifacts: true
#   - job: build-linux-x86_64-release
#     artifacts: true
#   rules:
#   - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
#     when: never
#   - !reference [.rules-push-manual, rules]
#   allow_failure: true


# ==============================================================================================================
release-new-version:
  rules:
  - when: never

#   extends:
#   - .deploy-common
#   - .omni_nvks_runner_with_docker
#   needs: []
#   script:
#   - ./repo.sh ci release_new_version
#   rules:
#   - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
#     when: never
#   - !reference [.rules-push-manual, rules]
#   allow_failure: true


# ==============================================================================================================
# update Kit SDK and extensions, merge master, typically done in daily branch
# set AUTOUPDATE_KIT=true for scheduled pipeline to run
autoupdate-kit:
  rules:
  - when: never
#   extends:
#   - .deploy-common
#   - .omni_nvks_runner_with_docker
#   needs: []
#   script:
#   - ./repo.sh ci autoupdate_kit
#   rules:
#   - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
#     when: never
#   - if: $AUTOUPDATE_KIT == "true" && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule")
#     when: always


# ==============================================================================================================
bump-version:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ./repo.sh bump_version
  needs: []
  rules:
  - if: $RUN_BUMP_VERSION != "true"
    when: never
  - !reference [.rules-bump-version, rules]


# ==============================================================================================================
sign-windows-x86_64-release:
  timeout: 3 hour
  extends:
  - .build-common
  - .runner-build-windows-x86_64
  before_script:
  - !reference [.repo_codesign_get_secrets_windows_powershell, repo_codesign_get_secrets_windows_powershell]
  - !reference [.windows_packman_s3_creds_get_powershell, windows_packman_s3_creds_get_powershell]
  script:
  - ls _build/packages/
  - mkdir _unsignedpackages
  - mkdir _signedpackages
  - mv -Force _build/packages/*windows-x86_64.release.7z _unsignedpackages/
  - ./repo.bat codesign
  - mv -Force _signedpackages/*windows-x86_64.release.7z _build/packages/
  - ls _build/packages/
  needs:
  - job: build-windows-x86_64-release
    artifacts: true
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
internal-build-linux-x86_64-release:
  extends:
  - .build-common
  - .runner-build-linux-x86_64
  before_script:
  - set -eu
  - yum install -y bsdtar
  - !reference [.omni_s3_write_get_secrets, omni_s3_write_get_secrets]
  script:
  - ./repo.sh build -r --no-docker
  - ./repo.sh package -m isaac-sim-internal-standalone -c release
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - if: '$CI_COMMIT_BRANCH != "develop"'
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
internal-build-windows-x86_64-release:
  extends:
  - .build-common
  - .runner-build-windows-x86_64
  before_script:
  - !reference [.windows_packman_s3_creds_get_powershell, windows_packman_s3_creds_get_powershell]
  script:
  - ./repo.bat build -r
  - ./repo.bat package -m isaac-sim-internal-standalone -c release
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - if: '$CI_COMMIT_BRANCH != "develop"'
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
internal-publish-to-packman:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ls _build/packages/
  - ./repo.sh publish_internal_packages
  needs:
  - job: internal-build-linux-x86_64-release
    artifacts: true
  - job: internal-build-windows-x86_64-release
    artifacts: true
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - if: '$CI_COMMIT_BRANCH != "develop"'
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
internal-publish-container:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  variables:
    APP_NAME: "isaac-sim-internal"
    FAMILY_NAME: "gl"
  before_script:
  - docker version
  - docker login -u sabdulajees -p ${gitlab_registry_push} gitlab-master.nvidia.com:5005
  - docker login -u \$oauthtoken -p $NGC_TOKEN nvcr.io
  - docker login nvcr.io
  script:
  - ./tools/container/publish_container.sh
  needs:
  - job: internal-build-linux-x86_64-release
    artifacts: true
  retry:
    max: 2
    when:
    - always
  rules:
  - if: $ALLOW_PUBLISH_CONTAINERS != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - if: '$CI_COMMIT_BRANCH != "develop"'
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
publish-container:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  variables:
    APP_NAME: "isaac-sim"
    FAMILY_NAME: "gl"
  before_script:
  - docker version
  - docker login -u sabdulajees -p ${gitlab_registry_push} gitlab-master.nvidia.com:5005
  - docker login -u \$oauthtoken -p $NGC_TOKEN nvcr.io
  - docker login nvcr.io
  script:
  - ./tools/container/publish_container.sh
  needs:
  - job: build-linux-x86_64-release
    artifacts: true
  retry:
    max: 2
    when:
    - always
  rules:
  - if: $ALLOW_PUBLISH_CONTAINERS != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true



# ==============================================================================================================
binaryscan-build-linux-x86_64-release:
  extends:
  - .build-common
  - .runner-build-linux-x86_64
  before_script:
  - set -eu
  - yum install -y bsdtar
  - !reference [.omni_s3_write_get_secrets, omni_s3_write_get_secrets]
  script:
  - ./repo.sh build -r --no-docker
  - ./repo.sh package -m isaac-sim-binaryscan -c release
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
binaryscan-build-windows-x86_64-release:
  extends:
  - .build-common
  - .runner-build-windows-x86_64
  before_script:
  - !reference [.windows_packman_s3_creds_get_powershell, windows_packman_s3_creds_get_powershell]
  script:
  - ./repo.bat build -r
  - ./repo.bat package -m isaac-sim-binaryscan -c release
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
binaryscan-publish-to-packman:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ls _build/packages/
  - ./repo.sh publish_binaryscan_packages
  needs:
  - job: binaryscan-build-linux-x86_64-release
    artifacts: true
  - job: binaryscan-build-windows-x86_64-release
    artifacts: true
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
isaac-sim-assets-1:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ./tools/ci/build-and-packaging/isaac-sim-assets-1/step.sh
  - ./repo.sh publish_assets_launcher_1
  needs: []
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "gitlab-ci")
    when: manual
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
isaac-sim-assets-2:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ./tools/ci/build-and-packaging/isaac-sim-assets-2/step.sh
  - ./repo.sh publish_assets_launcher_2
  needs: []
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "gitlab-ci")
    when: manual
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true


# ==============================================================================================================
isaac-sim-assets-3:
  extends:
  - .deploy-common
  - .omni_nvks_runner_with_docker
  script:
  - ./tools/ci/build-and-packaging/isaac-sim-assets-3/step.sh
  - ./repo.sh publish_assets_launcher_3
  needs: []
  rules:
  - if: $ALLOW_PUBLISH_TO_LAUNCHER != "true"
    when: never
  - if: $RUN_BUMP_VERSION == "true" || $RUN_DOCS_BUILD == "true"
    when: never
  - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "gitlab-ci")
    when: manual
  - !reference [.rules-version-changed, rules]
  - !reference [.rules-push-manual, rules]
  allow_failure: true
