pages:
  tags: 
    - pages
  image:
    alpine:latest
  script:
    - apk add --no-cache p7zip wget curl
    - mkdir .public
    - echo "10.36.168.30 teamcity.nvidia.com" >> /etc/hosts
    - echo "24.51.7.209 swiftstack-maglev.ngc.nvidia.com" >> /etc/hosts
    - 'curl -L --output docs.7z --header "Authorization: Bearer $TC_TOKEN" https://teamcity.nvidia.com/repository/download/Omniverse_IsaacSim_Develop_BuildAndPackaging_OmniDocsBuildLinuxX8664/.lastSuccessful/omniverse-robotics-docs%40%7Bbuild.number%7D.7z'
    - 'curl -L --output pydocs.zip --header "Authorization: Bearer $TC_TOKEN" https://teamcity.nvidia.com/repository/download/Omniverse_IsaacSim_Develop_BuildAndValidation/.lastSuccessful/artifacts/Linux/docs%40%7Bbuild.number%7D.linux-x86_64.zip'
    - 7z x docs.7z -o.public
    - 7z x pydocs.zip -oisaacsim
    - mkdir -p .public/py/
    - mv isaacsim .public/py/
    - ls .public/py/isaacsim
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - develop@Isaac/omni_isaac_sim

stages:
  - test

# include:
#   - project: 'omniverse/sectools/omni-pulse'
#     file: '/templates/nspect-pulse-scan.yml'
#     # ref: main

# nspect:
#   extends: .nspect-scan
#   stage: test
#   tags: ['os/linux', 'type/docker']
#   # allow_failure: true
#   variables:
#     PULSE_NSPECT_ID: "NSPECT-8CX1-LP1G"
#     PULSE_SCAN_PROJECT: "Omniverse Isaac Sim"
#     PULSE_SCAN_PROJECT_VERSION: "${CI_COMMIT_REF_SLUG}"

#     OMNI_PULSE_TOOL_ARGS: "
#     --target-deps-platforms linux-x86_64 windows-x86_64 \
#     --target-deps-paths \
#         deps/kit-sdk.packman.xml \
#         deps/rtx-plugins.packman.xml \
#         deps/target-deps.packman.xml \
#         deps/isaac-sim.packman.xml \
#     --additional-sources-path \
#         source \
#     --override-branches master develop 'release/*'' \
#         "
#   script:
#     - set e
#     # WAR for omni.pulse not knowing how to magically create <import path="../_build/${platform}/${config}/kit/dev/deps/rtx-target-deps.packman.xml.user">
#     - tools/packman/packman pull deps/kit-sdk.packman.xml --platform linux-x86_64 -t config=release
#     - tools/packman/packman pull deps/rtx-plugins.packman.xml --platform linux-x86_64 -t config=release
#     - tools/packman/packman pull deps/omni-physics.packman.xml --platform linux-x86_64 -t config=release
#     # - tools/packman/packman pull deps/target-deps.packman.xml --platform linux-x86_64 -t config=release
#     # - tools/packman/packman pull deps/isaac-sim.packman.xml --platform linux-x86_64 -t config=release
#     - tools/packman/packman pull deps/kit-sdk.packman.xml --platform windows-x86_64 -t config=release
#     - tools/packman/packman pull deps/rtx-plugins.packman.xml --platform windows-x86_64 -t config=release
#     - tools/packman/packman pull deps/omni-physics.packman.xml --platform windows-x86_64 -t config=release
#     # - tools/packman/packman pull deps/target-deps.packman.xml --platform windows-x86_64 -t config=release
#     # - tools/packman/packman pull deps/isaac-sim.packman.xml --platform windows-x86_64 -t config=release
#     - !reference ['.nspect-scan', 'script']
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       when: manual
#     - if: '$CI_PIPELINE_SOURCE == "schedule"'
#       when: always
#     # the default branch has a scheduled scanner, disable per-commit automatic scan
#     - if: '$CI_COMMIT_BRANCH == "develop"'
#       when: manual
#     - if: '$CI_COMMIT_BRANCH == "master"'
#       when: manual
#     # we probably don't have a scheduled scan setup for each release branch (though we should),
#     # scan per-commit to catch some updates
#     - if: $CI_COMMIT_REF_NAME =~ /^release\/.*$/
#       when: always
#     - when: never
