# Stylua configuration file
# See https://github.com/JohnnyMorganz/StyLua for more information

# Column width (default: 120)
column_width = 120

# Line endings (options: Unix, Windows)
line_endings = "Unix"

# Indent type (options: Tabs, Spaces)
indent_type = "Spaces"

# Indent width
indent_width = 4

# Quote style (options: AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle)
quote_style = "AutoPreferDouble"

# Call parentheses (options: Always, NoSingleString, NoSingleTable, None)
call_parentheses = "NoSingleTable"

# Collapse simple statement (default: true)
collapse_simple_statement = "Always"

# Sort requires (default: false)
[sort_requires]
enabled = true