########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]
logging = "info"


########################################################################################################################
# Build tool setup
########################################################################################################################

[repo_build]

# List of packman projects to pull (in order)
fetch.packman_host_files_to_pull = [
    "${root}/deps/host-deps.packman.xml",
]

fetch.packman_target_files_to_pull = [
    "${root}/deps/kit-sdk.packman.xml",
    "${root}/deps/rtx-plugins.packman.xml",
    "${root}/deps/omni-physics.packman.xml",
    "${root}/deps/target-deps.packman.xml",
    "${root}/deps/isaac-sim.packman.xml",
]

# List of pip files to pip install from (in order)
fetch.pip_files_to_pull = [
    "${root}/deps/pip.toml"
]

fetch.enable_exclude_configs_tags = false


stage_files.extra_mapping.kit_sdk_debug = "${root}/_build/kit_debug"
stage_files.extra_mapping.kit_sdk_release = "${root}/_build/kit_release"

# This allows us to write to files outside of _build
stage_files.allowed_paths=[]

vscode.python = "${root}/_build/kit_debug/_build/target-deps/python"

vscode.python_env.PYTHONPATH= [
  "$$$${PYTHONPATH}",
  "${env:PYTHONPATH}",
  "$root/_build/pip-packages",
  "$repo_deps/repo_man",
  "$repo_deps/repo_build",
  "$repo_deps/repo_fileutils",
  "$repo_deps/repo_format",
  "$repo_deps/repo_package",
  "$root/tools/repoman",
  "$root/_build/$platform/$config/extensions",
  "$root/_build/$platform/$config/exts",
  "$root/_build/$platform/$config/bindings-python",
  "$root/_build/$platform/$config/exts/*",
  "$root/_build/kit_$config/_exts/*/",
  "$root/_build/kit_$config/_build/$platform/$config/extsPhysics/*/",
  "$root/_build/kit_$config/_build/$platform/$config/extensions/extensions-bundled",
  "$root/_build/kit_$config/_build/$platform/$config/plugins/bindings-python",
]

vscode.python_env.PATH= ["$$$${PATH}", "$root/_build/$platform/$config",
  "$root/_build/kit_$config/_build/$platform/$config",
  "$root/_build/kit_$config/_build/$platform/$config/plugins",
  "$root/_build/kit_$config/_build/$platform/$config/plugins/carb_gfx",
  "$root/_build/kit_$config/_build/$platform/$config/plugins/rtx",
  "$root/_build/kit_$config/_build/$platform/$config/libs/mdl",
  "$root/_build/kit_$config/_build/$platform/$config/libs/iray",
  "$root/_build/kit_$config/_exts/*/bin",
  "$root/_build/kit_$config/_build/$platform/$config/extsPhysics/*/bin",
  "$root/_build/kit_$config/_build/$platform/$config/extensions/extensions-bundled/bin",
  "$root/_build/kit_$config/_build/$platform/$config/plugins/bindings-python/bin",
  # "$root/_build/$platform/$config/exts/omni.isaac.*/bin",
]
# These paths are used by python samples
vscode.python_env.CARB_APP_PATH= ["$root/_build/kit_$config/_build/$platform/$config"]
vscode.python_env.ISAAC_PATH= ["$root/_build/$platform/$config"]
# TODO
# vscode.python_env.PXR_PLUGINPATH_NAME= ["$root/_build/"]


msbuild.sln_file = "isaac-sim.sln"
msbuild.vs_version = "vs2017"

stage_files.error_if_missing = true

licensing.enabled = true
#licensing.packages = ["${root}/deps/rtx-target-deps.packman.xml", "${root}/deps/target-deps.packman.xml", "${root}/deps/isaac-sim.packman.xml"]
licensing.packages = ["${root}/deps/rtx-target-deps.packman.xml", "${root}/deps/target-deps.packman.xml"]
licensing.fail_on_missing = false


########################################################################################################################
# Documentation building
########################################################################################################################

[repo_build_docs]
enabled = true

# Use python from kit sdk
python_path =  "${root}/_build/kit_${config}/_build/${platform}/${config}/python${shell_ext}"

# differentiate debug/release docs
enable_build_config_choice = true

# Add all extensions to docs sys.path
extra_sys_paths = [
    "${root}/_build/${platform}/${config}/exts/*"
]

########################################################################################################################
# Build Number 
########################################################################################################################

[repo_build_number]
enabled = true


########################################################################################################################
# Packaging 
########################################################################################################################

[repo_package]

[repo_package.packages.isaac_sim]
omniverse_flow_version_scheme = true
ziponly = false
package_per_config = true
"platform:linux-x86_64".archive_format = "7z" # Use 7z on linux

[repo_package.packages.isaac_sim-launcher]
omniverse_flow_version_scheme = true
ziponly = false
"platform:linux-x86_64".archive_format = "7z" # Use 7z on linux
package_per_config = true
append_config = true
replace_authors_in_kit_extensions = true
strip_package_infos = true
windows_max_path_length = 220 #TODO: changed from default of 180 to make builds pass

# to generate test runner package for isaac sim
[repo_package.packages.test_runner]
omniverse_flow_version_scheme = true
ziponly = true

# to generate laucnher images package
[repo_package.packages.isaac_sim-pipeline-images-dl]
omniverse_flow_version_scheme = true
archive_format = "zip"
strip_package_infos = true

[repo_package.packages.isaac_sim-pipeline-images-rc]
omniverse_flow_version_scheme = true
archive_format = "zip"
strip_package_infos = true

[repo_package.packages.isaac_sim-pipeline-images-prod]
omniverse_flow_version_scheme = true
archive_format = "zip"
strip_package_infos = true

########################################################################################################################
# Package publishing to packman
########################################################################################################################

[repo_publish]
enabled = true
packages = ["isaac_sim*"]

########################################################################################################################
# Launcher publish and deploy
########################################################################################################################

[deploy_launcher]
git_url = "https://oauth2:${env:ISAAC_SIM_PIPELINE_TOKEN}@gitlab-master.nvidia.com/omniverse/isaac_sim-release-pipeline.git"
template_path = "${root}/tools/repoman/launcher-pipeline-template"

########################################################################################################################
# Test Runner
########################################################################################################################
[repo_test]

# When running from package, look for package using that path/pattern:
archive_pattern = "${root}/_build/packages/isaac_sim-*.7z"

[repo_test.suites.pythontests]
kind = "glob_and_exec"
path = "${test_root}/_build/${platform}/${config}"
  [[repo_test.suites.pythontests.group]]
  include = ["tests-*${shell_ext}"]
  exclude =[]
  args = []
  tc_report_enabled = false
  timeout = 240


# Catch2 Unit Tests
[repo_test.suites.unittests]
kind = "catch2"
default = true
executables = [
	"${test_root}/_build/${platform}/${config}/test.unit.range_sensor${exe_ext}",
]
