# This repo has custom test_runner tool for repoman. To run tests.
[test_runner]
command = "test"
entry_point = "${config_root}/tools/repoman/test_runner.py:setup_repo_tool"

########################################################################################################################
# Kit Update & Commit Tool
########################################################################################################################

[repo_stubgen]
command = "kit_autoupdate"
entry_point = "${config_root}/tools/repoman/kit_autoupdate.py:setup_repo_tool"


########################################################################################################################
# Omniverse Launcher package publish and deploy tool
########################################################################################################################

[deploy_launcher]
command = "deploy_launcher"
entry_point = "${config_root}/tools/repoman/deploy_launcher.py:setup_repo_tool"