########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]
logging = "warn"
extra_tool_paths = [
	"${root}/_build/$platform/release/kit/dev"
]


########################################################################################################################
# Override VERSION File
########################################################################################################################

[repo.folders]
version_file = "${root}/VERSION"


########################################################################################################################
# Build tool setup
########################################################################################################################

[repo_build]

# List of packman projects to pull (in order)
fetch.packman_host_files_to_pull = [
    "${root}/deps/host-deps.packman.xml",
]

fetch.packman_target_files_to_pull = [
    "${root}/deps/kit-sdk.packman.xml",
    "${root}/deps/rtx-plugins.packman.xml",
    "${root}/deps/omni-physics.packman.xml",
    "${root}/deps/target-deps.packman.xml",
    "${root}/deps/isaac-sim.packman.xml",
]

stage_files.extra_mapping.kit_sdk_debug = "${root}/_build/$platform/debug/kit"
stage_files.extra_mapping.kit_sdk_release = "${root}/_build/$platform/release/kit"

vscode.python = "${root}/_build/$platform/release/kit/python"

vscode.python_env.PYTHONPATH= [
  "$$$${PYTHONPATH}",
  "${env:PYTHONPATH}",
  "$root/_build/pip-packages",
  "$repo_deps/repo_man",
  "$repo_deps/repo_build",
  "$repo_deps/repo_fileutils",
  "$repo_deps/repo_format",
  "$repo_deps/repo_package",
  "$root/tools/repoman",
  "$root/_build/$platform/$config/exts/*",
  "$root/_build/$platform/$config/kit/exts/*",
  "$root/_build/$platform/$config/kit/extscore/*",
  "$root/_build/$platform/$config/kit/extensions/extensions-bundled",
  "$root/_build/$platform/$config/kit/plugins/bindings-python/",
  "$root/_build/$platform/$config/kit/extscore/omni.kit.pip_archive/pip_prebundle",
]

vscode.python_env.PATH= [
  "$$$${PATH}", 
  "$root/_build/$platform/$config",
  "$root/_build/$platform/$config/exts/omni.usd.schema.isaac/bin",
  "$root/_build/$platform/$config/kit",
  "$root/_build/$platform/$config/kit/exts/*/bin",
  "$root/_build/$platform/$config/kit/extscore/*/bin",
  "$root/_build/$platform/$config/kit/extsPhysics/*/bin",
  "$root/_build/$platform/$config/kit/libs/iray",
  "$root/_build/$platform/$config/kit/plugins",
  "$root/_build/$platform/$config/kit/plugins/bindings-python",
  "$root/_build/$platform/$config/kit/plugins/carb_gfx",
  "$root/_build/$platform/$config/kit/plugins/rtx",
  "$root/_build/$platform/$config/kit/extensions/extensions-bundled/bin",

]
# These paths are used by python samples
vscode.python_env.CARB_APP_PATH= ["$root/_build/${platform}/${config}/kit"]
vscode.python_env.ISAAC_PATH= ["$root/_build/$platform/$config"]

vscode.write_python_paths_in_settings_json = true
vscode.generate_python_env_file = false

msbuild.sln_file = "isaac-sim.sln"
msbuild.vs_version = "vs2017"

stage_files.error_if_missing = true

licensing.enabled = true
licensing.packages = ["${root}/deps/rtx-target-deps.packman.xml", "${root}/deps/target-deps.packman.xml"]
licensing.fail_on_missing = true

post_build.commands = [
    ["${root}/repo${shell_ext}", "precache_exts", "-c", "${config}"],
    ["${root}/tools/build_docs${shell_ext}", "--config", "${config}", "--warn-as-error", "0"] 
]


########################################################################################################################
# Extensions precacher
########################################################################################################################

[repo_precache_exts]
enabled = true

# Extra args to pass to kit
kit_extra_args = []

# Folder to store cache extensions into
cache_path = "${root}/_build/${platform}/${config}/exts"

ext_folders = [
  "${root}/_build/$platform/$config/exts"
]

# Apps to run and precache
apps = [
    "${root}/_build/$platform/$config/apps/omni.isaac.sim.extscache.kit"
]

# Registries to use
registries = [
    { name = "kit/default", url = "omniverse://kit-extensions.ov.nvidia.com/exts/kit/default" },
]


########################################################################################################################
# Documentation building
########################################################################################################################

[repo_docs]

enabled = true

# the name of you project.  should be a single word. used to name files.
project = "isaac_sim"

# a slightly more descriptive name for your project. user visible. keep it short.
long_name = "Isaac Sim"

# first year in your projects copyright.
copyright_start = 2018

# Use python from kit sdk
python_path =  "${root}/_build/${platform}/${config}/python${shell_ext}"

# Move api docs to build directory
# docs_dst = "${root}/_build/${platform}/${config}/docs"

# Add all extensions to docs sys.path
extra_sys_paths = []

sphinx_conf_py_extra = """
    add_module_names = False
    html_logo = "docs/media/main_ov_logo_square.png"
    html_favicon = "docs/media/favicon.ico"
    html_static_path = [
        "docs/media/isaac-style.css",
        "docs/media/NVIDIA-LogoBlack.svg",
    ]
    html_css_files = [ "isaac-style.css" ]
"""

sphinx_exclude_patterns = [
    "**/omni.isaac.app",
    "**/omni.isaac.app.launcher",
    "**/omni.isaac.app.setup",
    "**/omni.isaac.decals",
    "**/omni.isaac.exploded_view",
    "**/omni.isaac.internal_tools",
    "**/omni.isaac.robot_engine_bridge",     #TODO
    "**/omni.isaac.robot_engine_bridge_gxf",     #TODO
    "**/omni.isaac.samples",     #TODO?
    "**/omni.isaac.samples_internal",
    "**/omni.isaac.shapenet",     #TODO?
    "**/omni.isaac.splash",
    "**/omni.isaac.step_importer",     #TODO?
    "**/omni.isaac.tests",
    "**/omni.isaac.utils_manager",
    "**/omni.kit.property.isaac",
    "**/omni.usd.schema.isaac",     #TODO?
    "**/omni.isaac.window.about",
    "include",
    "tools",
    "tests",
    "**/README.md",
    "TESTING.md",
    "**/CHANGELOG.md",
    "CHANGELOG.md",
    "**/*LICENSE.md",
    ".cache"
]

########################################################################################################################
# Build Number 
########################################################################################################################

[repo_build_number]
enabled = true


########################################################################################################################
# Packaging 
########################################################################################################################

[repo_package.packages.isaac-sim]
root = "_build/$${platform}/$${config}"
omniverse_flow_version_scheme = true
ziponly = false
package_per_config = true
"platform:linux-x86_64".archive_format = "7z" # Use 7z on linux

[repo_package.packages.isaac-sim-standalone]
root = "_build/$${platform}/$${config}"
omniverse_flow_version_scheme = true
ziponly = false
"platform:linux-x86_64".archive_format = "7z" # Use 7z on linux
package_per_config = true
append_config = true
replace_authors_in_kit_extensions = true
strip_package_infos = true
windows_max_path_length = 220 #TODO: changed from default of 180 to make builds pass

# to generate test runner package for isaac sim
[repo_package.packages.test_runner]
omniverse_flow_version_scheme = true
ziponly = true

# to generate launcher images package
[repo_package.packages.isaac-sim-pipeline-images-beta]
omniverse_flow_version_scheme = true
archive_format = "zip"
strip_package_infos = true

[repo_package.packages.isaac-sim-pipeline-images-rc]
omniverse_flow_version_scheme = true
archive_format = "zip"
strip_package_infos = true

# to generate docs package for isaac sim
[repo_package.packages.docs]
omniverse_flow_version_scheme = true
ziponly = true


########################################################################################################################
# Package publishing to packman
########################################################################################################################

[repo_publish]
enabled = true
packages = ["isaac-sim*"]

########################################################################################################################
# Launcher publish and deploy
########################################################################################################################

[publish_launcher]
git_url = "https://oauth2:${env:ISAAC_SIM_PIPELINE_TOKEN}@gitlab-master.nvidia.com/omniverse/isaac_sim-release-pipeline.git"
template_path = "${root}/tools/repoman/launcher-pipeline-template/beta"
branch_prefix = "integ"

########################################################################################################################
# Test Runner
########################################################################################################################
[repo_test]

test_root = "$root/_build/$platform/$config"

# When running from package, look for package using that path/pattern:
archive_pattern = "${root}/_build/packages/isaac-sim-*.7z"

[repo_test.suites.pythontests]
kind = "glob_and_exec"
path = "${test_root}"
  [[repo_test.suites.pythontests.group]]
  include = ["tests-*${shell_ext}"]
  exclude =[]
  args = ["--portable-root ${test_root}/portable_root"]
  tc_report_enabled = false
  timeout = 480


# Catch2 Unit Tests
[repo_test.suites.unittests]
kind = "catch2"
default = true
executables = [
	"${test_root}/tests-unit-omni.isaac.range_sensor${exe_ext}",
]

########################################################################################################################
# Bump version
########################################################################################################################

[bump_version]
git_url = "https://oauth2:${env:ISAAC_SIM_PIPELINE_TOKEN}@gitlab-master.nvidia.com/Isaac/omni_isaac_sim.git"
branch_name = "develop"


########################################################################################################################
# Extensions publisher
########################################################################################################################

[repo_publish_exts]
enabled = true

kit_path = "${root}/_build/$platform/$config/kit/kit${exe_ext}"

publish_root = "${root}/_build/$platform/$config"

ext_folders = [
  "${publish_root}/exts"
]

# Extensions to publish, include and exclude among those discovered by kit. Wildcards are supported.
exts.include = [
    "omni.isaac.contact_sensor",
    "omni.isaac.dr",
    "omni.isaac.dynamic_control",
    "omni.isaac.manip",
    "omni.isaac.motion_planning",
    "omni.isaac.occupancy_map",
    "omni.isaac.onshape",
    "omni.isaac.range_sensor",
    "omni.isaac.samples",
    "omni.isaac.synthetic_utils",
    "omni.isaac.urdf",
    "omni.isaac.utils",
    "omni.usd.schema.isaac"
]
exts.exclude = []

# Registries to publish to.
registries = [
    { name = "kit/default", url = "omniverse://kit-extensions.ov.nvidia.com/exts/kit/default" },
]

# verify before publishing
publish_verification = true

# When running from package, look for package using that path/pattern:
archive_pattern = "${root}/_build/packages/isaac-sim-*.7z"

# ETM (extension test matrix) settings
enroll_in_etm = false
etm_emails = []