########################################################################################################################
# Omniverse Launcher package publish and deploy tool
########################################################################################################################

[publish_launcher]
command = "publish_launcher"
entry_point = "${config_root}/tools/repoman/publish_launcher.py:setup_repo_tool"


########################################################################################################################
# Omniverse Launcher Images package publish and deploy tool
########################################################################################################################

[publish_launcher_images]
command = "publish_launcher_images"
entry_point = "${config_root}/tools/repoman/publish_launcher_images.py:setup_repo_tool"


########################################################################################################################
# Isaac Sim package publish tool
########################################################################################################################

[publish_packages]
command = "publish_packages"
entry_point = "${config_root}/tools/repoman/publish_packages.py:setup_repo_tool"


########################################################################################################################
# Bump version
########################################################################################################################

[bump_version]
command = "bump_version"
entry_point = "${config_root}/tools/repoman/bump_version.py:setup_repo_tool"


########################################################################################################################
# Publish Isaac Sim assets on Launcher
########################################################################################################################

[publish_assets_launcher]
command = "publish_assets_launcher"
entry_point = "${config_root}/tools/repoman/publish_assets_launcher.py:setup_repo_tool"

########################################################################################################################
# Generate Omnigraph Docs
########################################################################################################################

[omnigraph_docs]
command = "omnigraph_docs"
entry_point = "${config_root}/tools/ogn/ogn_docs_generator.py:setup_repo_tool"

[generate_vscode_settings]
command = "generate_vscode_settings"
entry_point = "${config_root}/tools/isaac/generate_vscode_settings.py:setup_repo_tool"