[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "Isaac Sim Physics Utilities"
description = "Collision and Physics Utils"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.physics_utilities"
keywords = ["isaac", "physics", "utils",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.util.physics" = {}

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.util.physics."

[[python.module]]
name = "omni.isaac.physics_utilities"
