[package]
version = "1.2.1"
category = "Internal"
title = "Isaac Sim DocTest"
description = "Provides test case base classes for validating Python docstring examples using Python's doctest module in both standalone and async execution contexts."
authors = ["hmazhar@nvidia.com", "aserranomuno@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.test.docstring"
keywords = ["isaac", "test", "doctest", "docstrings"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"omni.kit.test" = {}

[[python.module]]
name = "isaacsim.test.docstring"
