# lula is a custom dependency that is compiled and brought in from packman for omni.isaac.lula
[[dependency]]
python = "../_build/target-deps/python"
packages = [
    "requests==2.31.0",        # SWIPAT filed under: https://nvbugs/3430668
    "pint==0.20.1",            # SWIPAT filed under: https://nvbugs/3433818
    "packaging==23.0",         # SWIPAT filed under: https://nvbugs/3433815
    "oauthlib==3.2.2",         # SWIPAT filed under: https://nvbugs/3433846
    "requests-oauthlib==1.3.1",# SWIPAT filed under: https://nvbugs/3433849
    "ruamel.yaml==0.17.32",    # SWIPAT filed under: https://nvbugs/4221806
    "ruamel.yaml.clib==0.2.7", # SWIPAT filed under: https://nvbugs/4221809
    "nulltype==2.3.1",         # SWIPAT filed under: https://nvbugs/4221818
]
target = "../_build/target-deps/isaac_onshape_prebundle"
platforms = ["*-x86_64"]
download_only = false
install_dependencies = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
# extra_args = []
