[[dependency]]
python = "../_build/target-deps/python"
packages = [
    "imageio==2.22.2",          # SWIPAT filed under: https://nvbugs/3701046
    "scipy==1.10.1",            # SWIPAT filed under: https://nvbugs/3673519
    "pyyaml==6.0.1",            # SWIPAT filed under: https://nvbugs/3434739
]

target = "../_build/target-deps/pip_compute_prebundle"
platforms = ["*-x86_64"]
download_only = false
install_dependencies = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
# extra_args = []
