display_name = "STEP Importer"

[dependencies]
"omni.kit.editor" = {}

[[python.modules]]
name = "omni.isaac.step_importer"

[[native.plugins]]
search_path = "bin/${platform}/${config}/*.plugin"
recursive = false

