display_name = "Kaya Preview Sample"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.utils" = {}
"omni.isaac.manip" = {}

[[python.modules]]
name = "omni.isaac.samples.kaya_preview"
public = false
