[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
title = "Isaac Sim Proximity Sensor Example"
description = "Proximity Sensor"

[dependencies]
"omni.physx" = {}

[[python.module]]
name = "omni.isaac.proximity_sensor"
