display_name = "Isaac UR10 Robot"

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.kit" = {}
"omni.isaac.motion_generation" = {}
"omni.isaac.surface_gripper" = {}

[[python.module]]
name = "omni.isaac.ur10"

