[package]
title = "Isaac Sim App Selector"
description = "Mini Launch Pad app for Isaac Sim Sub Apps"
version = "2.1.0"
toggleable = false

[dependencies]
"omni.kit.pip_archive" = {} # pulls in pyperclip

[[python.module]]
name = "omni.isaac.app.selector"