[core]
reloadable = true
order = 0

[package]
version = "1.1.2"
category = "Simulation"
title = "Ros2 Robot Description URDF Importer"
description = "This extensions expands the URDF Importer by enabling importing the robot description from a given ROS node"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.ros2.urdf"
keywords = ["isaac", "ROS2", "URDF"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.asset.importer.urdf" = {}
"omni.kit.pip_archive" = {} # import the base kit python archive
"omni.kit.viewport.utility"= {}
"omni.kit.viewport.window"= {}
"isaacsim.ros2.bridge" = {}
"omni.ui" = {}


[[python.module]]
name = "isaacsim.ros2.urdf"

[[test]]
stdoutFailPatterns.exclude = [
    '*[Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.*', # feature not included in Windows
]

