[core]
reloadable = true
order = 0

[package]
version = "1.0.4"
category = "Simulation"
title = "Isaac Cortex Sample Behaviors"
description = "Sample Behaviors for Isaac Cortex"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.cortex.sample_behaviors"
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.cortex" = {}

[[python.module]]
name = "omni.isaac.cortex.sample_behaviors"
