[core]
reloadable = true
order = 0

[package]
version = "0.1.10"
category = "Simulation"
title = "Isaac Sim Samples"
description = "Sample extensions for Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.samples"
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.vehicle" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.motion_planning" = {}
"omni.isaac.utils" = {}
"omni.isaac.manip" = {}
"omni.isaac.synthetic_utils" = {}
"omni.isaac.dr" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.isaac.franka" = {}
"omni.isaac.jetbot" = {}
"omni.isaac.kaya" = {}
"omni.isaac.motion_generation" = {}
"omni.isaac.demos" = {}

[[python.module]]
name = "omni.isaac.samples.tests"

[[python.module]]
name = "omni.isaac.samples.scripts.dynamic_control.joint_controller"

[[python.module]]
name = "omni.isaac.samples.scripts.dynamic_control.read_articulations"

[[python.module]]
name = "omni.isaac.samples.scripts.kaya_joystick"

[[python.module]]
name = "omni.isaac.samples.scripts.jetbot_keyboard"

[[python.module]]
name = "omni.isaac.samples.scripts.navigation_preview"

[[python.module]]
name = "omni.isaac.samples.scripts.rmp_sample"

[[python.module]]
name = "omni.isaac.samples.scripts.replay_sample"

[[python.module]]
name = "omni.isaac.samples.scripts.ros_samples"

[[python.module]]
name = "omni.isaac.samples.scripts.ros_moveit_sample"

[[python.module]]
name = "omni.isaac.samples.scripts.simple_stack"

[[python.module]]
name = "omni.isaac.samples.scripts.follow_target"

[[python.module]]
name = "omni.isaac.samples.scripts.surface_gripper"

[[test]]
timeout = 960
