display_name = "Isaac Sim Utilities Manager"

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Simulation"
title = "Isaac Sim Utilities Manager"
description = "Useful Tools for Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.utils_manager"
keywords = ["isaac", "utils"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.physx" = {}
"omni.usdphysics" = {}
"omni.debugdraw" = {}

# Isaac Sim Utilities
"omni.isaac.robot_engine_bridge" = {}
"omni.isaac.samples" = {}
"omni.isaac.step_importer" = {}
"omni.isaac.synthetic_utils" = {}
"omni.isaac.urdf" = {}
"omni.isaac.utils" = {}

[[python.module]]
name = "omni.isaac.utils_manager"
