display_name = "ROS Bridge"

[dependencies]
"omni.kit.editor" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.syntheticdata" = {}
"omni.isaac.utils" = {}

[[python.module]]
name = "omni.isaac.ros_bridge"

[[python.module]]
name = "omni.isaac.ros_bridge.scripts.samples.rostopics"

[[python.module]]
name = "omni.isaac.ros_bridge.scripts.samples.rosservices"

[[native.plugins]]
path = "bin/*.plugin"
recursive = false

[[python.module]]
name = "omni.isaac.RosBridgeSchema"
public = false


[[libraries]]
path = "bin/${lib_prefix}rosBridgeSchema${lib_ext}"
