display_name = "ROS Bridge"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.syntheticdata" = {}
"omni.isaac.utils" = {}
"omni.usd.schema.isaac" = {}

[[python.module]]
name = "omni.isaac.ros_bridge"

[[python.module]]
name = "omni.isaac.ros_bridge.tests"
public = false

[[python.module]]
name = "omni.isaac.ros_bridge.scripts.samples.rostopics"

[[python.module]]
name = "omni.isaac.ros_bridge.scripts.samples.rosservices"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false