[package]
version = "1.0.5"
category = "Utility"
title = "TF Viewer"
description = "Show the tf transform tree in the viewport"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.tf_viewer"
keywords = ["isaac", "ROS2", "tf"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.ros2.tf_viewer."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.ros2.tf_viewer" = {}

[[python.module]]
name = "omni.isaac.tf_viewer.tests"

[[test]]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
dependencies = [
    "omni.isaac.core",
    "omni.isaac.nucleus",
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
