[core]
reloadable = true
order = 0

[package]
version = "2.0.2"
category = "Simulation"
title = "Generate Extension"
description = "UI tool for generating extension templates for different common workflows"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.extension_templates"
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"


[dependencies]
"isaacsim.examples.extension" = {}
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "omni.isaac.extension_templates"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.examples.extension."