[core]
reloadable = false
order = 0

[package]
version = "2.0.3"
category = "Simulation"
title = "Isaac Sim Kit Helpers"
description = "This Extension that provides a way to launch a python app"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.simulation_app"
keywords = ["isaac", "kit", "python"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true
toggleable = false

[dependencies]
"omni.usd" = {}

[[python.module]]
name = "isaacsim.simulation_app"
