display_name = "Isaac Utilities"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}

[[python.modules]]
name = "omni.isaac.utils"

[[python.modules]]
name = "omni.isaac.utils.scripts.prim_rel_editor"
public = false

[[python.modules]]
name = "omni.isaac.utils.scripts.semantics_ui"
public = false