display_name = "Isaac Utilities"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.synthetic_utils" = {}
"omni.syntheticdata" = {}

[[python.modules]]
name = "omni.isaac.utils"

[[python.modules]]
name = "omni.isaac.utils.scripts.prim_rel_editor"
public = false

[[python.modules]]
name = "omni.isaac.utils.scripts.semantics_ui"
public = false

[[python.modules]]
name = "omni.isaac.utils.scripts.visualize_syntheticdata"
public = false

[[python.modules]]
name = "omni.isaac.utils.scripts.syntheticdata_recorder"
public = false

[[python.modules]]
name = "omni.isaac.utils.scripts.physics_inspector"

[[python.modules]]
name = "omni.isaac.utils.scripts.samples.surface_gripper"

[[python.modules]]
name = "omni.isaac.utils.scripts.merge_mesh_tool"
public = false