display_name = "STEP Importer"

[dependencies]
"omni.kit.editor" = {}
"omni.kit.tool.asset_importer" = {}
"omni.kit.window.content_browser" = {order = 1} # order = 1 is a hack to prevent the extension from crashing if it loads too soon
"omni.kit.window.filepicker" = {}

[[python.module]]
name = "omni.isaac.step_importer"

[[native.plugins]]
path = "bin/*.plugin"
recursive = false

[python.pipapi]
requirements = ["numpy", "psutil"]