display_name = "STEP Importer"

[dependencies]
"omni.kit.editor" = {}
"omni.kit.tool.asset_importer" = {}
"omni.isaac.utils" = {}

[[python.modules]]
name = "omni.isaac.step_importer"

[[native.plugins]]
path = "bin/*.plugin"
recursive = false

[python.pipapi]
requirements = ["numpy", "psutil"]