display_name = "ROS Bridge"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}

[[python.modules]]
name = "omni.isaac.ros_bridge"

[[native.plugins]]
search_path = "bin/${platform}/${config}/*.plugin"
recursive = false
