display_name = "Range Sensor"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {} 
"omni.debugdraw" = {}

[[python.modules]]
name = "omni.isaac.range_sensor"


[[python.modules]]
name = "omni.isaac.range_sensor.scripts.samples.lidar_info"

[[python.modules]]
name = "omni.isaac.RangeSensorSchema"
public = false

[[native.plugins]]
path = "bin/*.plugin"
recursive = false

[[libraries]]
path = "bin/${lib_prefix}rangeSensorSchema${lib_ext}"

[python.pipapi]
requirements = ["numpy"]