[package]
version = "1.0.4"
category = "SyntheticData"
title = "Isaac Sim Replicator Writers"
description = "The extension provides various custom Replicator based writers for Synthetic Data Generation (SDG) workflows. The writers are registered with Replicator at extension startup."
authors = ["hmazhar@nvidia.com", "ahaidu@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.replicator.writers"
keywords = ["Synthetic", "Data", "Generation", "SDG", "Writers"]
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.platform = true # Build separate extensions for Windows and Linux so appropriate libraries are bundled

[dependencies]
"isaacsim.core.api" = {}
"omni.graph" = {}
"omni.graph.core" = {}
"omni.isaac.ml_archive" = {} # torch
"omni.replicator.core" = {}

[[python.module]]
name = "isaacsim.replicator.writers"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[test]]
dependencies = [
]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]