# Copyright (c) 2020-2024, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto. Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#

import argparse
import glob
import logging
import os
import shutil
from typing import Callable, Dict

import omni.repo.man

logger = logging.getLogger(os.path.basename(__file__))


def collect_ogn_docs(home_dir, build_dir, ext_name):
    omni.repo.man.print_log(f"Collecting ogn docs: {ext_name}", logging.INFO)
    # copy ogn docs
    dst_dir = os.path.join(home_dir, ext_name, "docs", "ogn")
    src_dir = os.path.join(build_dir, ext_name, "ogn", "docs")
    doc_files = glob.glob(os.path.join(src_dir, "*.rst"))
    if doc_files:
        shutil.copytree(src_dir, dst_dir, dirs_exist_ok=True)


def update_index(home_dir, ext_name):
    doc_files = glob.glob(os.path.join(home_dir, ext_name, "docs", "ogn", "*.rst"))
    if not doc_files:
        omni.repo.man.print_log(f"  |-- Skipping extension: no .rst files found", logging.WARN)
        return
    index_file = os.path.join(home_dir, ext_name, "docs", "index.rst")
    # create index.rst if it doesn't exist
    if not os.path.isfile(index_file):
        omni.repo.man.print_log(f"  |-- Creating {index_file}", logging.INFO)
        open(index_file, "a").close()
    with open(index_file, "r") as file:
        lines = file.readlines()
    # find placeholders
    begin = None
    begin_placeholder = "   [begin ogn autogenerated]"
    if f"{begin_placeholder}" in lines:
        begin = lines.index(f"{begin_placeholder}") + 1
    if f"{begin_placeholder}\n" in lines:
        begin = lines.index(f"{begin_placeholder}\n") + 1
    end = None
    end_placeholder = "   [end ogn autogenerated]"
    if f"{end_placeholder}" in lines:
        end = lines.index(f"{end_placeholder}") - 1
    if f"{end_placeholder}\n" in lines:
        end = lines.index(f"{end_placeholder}\n") - 1
    if begin is None or end is None:
        omni.repo.man.print_log(f"  |-- Wrong placeholder format: {index_file}", logging.WARN)
        return
    omni.repo.man.print_log(f"  |-- Updating index.rst", logging.INFO)
    # generate content
    content = [
        f".. _ext_{ext_name.replace('.', '_')}:\n\n",
        "Omnigraph Nodes\n",
        "===============\n\n",
        ".. toctree::\n",
        "    :glob:\n",
        "    :maxdepth: 1\n\n",
        "    ogn/*\n",
    ]
    # write content
    with open(index_file, "w") as file:
        file.writelines(lines[:begin] + content + lines[end:])


def setup_repo_tool(parser: argparse.ArgumentParser, config: Dict) -> Callable:
    parser.description = """
Generate OmniGraph documentations.

Target extensions should include the docs/index.rst file with at least the following placeholder
(content between ---) in order to make the OmniGraph documentation discoverable by repo_docs.
Use the argument `--update-index` to generate the content inside the placeholder.

----------------------------
..
   [begin ogn autogenerated]
..
   [end ogn autogenerated]
----------------------------
"""
    parser.formatter_class = argparse.RawTextHelpFormatter
    parser.add_argument(
        "--update-index",
        required=False,
        default=False,
        action="store_true",
        help="Whether to regenerate the OmniGraph node section in extensions' docs/index.rst",
    )

    def run_repo_tool(options: Dict, config: Dict):
        # get repo config
        ogn_config = config["repo_ogn"]
        home_dir = ogn_config["home_path"]
        build_dir = ogn_config["build_path"]
        ogn_exts = ogn_config["ogn_exts_includes"]

        for ext in ogn_exts:
            collect_ogn_docs(home_dir, build_dir, ext)
            if options.update_index:
                update_index(home_dir, ext)

    return run_repo_tool
