name = "Isaac Sim Daily"
#displayed application name in smaller card and library view
shortName = "Isaac Sim Daily"
version = "${version}"
#boolean for if this version is the latest version
latest = true
#unique identifier for component, all lower case, persists between versions
slug = "isaac_sim-daily"

#displayed before application name in launcher
productArea = "Omniverse"
#category of content
category = "Daily"
#values for filtering content, not implemented yet
tags = [
  "Autonomous Machines",
  "Robotics",
  "Manufacturing",
  "Product Design", 
  "Scene Composition", 
  "Visualization", 
  "Rendering"
]

#enum of "app", "connector" and "experience" for now
kind = "app"
#string array, each line is a new line, keep lines under 256 char and keep lines under 4
description = [
 "DAILY BUILD !!, use the Stable Build for Production Work.",
 "NVIDIA Omniverse™ Isaac Sim is built on NVIDIA Omniverse simulation platform, it leverages Omniverse Kit and has been enhanced with robotics specific extensions. Isaac Sim provides the essential features for building virtual robotic worlds and experiments. Isaac Sim supports navigation and manipulation applications through Isaac SDK and ROS, with RGB-D, Lidar and IMU sensors, Domain Randomization, ground truth labeling, segmentation, and bounding boxes."
]

#array of links for more info on product

[[links]]
title = "Release Notes"
url = "https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/release_notes.html"
[[links]]
title = "Documentation"
url = "https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/overview.html"
[[links]]
title = "Tutorials"
url = "https://www.nvidia.com/en-us/on-demand/search/?facet.mimetype[]=event%20session&page=1&q=isaac%20sim&sort=date"
[[links]]
title = "Forums"
url = "https://forums.developer.nvidia.com/c/agx-autonomous-machines/isaac/simulation/69"