[package]
version = "3.0.2"
category = "Simulation"
title = "Gain Tuner"
description = "Gain Tuner for Articulation PD Gains"
authors = ["hmazhar@nvidia.com", "qwan@nvidia.com", "rgasoto@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.robot_setup.gain_tuner"
keywords = ["isaac", "physics", "analyze", "tune"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.core.experimental.prims" = {}
"isaacsim.core.deprecation_manager" = {}
"isaacsim.gui.components" = {}
"isaacsim.robot.schema" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "isaacsim.robot_setup.gain_tuner"
