[core]
reloadable = true
order = 0

[package]
version = "2.0.2"
category = "Other"
title = "Isaac Sim Throlling"
description = "Control throttling behaviors for isaac sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.core.throttling"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.window.preferences" = {}

[[python.module]]
name = "isaacsim.core.throttling"

[[python.module]]
name = "isaacsim.core.throttling.tests"

[[test]]
args = ["--/rtx/ecoMode/enabled = True"]
dependencies = ["omni.kit.test", "omni.timeline"]