name = "Create Daily"
#displayed application name in smaller card and library view
shortName = "Create Daily"
version = "${version}"
#boolean for if this version is the latest version
latest = true
#unique identifier for component, all lower case, persists between versions
slug = "create-daily"

#displayed before application name in launcher
productArea = "Omniverse"
#category of content
category = "Daily"
#values for filtering content, not implemented yet
tags = [
  "Media & Entertainment",
  "Manufacturing",
  "Product Design", 
  "Scene Composition", 
  "Visualization", 
  "Rendering"
]

#enum of "app", "connector" and "experience" for now
kind = "app"
#string array, each line is a new line, keep lines under 256 char and keep lines under 4
description = [
 "DAILY BUILD !!, use the Stable Build for Production Work.",
 "Omniverse Create is an application built on Omniverse Kit that accelerates advanced scene composition and allows users to interactively assemble, light, simulate, and render scenes in Pixar USD in real-time. Create lets you easily navigate, modify, and render Pixar USD content in a live, synchronous environment. ",
 "FEATURES:",
 "- Simplify Scene Composition: Create offers advanced layout tools to build worlds with ease. Translate existing assets you own or fill from Create’s libraries of assets, including trees, furniture, roads, and people. With Omniverse Connectors, designers can also import landscapes from industry-leading tools like Unreal Engine or Houdini.",
 "- Breathtaking Photorealism: Create includes NVIDIA RTX™ Renderer—an advanced, multi-GPU enabled that lets you visualize stunning, photoreal scenes at the speed of light. Coupled with NVIDIA vMaterials based on MDL, scenes are realistic, interactive visualizations that are true to reality. For high-speed playback and authoring, Create also includes real-time ray tracing mode powered by RTX.",
 "- Make it Move: Create supports animation from tools like Maya, Unreal, 3ds Max, and supports features like animation clips, skeletal animation, animation caches, and blend shapes. In Create, you can either play back these animations in real time or render into movies.",
 "- Recreate Reality: Create includes advanced simulation capabilities, including direct integration of PhysX, Blast, and Flow for realistic physics, destruction, fire, and smoke simulation. You can also use tools like Houdini to export USD animations and effects that can be brought into Create and rendered.",
 "- Share it Anywhere: Once your visualization is created in Omniverse Create, you can export your simulation as an MP4, sequential images, or an interactive standalone playback with the app’s Movie Maker tool. As an experimental feature, CloudXR is also supported on tablets for augmented reality experiences."
]

#array of links for more info on product

[[links]]
title = "Release Notes"
url = "https://gitlab-master.nvidia.com/omniverse/ov-create/-/blob/daily/CHANGELOG.md"
[[links]]
title = "Documentation"
url = "https://docs.omniverse.nvidia.com/app_create/app_create/overview.html"
[[links]]
title = "Tutorials"
url = "https://www.nvidia.com/en-us/on-demand/search/?facet.event_name[]=Omniverse%20Tutorials&facet.mimetype[]=event%20session&headerText=All%20Sessions&page=1&q=-&sort=date"
[[links]]
title = "Forums"
url = "https://forums.developer.nvidia.com/c/omniverse/300"