omni.replicator.character:
  version: 0.1.0
  global:
    seed: 123456
    camera_num: 5
    lidar_num: 0
    simulation_length: 10
  scene:
    asset_path:
  character:
    asset_path:
    command_file:
    filters:
    num: 5
  robot:
    command_file:
    num: 0
    write_data: false
  replicator:
    writer: TaoWriter
    parameters:
      output_dir:
      rgb: True
      bbox: True
      semantic_segmentation: False
      video: False
