[package]
version = "1.0.5"
category = "Other"
title = "Isaac Sim Import Wizard [alpha]"
description = "wizard to guide users through importing and configuration tools inside isaac sim"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.import_wizard"
keywords = ["isaac","wizard","import"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.robot_setup.import_wizard."

[dependencies]
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "omni.isaac.import_wizard"

[[python.module]]
name = "omni.isaac.import_wizard.tests"
