display_name = "Dynamic Control"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}
"omni.isaac.utils" = {}

[[python.modules]]
name = "omni.isaac.dynamic_control"

[[native.plugins]]
search_path = "bin/${platform}/${config}/*.plugin"
recursive = false

