[package]
title = "Isaac Sim App Launcher"
description = "Create a Launch Pad app for Isaac Sim Sub Apps"
version = "1.0.0"
toggleable = false

[dependencies]
"omni.kit.pip_archive" = {} # pulls in pyperclip

[[python.module]]
name = "omni.isaac.app.launcher"