[core]
reloadable = true
order = 0


[package]
version = "2.0.0"
category = "Simulation"
title = "Isaac Sim Surface Gripper"
description = "Helper to model Suction and Distance based grippers"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/isaacsim.robot.surface_gripper"
keywords = ["isaac", "physics", "end-effector",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true


[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.ros2.bridge" = {}

[[python.module]]
name = "omni.isaac.ros2_bridge.robot_description"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.ros2.bridge."
