# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#



[package]
version = "1.0.0"
category = "other"
title = "Isaac Sim OpenXR support"
description = "Additional APIs for integrating Isaac Sim and OpenXR for robotics"
authors = ["hmazhar@nvidia.com", "rwiltz@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.xr.openxr"
keywords = ["isaac", "xr", "openxr"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 5.0.0. Replaced by omni.kit.xr handtracking"

[dependencies]
"omni.kit.xr.profile.ar" = {}
"omni.kit.xr.system.openxr" = {}

[[python.module]]
name = "isaacsim.xr.openxr"

# define the C++ plugins that the extension provides
[[native.plugin]]
path = "bin/*.plugin"
recursive = false

# [settings]
# exts."isaacsim.xr.openxr".timeout = 5