[package]
title = "Isaac Sim Splash"
description = "Show up a splash Screen while Isaac Sim is Loading"
version = "1.0.0"

[dependencies]
"omni.kit.editor" = { tag="mini" }

[[python.module]]
name = "omni.isaac.splash"
