display_name = "Occupancy Map"

[dependencies]
"omni.kit.editor" = {}
"omni.kit.test" = {}
"omni.physx" = {} 
"omni.debugdraw" = {}

[[python.modules]]
name = "omni.isaac.occupancy_map"

[[native.plugins]]
path = "bin/*.plugin"
recursive = false

