[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Simulation"
title = "Isaac Sim Occupancy Map"
description = "2D Occupancy Map Generation"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.occupancy_map"
keywords = ["isaac", "occupancy map"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.editor" = {}
"omni.physx.core" = {} 
"omni.debugdraw" = {}

[[python.module]]
name = "omni.isaac.occupancy_map"

[[native.plugins]]
path = "bin/*.plugin"
recursive = false

