display_name = "Isaac UR10 Robot"

[package]
version = "0.2.2"

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.motion_generation" = {}
"omni.isaac.surface_gripper" = {}

[[python.module]]
name = "omni.isaac.universal_robots"

