[package]
version = "1.0.5"
category = "Internal"
title = "Isaac Sim DocTest"
description = "Test interactive Python docstrings examples"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.doctest"
keywords = ["isaac", "test", "doctest", "docstrings"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.test.docstring."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.test.docstring" = {}

[[python.module]]
name = "omni.isaac.doctest"

[[python.module]]
name = "omni.isaac.doctest.tests"