[package]
version = "1.0.1"
category = "Simulation"
title = "Isaac Sim Conveyor belt utility"
description="Omnigraph Node for Defining the behavior of a linear conveyor belt"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.asset.conveyor"

keywords = ["kit", "example"]



[dependencies]
"isaacsim.core.deprecation_manager" = {}
"omni.physx"={}
"omni.graph" = {}
"omni.graph.core" = {}
"omni.graph.action" = {}
"omni.graph.nodes" = {}
"omni.usd" = {}

# Main module for the Python interface
[[python.module]]
name = "isaacsim.asset.conveyor"

[[python.module]]
name = "isaacsim.asset.conveyor.tests"


[[native.plugin]]
path = "bin/*.plugin"
recursive = false

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[test]]
dependencies=[
"omni.physx.stageupdate",
"usdrt.scenegraph",
"omni.timeline",
]

stdoutFailPatterns.exclude = [
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_isaacsim_asset_conveyor_IsaacConveyor: [/TestGraph] no prim path found for the conveyor*",
    "*[Error] [carb.glinterop.plugin] GLInteropContext::init: carb::windowing is not available*",
]
    