display_name = "Leonardo Preview Sample"

[dependencies]
"omni.kit.editor" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.motion_planning" = {}
"omni.isaac.utils" = {}

[[python.modules]]
name = "omni.isaac.samples.leonardo_preview"
public = false