[core]
reloadable = true
order = 0

[package]
version = "2.1.2"
category = "Simulation"
title = "Isaac Sim Range Sensor UI components"
description = "UI components for the Range Sensor extension"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.sensors.physx.ui"
keywords = ["isaac", "physics", "sensor", "lidar", "ui"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"omni.kit.uiapp" = {}
"omni.kit.menu.utils" = {}
"isaacsim.robot.schema" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}
"isaacsim.sensors.physx" = {}
"omni.kit.context_menu" = {}

[[python.module]]
name = "isaacsim.sensors.physx.ui"
