[package]
version = "2.2.4"
category = "Simulation"
title = "Isaac Sim PhysX Sensor UI components"
description = "Isaac Sim PhysX Sensor UI components extension provides UI components for Isaac Sim PhysX-raycast-based sensor simulation, eg. menu options."
authors = ["hmazhar@nvidia.com", "adevalla@nvidia.com", "stevfeng@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.sensors.physx.ui"
keywords = ["isaac", "physics", "sensor", "lidar", "ui"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.core.deprecation_manager" = {}
"isaacsim.gui.components" = {}
"isaacsim.robot.schema" = {}
"isaacsim.sensors.physx" = {}
"omni.kit.context_menu" = {}
"omni.kit.menu.utils" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "isaacsim.sensors.physx.ui"

[[test]]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]