[package]
version = "2.2.15"
category = "Simulation"
title = "Isaac Sim Utilities"
description = "The Core Utils extension provides useful utilities for USD, physics, math, rendering and carb."
authors = ["hmazhar@nvidia.com", "aserranomuno@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.core.utils"
keywords = ["isaac", "utils"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true
writeTarget.platform = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.storage.native" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.ml_archive" = {}
"omni.physx" = {}
"omni.usd.schema.semantics" = {}
"omni.usdphysics" = {}
"omni.warp.core" = {}

[[python.module]]
name = "isaacsim.core.utils"

[[python.module]]
name = "isaacsim.core.utils.tests"

[[test]]
dependencies = [
    "isaacsim.core.api",
    "isaacsim.sensors.camera",
    "omni.replicator.core",
]

args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
    '--/persistent/isaac/asset_root/default = "omniverse://isaac-dev.ov.nvidia.com"',
    '--/persistent/simulation/defaultMetersPerUnit = 1.0',
    '--/persistent/app/stage/upAxis = "Z"'
]