[package]
version = "1.0.5"
category = "Simulation"
title = "Isaac Franka Robot"
description = "Isaac Franka Robot Helper Class"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.franka"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.robot.manipulators.examples"

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot.manipulators.examples" = {}

[[python.module]]
name = "omni.isaac.franka"

[[test]]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
