[core]
reloadable = true
order = 0

[package]
version = "2.1.2"
category = "Simulation"
title = "Wheeled Robots UI"
description = "This extension provides the UI elements for the wheeled_robots extension"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.robot.wheeled_robots"
keywords = ["isaac", "physics", "analyze", "tune", "ui"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"omni.graph" = {}
"omni.graph.tools" = {}
"isaacsim.robot.wheeled_robots" = {}
"isaacsim.core.deprecation_manager" = {}


[[python.module]]
name = "isaacsim.robot.wheeled_robots.ui"