[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Isaac Sim Team"]

# The title and description fields are primarily for displaying extension info in UI
title = "Kit Provide Feedback Window"
description=""

# URL of the extension source repository.
repository="https://gitlab-master.nvidia.com/omniverse/kit"

# One of categories for UI.
category = "Internal"

# Keywords for the extension
keywords = ["kit"]

# https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

[dependencies]
"omni.kit.editor" = { optional=true }

[[python.module]]
name = "omni.isaac.window.provide_feedback"


# Extension test settings
[test]
dependencies = [
    "omni.kit.editor-mini",
]
