[core]
reloadable = true
order = 0

[package]
version = "1.1.0"
category = "Simulation"
title = "Isaac Sim Menus"
description = "Isaac Sim Utility Extensions"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.gui.menu"
keywords = ["isaac", "menu"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"omni.kit.menu.utils" = {}
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}

[[python.module]]
name = "isaacsim.gui.menu"

[[python.module]]
name = "isaacsim.gui.menu.tests"


[[test]]
timeout = 1500
dependencies = [
    "omni.timeline",
    "omni.isaac.utils",
    "isaacsim.sensors.physx",
    "isaacsim.sensors.physics",
    "isaacsim.sensors.rtx",
    "omni.kit.test_helpers_gfx"
]

stdoutFailPatterns.exclude = [
    '*[Error] [isaacsim.sensors.physics.plugin] *** error, No valid parent*',
    '*[Error] [isaacsim.sensors.physics.plugin] Imu Sensor does not exist*',
    '*[Error] [isaacsim.sensors.physics.plugin] Contact Sensor does not exist*',
    '*[isaacsim.sensors.physics.plugin] Failed to create contact sensor, parent prim is not found or invalid*',
    '*[Error] [isaacsim.sensors.physx.plugin] Lidar Sensor does not exist*',
    '*[Error] [isaacsim.sensors.physx.plugin] Generic Sensor does not exist*',
    '*[Error] [omni.kit.commands.command] Failed to execute a command: ChangeProperty*',
    '*[Error] [asyncio] Task exception was never retrieved*',
    '*[Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.*', # feature not included in Windows
    '*[Error] [isaacsim.sensors.physics.plugin] *** error: /Cube/Contact_Sensor parent prim is missing contact report API, automatically adding contact report API, stop and play the simulation for this change to take effect*',
    '*[Error] [isaacsim.sensors.physx.plugin] isLightBeamSensor: Light Beam Sensor does not exist*',
    '*[Error] [omni.hydra] Unsupported data type 0 on primvar *doNotCastShadows*'
]