[core]
reloadable = true
order = 0

[package]
version = "1.1.1"
category = "Rendering"
title = "Isaac Sim Asset Browser"
description = "A browser for Isaac Sim assets"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.asset.browser"
keywords = ["isaac", "browser", "asset"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.svg"
feature = true
# writeTarget.kit = true

[dependencies]
"omni.kit.browser.folder.core" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.usd" = {}
"omni.kit.viewport.utility" = { }
"omni.kit.tool.collect" = { optional=true }
"omni.kit.menu.stage" = { optional=true }
"omni.kit.clipboard" = { optional=true }
"isaacsim.core.deprecation_manager" = {}
"isaacsim.core.utils" = {}
"omni.pip.cloud" = {}

# Main python module this extension provides, it will be publicly available as "import isaacsim.asset.browser".
[[python.module]]
name = "isaacsim.asset.browser"

[settings]
exts."isaacsim.asset.browser".folders = [
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Environments",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/IsaacLab",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Materials",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/People",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Props",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Robots",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Samples",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Sensors",
]

exts."isaacsim.asset.browser".instanceable = []
exts."isaacsim.asset.browser".data.timeout = 10
exts."isaacsim.asset.browser".visible_after_startup = true

[[trigger]]
menu.name = "Window/Browsers/Isaac"
menu.window = "Isaac Sim Assets"


[[test]]
dependencies = [
    "omni.kit.renderer.core",
    "omni.kit.renderer.capture",
    "omni.kit.tool.collect",
    "omni.kit.menu.stage",
    "omni.kit.ui_test",
    "omni.usd",
    "omni.kit.clipboard",
    "omni.kit.browser.asset",
]

args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/menu/legacy_mode=false",
    "--/exts/omni.kit.browser.asset/folders/0=''",
    "--/exts/omni.kit.browser.asset/folders/1=''",
    "--/exts/omni.kit.browser.asset/folders/2=''",
    "--/exts/omni.kit.browser.asset/visible_after_startup=true",
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
