display_name = "Robot Engine Bridge GXF"

[package]
version = "0.1.1"
title = "Robot Engine Bridge GXF"
description = "Communication bridge for the Isaac SDK GXF backend"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
category = "Simulation"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
# "omni.graph.core" = {} # needed for fastcache
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.isaac.core" = {}
"omni.syntheticdata" = {}
"omni.usd.schema.isaac" = {}
"omni.isaac.core_archive" = {} # construct

[[python.module]]
name = "omni.isaac.robot_engine_bridge_gxf"

[[python.module]]
name = "omni.isaac.pygxf"

[[python.module]]
name = "omni.isaac.robot_engine_bridge_gxf.tests"
public = false

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[[native.library]]
path = "lib/libcudart.so.10.2"

[[native.library]]
path = "lib/libnppc.so.10"

[[native.library]]
path = "lib/libnppial.so.10"

[[native.library]]
path = "lib/libnppidei.so.10"

[[native.library]]
path = "lib/libnppif.so.10"

[[native.library]]
path = "lib/libnppig.so.10"

[[native.library]]
path = "lib/libnpps.so.10"

[fswatcher.patterns]
# include = ["*.ogn", "*.py"]
exclude = ["*/__pycache__*", "*/.git*", "*/packages", "Ogn*Database.py",  "*/gxf"]
