name = "Isaac Sim Daily"
#displayed application name in smaller card and library view
shortName = "Isaac Sim Daily"
version = "${version}"
#boolean for if this version is the latest version
latest = true
#unique identifier for component, all lower case, persists between versions
slug = "isaac-sim-daily"

#displayed before application name in launcher
productArea = ""
#category of content
category = "Daily"

# A filter of release types
# 3 filter types [ "alpha", "beta", "release "]
channel = "alpha"

# Set true if you want this package to show in enterprise launcher
enterpriseStatus = false

#values for filtering content, not implemented yet
tags = [
  "Autonomous Machines",
  "Robotics",
  "Manufacturing",
  "Synthetic Data Generation",
  "Simulation"
]

#enum of "app", "connector" and "experience" for now
kind = "app"

#string array, each line is a new line, keep lines under 256 char and keep lines under 4
description = [
  "DAILY INTERNAL BUILD !!, use the Stable Build for Production Work.",
  "DAILY INTERNAL BUILD !!, see [Developer README](https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/blob/develop/README.md) link below.",
  "NVIDIA Isaac Sim is a scalable robotics simulation application and synthetic data generation tool, built on the NVIDIA Omniverse™ platform. It leverages Omniverse Kit powerful simulation technologies including advanced GPU-enabled physics simulation with PhysX 5, photorealism with real-time ray tracing.",
  "Isaac Sim is a physically accurate virtual environment to develop, test, and manage AI-based robots, and provides the essential features for building virtual robotics experiments.",
  "Features:",
  "- Isaac Sim includes many tools for importing and simulating robot models, and simulating sensors such as RGB-D, PhysX-Lidar, RTX-Lidar, Radar, contact and IMU.",
  "- Isaac Sim supports various robotics applications including navigation, manipulation, and AI applications through Python and ROS.",
  "- For AI applications, Isaac Sim provides extensive tools such as Isaac Replicator for synthetic data generation and domain randomization, Isaac Gym for reinforcement learning.",
  "- For development tools Isaac Sim includes Isaac core API, Isaac Orbit and Cortex. Isaac Core API, is a robotics abstraction layer which hides the USD complexity, Isaac Orbit provides ready development environment, and Cortex for high level decision programing.",
  "- Isaac Sim comes with extensions for building a warehouse such as sim-ready assets, conveyor tools, people and CuOpt for logistics and route optimization",
]

#array of links for more info on product

[[links]]
title = "Developer README"
url = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/blob/develop/README.md"
[[links]]
title = "System Requirements"
url = "https://omniverse.gitlab-master-pages.nvidia.com/isaac/omni_isaac_sim/isaacsim/latest/requirements.html"
[[links]]
title = "Release Notes"
url = "https://omniverse.gitlab-master-pages.nvidia.com/isaac/omni_isaac_sim/isaacsim/latest/release_notes.html"
[[links]]
title = "Documentation"
url = "https://omniverse.gitlab-master-pages.nvidia.com/isaac/omni_isaac_sim/isaacsim/latest/overview.html"
