# Optional note that will be shown below system requirements.
# Supports markdown.
note = "Note: Omniverse is built to run on any RTX-powered machine. For latest recommended drivers, visit [NVIDIA OMNIVERSE - Driver Requirements](https://developer.nvidia.com/omniverse/driver/)."

# System requirements specs.
# Supports line breaks.
[minimum]
cpuNames = "Intel Core i7 (7th Generation)\nAMD Ryzen 5"
cpuCores = "4"
ram = "32GB"
storage = "50GB SSD"
vram = "8GB"
gpu = "Any RTX GPU"

[recommended]
cpuNames = "Intel Core i7 (9th Generation)\nAMD Ryzen 7"
cpuCores = "8"
ram = "64GB"
storage = "500GB SSD"
vram = "10GB"
gpu = "GeForce RTX 3080\nQuadro RTX A5000"