display_name = "Isaac Isaac Tests"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}
"omni.kit.window.toolbar" = {} # needed for simulation to happen

[[python.module]]
name = "omni.isaac.tests"
