display_name = "Domain Randomization"

[package]
version = "0.1.0"
title = "Domain Randomization"
desciption = "This extension randomizes domain parameters in Omniverse Kit"
authors = ["Shoubhik Debnath <sdebnath@nvidia.com>", "Hammad Mazhar <hmazhar@nvidia.com>"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac/dr"
keywords = ["kit", "domain", "randomizer"]
changelog = "config/CHANGELOG.md"

[dependencies]
"omni.kit.editor" = {}
"omni.isaac.dynamic_control" = {}
"omni.client" = {}

[[python.modules]]
name = "omni.isaac.dr"

[[python.modules]]
name = "omni.isaac.dr.scripts.samples"

[[python.modules]]
name = "omni.isaac.dr.scripts.random_room_sample"

[[python.modules]]
name = "omni.isaac.DrSchema"
public = false

[[native.plugins]]
search_path = "bin/${platform}/${config}/*.plugin"
recursive = false

[[libraries]]
path = "bin/${platform}/${config}/${lib_prefix}drSchema${lib_ext}"
