display_name = "Domain Randomization"

[dependencies]
"omni.kit.editor" = {}
"omni.client" = {}

[[python.modules]]
name = "omni.isaac.dr"

[[python.modules]]
name = "omni.isaac.dr.scripts.samples"

[[python.modules]]
name = "omni.isaac.DrSchema"
public = false

[[native.plugins]]
search_path = "bin/${platform}/${config}/*.plugin"
recursive = false

[[libraries]]
path = "bin/${platform}/${config}/${lib_prefix}drSchema${lib_ext}"
