[core]
reloadable = true
order = 0

[package]
version = "3.0.1"
category = "Simulation"
title = "ROS2 Bridge"
description = "ROS2 Bridge"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.ros2_bridge"
keywords = ["isaac", "ROS2"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.ros2.bridge" = {}

[[python.module]]
name = "omni.isaac.ros2_bridge"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.ros2.bridge."
