[package]
version = "2.0.8"
category = "Simulation"
title = "Isaac Sim Merge Mesh"
description = "Isaac Sim tool to facilitate combining meshes together in a single USD Prim. It provides the ability to reset the mesh origin to world origin, and combining all materials into a single list, combining materials with the same characteristics."
authors = ["hmazhar@nvidia.com", "rgasoto@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.util.merge_mesh"
keywords = ["isaac", "merge", "mesh",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.gui.components" = {}

[[python.module]]
name = "isaacsim.util.merge_mesh"

[[python.module]]
name = "isaacsim.util.merge_mesh.tests"

[[test]]
dependencies = [
    "omni.kit.material.library",
    "omni.kit.primitive.mesh",
]
