[core]
reloadable = true
order = 0

[package]
version = "2.0.0"
category = "Simulation"
title = "Isaac Sim Lula"
description = "Extension that provides lula python interface"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.lula"
keywords = ["isaac", "lula", "rmp"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true
writeTarget.platform = true # pip prebundle makes this extension os specific

[dependencies]
"omni.kit.test" = {}
"omni.kit.pip_archive" = {}

[[python.module]]
path = "pip_prebundle"

[[python.module]]
name = "omni.isaac.lula"

[[python.module]]
name = "omni.isaac.lula.tests"