[core]
reloadable = true
order = 0

[package]
version = "0.1.6"
category = "Simulation"
title = "Isaac Sim Samples"
description = "Sample extensions for Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.samples"
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.physx" = {}
"omni.physx.vehicle" = {}
# "omni.graph.core" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.motion_planning" = {}
"omni.isaac.utils" = {}
"omni.isaac.manip" = {}
"omni.isaac.synthetic_utils" = {}
"omni.isaac.dr" = {}

[[python.module]]
name = "omni.isaac.samples.tests"

[[python.module]]
name = "omni.isaac.samples.scripts.kaya_preview"

[[python.module]]
name = "omni.isaac.samples.scripts.jetbot_preview"

[[python.module]]
name = "omni.isaac.samples.scripts.dofbot_preview"

[[python.module]]
name = "omni.isaac.samples.scripts.leonardo_preview"

[[python.module]]
name = "omni.isaac.samples.scripts.ur10_preview"

[[python.module]]
name = "omni.isaac.samples.scripts.navigation_preview"

[[python.module]]
name = "omni.isaac.samples.scripts.dofbot_rmp_sample"

[[python.module]]
name = "omni.isaac.samples.scripts.rmp_sample"

[[python.module]]
name = "omni.isaac.samples.scripts.replay_sample"

[[python.module]]
name = "omni.isaac.samples.scripts.ros_samples"

[[python.module]]
name = "omni.isaac.samples.scripts.ros_moveit_sample"
