[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "Simulation"
title = "Isaac Sim Samples"
description = "Sample extensions for Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.samples"
keywords = ["isaac", "samples", "manipulation"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.editor" = {}
"omni.physx" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.motion_planning" = {}
"omni.isaac.utils" = {}
"omni.isaac.manip" = {}

[[python.modules]]
name = "omni.isaac.samples"

[[python.modules]]
name = "omni.isaac.samples.scripts.kaya_preview"

[[python.modules]]
name = "omni.isaac.samples.scripts.jetbot_preview"

[[python.modules]]
name = "omni.isaac.samples.scripts.leonardo_preview"

[[python.modules]]
name = "omni.isaac.samples.scripts.ur10_preview"

[[python.modules]]
name = "omni.isaac.samples.scripts.simple_navigation_preview"

[[python.modules]]
name = "omni.isaac.samples.scripts.rmp_sample"
