[core]
reloadable = true
order = 0

[package]
version = "1.3.0"
title = "GXF Bridge"
description = "Communication bridge for the Isaac SDK GXF backend"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
category = "Simulation"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true
writeTarget.platform = true

[dependencies]
"omni.kit.uiapp" = {}
# "omni.graph.core" = {} # needed for fastcache
"omni.isaac.dynamic_control" = {}
"omni.isaac.range_sensor" = {}
"omni.isaac.core" = {}
"omni.isaac.core_nodes" = {}
"omni.isaac.sensor" = {}
"omni.syntheticdata" = {}
"omni.usd.schema.isaac" = {}
"omni.isaac.core_archive" = {} # construct
"usdrt.scenegraph" = {}

[settings]
exts."omni.isaac.gxf_bridge".yamlBaseFolder = "${app}/../exts/omni.isaac.gxf_bridge/data/yaml/"
exts."omni.isaac.gxf_bridge".supportedAMRReleases = ["2.0"]

[[python.module]]
name = "omni.isaac.gxf_bridge"

# [[python.module]]
# name = "omni.isaac.pygxf"

[[python.module]]
name = "omni.isaac.gxf_bridge.tests"
public = false

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[[native.library]]
path = "lib/libcudart.so"

[[native.library]]
path = "lib/libnppc.so"

[[native.library]]
path = "lib/libnppial.so"

[[native.library]]
path = "lib/libnppidei.so"

[fswatcher.paths]
exclude = ["*/pygxf*", "*/bin", "*/__pycache__/*", "*/.git/*"]

[fswatcher.patterns]
include = ["*.ogn", "*.py", "*.toml"]
exclude = ["Ogn*Database.py"]

[[test]]
stdoutFailPatterns.exclude = [
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_gxf_bridge_GXFGetYAMLFilePath: [/TestGraph] OmniGraph Error: Input path cannot be empty.*",
    "*[Error] [omni.graph.core.plugin] /TestGraph/Template_omni_isaac_gxf_bridge_GXFPoseTreeFrameMapBuilder: [/TestGraph] Please specify at least one target prim for the GXF pose tree component*",
    "*[Error] [omni.isaac.gxf_bridge.plugin] Cannot set context*",
    "*[Error] [omni.isaac.gxf_bridge.scripts.amr_nucleus] Could not find path on Nucleus server:*",
    "*[Error] [omni.isaac.gxf_bridge.scripts.amr_nucleus] Isaac * not supported by current version of Isaac Sim GXF Bridge Extension.*",
    "*[Error] [omni.isaac.gxf_bridge.scripts.amr_nucleus] Unexpected asset tier.*",
]
