[core]
reloadable = true
order = 0

[package]
version = "1.1.1"
category = "Simulation"
title = "Grasp Editor"
description = "Author grasps by hand for a specific robot gripper and USD asset."
authors = ["Isaac Sim Team"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}

[[python.module]]
name = "omni.isaac.grasp_editor"