[core]
reloadable = true
order = 0

[package]
version = "0.1.4"
category = "Simulation"
title = "Isaac Sim UI Example"
description = "Example with all the Core UI Elements in Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.ui_template"
keywords = ["isaac", "example", "ui",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}

[[python.module]]
name = "omni.isaac.ui_template"

[[python.module]]
name = "omni.isaac.ui_template.tests"
