name = "Isaac Sim"
#displayed application name in smaller card and library view
shortName = "Isaac Sim"
version = "${version}"
#boolean for if this version is the latest version
latest = true
#unique identifier for component, all lower case, persists between versions
slug = "isaac_sim"

#displayed before application name in launcher
productArea = ""
#category of content
category = "Apps"

# A filter of release types
# 3 filter types [ "alpha", "beta", "release "]
channel = "beta"

# Set true if you want this package to show in enterprise launcher
enterpriseStatus = false

#values for filtering content, not implemented yet
tags = [
  "Autonomous Machines",
  "Robotics",
  "Manufacturing",
  "Synthetic Data Generation",
  "Simulation"
]

#enum of "app", "connector" and "experience" for now
kind = "app"
#string array, each line is a new line, keep lines under 256 char and keep lines under 4
description = [
  "NVIDIA Isaac Sim is a scalable robotics simulation application and synthetic data generation tool, built on the NVIDIA Omniverse™ platform. It leverages Omniverse Kit powerful simulation technologies including advanced GPU-enabled physics simulation with PhysX 5, photorealism with real-time ray and path tracing, and MDL material definition support for physically-based rendering. Isaac Sim is a physically-accurate virtual environment to develop, test, and manage AI-based robots, and provides the essential features for building virtual robotics experiments, including importing robot models, and simulating sensors such as RGB-D, Lidar, contact, ultrasonic, and IMU. Isaac Sim supports navigation, manipulation, deep learning applications through Python, ROS and Isaac SDK. For AI applications, Isaac Sim provides extensive tools such as Isaac Replicator for synthetic data generation and domain randomization, Isaac Gym for reinforcement learning and Cortex for high level decision programing."
]

#array of links for more info on product

[[links]]
title = "System Requirements"
url = "https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/requirements.html"
[[links]]
title = "Release Notes"
url = "https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/release_notes.html"
[[links]]
title = "Documentation"
url = "https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/overview.html"
[[links]]
title = "Tutorials"
url = "https://www.nvidia.com/en-us/on-demand/search/?facet.mimetype[]=event%20session&page=1&q=isaac%20sim&sort=date"
[[links]]
title = "Forums"
url = "https://forums.developer.nvidia.com/c/agx-autonomous-machines/isaac/simulation/69"
