// Generated by gencpp from file isaac_bridge/IsaacPose.msg
// DO NOT EDIT!


#ifndef ISAAC_BRIDGE_MESSAGE_ISAACPOSE_H
#define ISAAC_BRIDGE_MESSAGE_ISAACPOSE_H

#include <ros/service_traits.h>

#include <IsaacPoseRequest.h>
#include <IsaacPoseResponse.h>


namespace isaac_bridge
{

struct IsaacPose
{

    typedef IsaacPoseRequest Request;
    typedef IsaacPoseResponse Response;
    Request request;
    Response response;

    typedef Request RequestType;
    typedef Response ResponseType;

}; // struct IsaacPose
} // namespace isaac_bridge


namespace ros
{
namespace service_traits
{


template <>
struct MD5Sum<::isaac_bridge::IsaacPose>
{
    static const char* value()
    {
        return "8511adbe7667fc4c8d731c0a60fa04fa";
    }

    static const char* value(const ::isaac_bridge::IsaacPose&)
    {
        return value();
    }
};

template <>
struct DataType<::isaac_bridge::IsaacPose>
{
    static const char* value()
    {
        return "isaac_bridge/IsaacPose";
    }

    static const char* value(const ::isaac_bridge::IsaacPose&)
    {
        return value();
    }
};


// service_traits::MD5Sum< ::isaac_bridge::IsaacPoseRequest> should match
// service_traits::MD5Sum< ::isaac_bridge::IsaacPose >
template <>
struct MD5Sum<::isaac_bridge::IsaacPoseRequest>
{
    static const char* value()
    {
        return MD5Sum<::isaac_bridge::IsaacPose>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacPoseRequest&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_bridge::IsaacPoseRequest> should match
// service_traits::DataType< ::isaac_bridge::IsaacPose >
template <>
struct DataType<::isaac_bridge::IsaacPoseRequest>
{
    static const char* value()
    {
        return DataType<::isaac_bridge::IsaacPose>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacPoseRequest&)
    {
        return value();
    }
};

// service_traits::MD5Sum< ::isaac_bridge::IsaacPoseResponse> should match
// service_traits::MD5Sum< ::isaac_bridge::IsaacPose >
template <>
struct MD5Sum<::isaac_bridge::IsaacPoseResponse>
{
    static const char* value()
    {
        return MD5Sum<::isaac_bridge::IsaacPose>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacPoseResponse&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_bridge::IsaacPoseResponse> should match
// service_traits::DataType< ::isaac_bridge::IsaacPose >
template <>
struct DataType<::isaac_bridge::IsaacPoseResponse>
{
    static const char* value()
    {
        return DataType<::isaac_bridge::IsaacPose>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacPoseResponse&)
    {
        return value();
    }
};

} // namespace service_traits
} // namespace ros

#endif // ISAAC_BRIDGE_MESSAGE_ISAACPOSE_H
