// Generated by gencpp from file isaac_bridge/IsaacBoundingBox.msg
// DO NOT EDIT!


#ifndef ISAAC_BRIDGE_MESSAGE_ISAACBOUNDINGBOX_H
#define ISAAC_BRIDGE_MESSAGE_ISAACBOUNDINGBOX_H


#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>

#include <map>
#include <string>
#include <vector>


namespace isaac_bridge
{
template <class ContainerAllocator>
struct IsaacBoundingBox_
{
    typedef IsaacBoundingBox_<ContainerAllocator> Type;

    IsaacBoundingBox_() : name(), confidence(0.0), xmin(0), ymin(0), xmax(0), ymax(0)
    {
    }
    IsaacBoundingBox_(const ContainerAllocator& _alloc)
        : name(_alloc), confidence(0.0), xmin(0), ymin(0), xmax(0), ymax(0)
    {
        (void)_alloc;
    }


    typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other> _name_type;
    _name_type name;

    typedef double _confidence_type;
    _confidence_type confidence;

    typedef int64_t _xmin_type;
    _xmin_type xmin;

    typedef int64_t _ymin_type;
    _ymin_type ymin;

    typedef int64_t _xmax_type;
    _xmax_type xmax;

    typedef int64_t _ymax_type;
    _ymax_type ymax;


    typedef boost::shared_ptr<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacBoundingBox_

typedef ::isaac_bridge::IsaacBoundingBox_<std::allocator<void>> IsaacBoundingBox;

typedef boost::shared_ptr<::isaac_bridge::IsaacBoundingBox> IsaacBoundingBoxPtr;
typedef boost::shared_ptr<::isaac_bridge::IsaacBoundingBox const> IsaacBoundingBoxConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>>::stream(s, "", v);
    return s;
}

} // namespace isaac_bridge

namespace ros
{
namespace message_traits
{


// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'isaac_bridge':
// ['/home/hmazhar/repos/srl_system/workspace/src/isaac_bridge/msg'], 'std_msgs':
// ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs':
// ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__',
// '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__',
// '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name',
// 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']


template <class ContainerAllocator>
struct IsFixedSize<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator> const> : FalseType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>>
{
    static const char* value()
    {
        return "35aed43c98414d6d8e8bc8fbc4048d28";
    }

    static const char* value(const ::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0x35aed43c98414d6dULL;
    static const uint64_t static_value2 = 0x8e8bc8fbc4048d28ULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_bridge/IsaacBoundingBox";
    }

    static const char* value(const ::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>>
{
    static const char* value()
    {
        return "string name\n"
               "float64 confidence\n"
               "int64 xmin\n"
               "int64 ymin\n"
               "int64 xmax\n"
               "int64 ymax\n";
    }

    static const char* value(const ::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.name);
        stream.next(m.confidence);
        stream.next(m.xmin);
        stream.next(m.ymin);
        stream.next(m.xmax);
        stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacBoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream& s, const std::string& indent, const ::isaac_bridge::IsaacBoundingBox_<ContainerAllocator>& v)
    {
        s << indent << "name: ";
        Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other>>::stream(
            s, indent + "  ", v.name);
        s << indent << "confidence: ";
        Printer<double>::stream(s, indent + "  ", v.confidence);
        s << indent << "xmin: ";
        Printer<int64_t>::stream(s, indent + "  ", v.xmin);
        s << indent << "ymin: ";
        Printer<int64_t>::stream(s, indent + "  ", v.ymin);
        s << indent << "xmax: ";
        Printer<int64_t>::stream(s, indent + "  ", v.xmax);
        s << indent << "ymax: ";
        Printer<int64_t>::stream(s, indent + "  ", v.ymax);
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_BRIDGE_MESSAGE_ISAACBOUNDINGBOX_H
