// Generated by gencpp from file isaac_bridge/IsaacPoseResponse.msg
// DO NOT EDIT!


#ifndef ISAAC_BRIDGE_MESSAGE_ISAACPOSERESPONSE_H
#define ISAAC_BRIDGE_MESSAGE_ISAACPOSERESPONSE_H


#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>

#include <map>
#include <string>
#include <vector>


namespace isaac_bridge
{
template <class ContainerAllocator>
struct IsaacPoseResponse_
{
    typedef IsaacPoseResponse_<ContainerAllocator> Type;

    IsaacPoseResponse_()
    {
    }
    IsaacPoseResponse_(const ContainerAllocator& _alloc)
    {
        (void)_alloc;
    }


    typedef boost::shared_ptr<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacPoseResponse_

typedef ::isaac_bridge::IsaacPoseResponse_<std::allocator<void>> IsaacPoseResponse;

typedef boost::shared_ptr<::isaac_bridge::IsaacPoseResponse> IsaacPoseResponsePtr;
typedef boost::shared_ptr<::isaac_bridge::IsaacPoseResponse const> IsaacPoseResponseConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>>::stream(s, "", v);
    return s;
}

} // namespace isaac_bridge

namespace ros
{
namespace message_traits
{


// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'isaac_bridge':
// ['/home/hmazhar/repos/srl_system/workspace/src/isaac_bridge/msg'], 'std_msgs':
// ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs':
// ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__',
// '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__',
// '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name',
// 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']


template <class ContainerAllocator>
struct IsFixedSize<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator> const> : FalseType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>>
{
    static const char* value()
    {
        return "d41d8cd98f00b204e9800998ecf8427e";
    }

    static const char* value(const ::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
    static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_bridge/IsaacPoseResponse";
    }

    static const char* value(const ::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>>
{
    static const char* value()
    {
        return "\n";
    }

    static const char* value(const ::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream&, T)
    {
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream&, const std::string&, const ::isaac_bridge::IsaacPoseResponse_<ContainerAllocator>&)
    {
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_BRIDGE_MESSAGE_ISAACPOSERESPONSE_H
