// Generated by gencpp from file isaac_bridge/IsaacJointStates.msg
// DO NOT EDIT!


#ifndef ISAAC_BRIDGE_MESSAGE_ISAACJOINTSTATES_H
#define ISAAC_BRIDGE_MESSAGE_ISAACJOINTSTATES_H

#include <ros/service_traits.h>

#include <IsaacJointStatesRequest.h>
#include <IsaacJointStatesResponse.h>


namespace isaac_bridge
{

struct IsaacJointStates
{

    typedef IsaacJointStatesRequest Request;
    typedef IsaacJointStatesResponse Response;
    Request request;
    Response response;

    typedef Request RequestType;
    typedef Response ResponseType;

}; // struct IsaacJointStates
} // namespace isaac_bridge


namespace ros
{
namespace service_traits
{


template <>
struct MD5Sum<::isaac_bridge::IsaacJointStates>
{
    static const char* value()
    {
        return "482cc7b23f4d6ca5e5aac26ecce1ce01";
    }

    static const char* value(const ::isaac_bridge::IsaacJointStates&)
    {
        return value();
    }
};

template <>
struct DataType<::isaac_bridge::IsaacJointStates>
{
    static const char* value()
    {
        return "isaac_bridge/IsaacJointStates";
    }

    static const char* value(const ::isaac_bridge::IsaacJointStates&)
    {
        return value();
    }
};


// service_traits::MD5Sum< ::isaac_bridge::IsaacJointStatesRequest> should match
// service_traits::MD5Sum< ::isaac_bridge::IsaacJointStates >
template <>
struct MD5Sum<::isaac_bridge::IsaacJointStatesRequest>
{
    static const char* value()
    {
        return MD5Sum<::isaac_bridge::IsaacJointStates>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJointStatesRequest&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_bridge::IsaacJointStatesRequest> should match
// service_traits::DataType< ::isaac_bridge::IsaacJointStates >
template <>
struct DataType<::isaac_bridge::IsaacJointStatesRequest>
{
    static const char* value()
    {
        return DataType<::isaac_bridge::IsaacJointStates>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJointStatesRequest&)
    {
        return value();
    }
};

// service_traits::MD5Sum< ::isaac_bridge::IsaacJointStatesResponse> should match
// service_traits::MD5Sum< ::isaac_bridge::IsaacJointStates >
template <>
struct MD5Sum<::isaac_bridge::IsaacJointStatesResponse>
{
    static const char* value()
    {
        return MD5Sum<::isaac_bridge::IsaacJointStates>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJointStatesResponse&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_bridge::IsaacJointStatesResponse> should match
// service_traits::DataType< ::isaac_bridge::IsaacJointStates >
template <>
struct DataType<::isaac_bridge::IsaacJointStatesResponse>
{
    static const char* value()
    {
        return DataType<::isaac_bridge::IsaacJointStates>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJointStatesResponse&)
    {
        return value();
    }
};

} // namespace service_traits
} // namespace ros

#endif // ISAAC_BRIDGE_MESSAGE_ISAACJOINTSTATES_H
