// Generated by gencpp from file isaac_bridge/IsaacJSON.msg
// DO NOT EDIT!


#ifndef ISAAC_BRIDGE_MESSAGE_ISAACJSON_H
#define ISAAC_BRIDGE_MESSAGE_ISAACJSON_H

#include <ros/service_traits.h>

#include <IsaacJSONRequest.h>
#include <IsaacJSONResponse.h>


namespace isaac_bridge
{

struct IsaacJSON
{

    typedef IsaacJSONRequest Request;
    typedef IsaacJSONResponse Response;
    Request request;
    Response response;

    typedef Request RequestType;
    typedef Response ResponseType;

}; // struct IsaacJSON
} // namespace isaac_bridge


namespace ros
{
namespace service_traits
{


template <>
struct MD5Sum<::isaac_bridge::IsaacJSON>
{
    static const char* value()
    {
        return "bba21b380002512f5222266cbd4dc034";
    }

    static const char* value(const ::isaac_bridge::IsaacJSON&)
    {
        return value();
    }
};

template <>
struct DataType<::isaac_bridge::IsaacJSON>
{
    static const char* value()
    {
        return "isaac_bridge/IsaacJSON";
    }

    static const char* value(const ::isaac_bridge::IsaacJSON&)
    {
        return value();
    }
};


// service_traits::MD5Sum< ::isaac_bridge::IsaacJSONRequest> should match
// service_traits::MD5Sum< ::isaac_bridge::IsaacJSON >
template <>
struct MD5Sum<::isaac_bridge::IsaacJSONRequest>
{
    static const char* value()
    {
        return MD5Sum<::isaac_bridge::IsaacJSON>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJSONRequest&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_bridge::IsaacJSONRequest> should match
// service_traits::DataType< ::isaac_bridge::IsaacJSON >
template <>
struct DataType<::isaac_bridge::IsaacJSONRequest>
{
    static const char* value()
    {
        return DataType<::isaac_bridge::IsaacJSON>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJSONRequest&)
    {
        return value();
    }
};

// service_traits::MD5Sum< ::isaac_bridge::IsaacJSONResponse> should match
// service_traits::MD5Sum< ::isaac_bridge::IsaacJSON >
template <>
struct MD5Sum<::isaac_bridge::IsaacJSONResponse>
{
    static const char* value()
    {
        return MD5Sum<::isaac_bridge::IsaacJSON>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJSONResponse&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_bridge::IsaacJSONResponse> should match
// service_traits::DataType< ::isaac_bridge::IsaacJSON >
template <>
struct DataType<::isaac_bridge::IsaacJSONResponse>
{
    static const char* value()
    {
        return DataType<::isaac_bridge::IsaacJSON>::value();
    }
    static const char* value(const ::isaac_bridge::IsaacJSONResponse&)
    {
        return value();
    }
};

} // namespace service_traits
} // namespace ros

#endif // ISAAC_BRIDGE_MESSAGE_ISAACJSON_H
