[package]
version = "1.0.1"
category = "Simulation"
title = "{EXTENSION_TITLE}"
description = "{EXTENSION_DESCRIPTION}"
authors = ["Add your name here"]
repository = "{EXTENSION_REPOSITORY}"
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "{PYTHON_PACKAGE_NAME}"