[package]
version = "2.0.4"
category = "Internal"
title = "Isaac Sim About Window"
description="Show application/build information."
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.window.about"
keywords = ["isaac", "about"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.app.about."

[dependencies]
"isaacsim.app.about" = {}
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "omni.isaac.window.about"

[[python.module]]
name = "omni.isaac.window.about.tests"

[[test]]
stdoutFailPatterns.exclude = [
    "*[Error] [carb.glinterop.plugin] GLInteropContext::init: carb::windowing is not available*",
]