[core]
reloadable = true
order = 0

[package]
version = "0.19.0"
category = "Simulation"
title = "Benchmark"
description = "This extension provides benchmarking utilities"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.benchmarks"
keywords = ["isaac", "benchmark", "analyze"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.isaac.benchmark.services" = {}
"omni.physx" = {}
"omni.isaac.core" = {}
"omni.isaac.core_nodes" = {}
"omni.graph" = {}
"omni.graph.tools" = {}
"omni.graph.ui" = {}
"omni.isaac.core_archive" = {} # pulls in nvsmi
"omni.isaac.range_sensor" = {}
"omni.isaac.sensor" = {}
"omni.isaac.wheeled_robots" = {}
"omni.hydra.rtx"= {}
"omni.kit.viewport.utility"= {}
"omni.kit.viewport.window"= {}
"omni.kit.primitive.mesh"= {}
"omni.kit.material.library"= {}

[dependencies."filter:platform"."linux-x86_64"]
"omni.isaac.ros2_bridge" = {}

[[python.module]]
name = "omni.isaac.benchmarks.tests"

[settings]
# uncomment and set this to output metrics to a specific folder
# exts."omni.isaac.benchmark.services".metrics.metrics_output_folder=""

[[test]]
# these are not cached
dependencies = [
    "omni.kit.testing.services",
    "omni.kit.nvdf.telemetry",
]
timeout=12000
args = ["--no-window", "--allow-root", "--/app/fastShutdown=1", "--vulkan"] # we can use fast shutdown because metrics are not uploaded
stdoutFailPatterns.exclude = [
    "*NGX EvaluateFeature failed*", # Ada multi gpu doesn't support this yet
    "*Failed to evaluate DLSS feature*", # Ada multi gpu doesn't support this yet
]