[core]
reloadable = true
order = 0

[package]
version = "0.1.2"
category = "Simulation"
title = "Isaac Sim URDF Importer"
description = "URDF Importer for Isaac Sim"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.urdf"
keywords = ["isaac", "urdf", "import"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.kit.editor" = {}
"omni.ui" = { order = -100 }
"omni.isaac.utils" = {}
"omni.kit.window.filepicker" = {}
"omni.kit.window.content_browser" = {order = 1} # order = 1 is a hack to prevent the extension from crashing if it loads too soon

[[python.module]]
name = "omni.isaac.urdf"

[[python.module]]
name = "omni.isaac.urdf.tests"

[[python.module]]
name = "omni.isaac.urdf.scripts.samples.import_carter"

[[python.module]]
name = "omni.isaac.urdf.scripts.samples.import_franka"

[[python.module]]
name = "omni.isaac.urdf.scripts.samples.import_kaya"

[[python.module]]
name = "omni.isaac.urdf.scripts.samples.import_ur10"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[python.pipapi]
requirements = ["graphviz==0.14.1", "pillow==7.2.0"]
