name: isaac-sim
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.0
  - matplotlib
  - pip
  - python=3.7
  - pytorch
  - requests
  - torchaudio
  - torchvision
  - six
  - pip:
    - gym
    - opencv-python
    - pillow
    - scipy
    - stable-baselines3
    - tensorboard
    - tensorboard-plugin-wit
    - tensorflow-estimator
    - tensorflow-gpu

