#!/bin/bash

set -e

error_exit()
{
    echo "There was an error running python"
    exit 1
}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_PATH=$SCRIPT_DIR
while [[ $BUILD_PATH != / ]];
do
    
    if ! find "$BUILD_PATH" -maxdepth 1 -mindepth 1 -iname "_build" -exec false {} +
    then
        break
    fi
    # Note: if you want to ignore symlinks, use "$(realpath -s "$BUILD_PATH"/..)"
    BUILD_PATH="$(readlink -f "$BUILD_PATH"/..)"
    
done

MY_DIR=$BUILD_PATH/_build

# Setup python env from generated file (generated by tools/repoman/build.py)
export EXP_PATH=$SCRIPT_DIR/experiences
source ${MY_DIR}/linux-x86_64/release/setup_python_env.sh

# By default use our python, but allow overriding it by checking if PYTHONEXE env var is defined:
python_exe=${PYTHONEXE:-"${MY_DIR}/kit_release/_build/target-deps/python/bin/python3"}

$python_exe $@ || error_exit
