display_name = "Robot Engine Bridge"

[dependencies]
"omni.kit.editor" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.lidar" = {}
"omni.syntheticdata" = {}

[[python.modules]]
name = "omni.isaac.robot_engine_bridge"

[[native.plugins]]
search_path = "bin/${platform}/${config}/*.plugin"
recursive = false

