[package]
version = "1.0.3"
category = "Simulation"
title = "Isaac Sim UI Example"
description = "Example with all the Core UI Elements in Isaac Sim"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.ui_template"
keywords = ["isaac", "example", "ui",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.examples.ui."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.examples.ui" = {}

[[python.module]]
name = "omni.isaac.ui_template"