#!/usr/bin/python3.10

################################################################################
## Libs
################################################################################

import os
import sys

bin_path = os.path.dirname(os.path.realpath(__file__))

sys.path.append(f"{bin_path}/common/lib")
sys.path.append(bin_path + "/lib")

import argparse
import getpass
import glob
import importlib.util
import io
import logging
import re
import shutil
import socket
import subprocess
from pprint import pprint
from time import localtime, strftime

import nvidia.docker
import nvidia.docker.registry.argparse
import nvidia.git
from nvidia.die import die
from nvidia.docker.utils.misc import get_images_list

################################################################################
## Globals
################################################################################

description = "Grab license files and package lists from docker images"
args = None
my_git_hash = nvidia.git.get_git_hash_short(bin_path)
my_repo = nvidia.git.get_origin_url(bin_path)

blacklist_env_var="DOCKER_IMAGE_SWIPAT_BLACKLIST"
blacklist = []

docker = None

class defaults:
  pass
#  version_file = os.path.abspath(os.path.join(bin_path, "../../VERSION.md"))


################################################################################
## Init
################################################################################

def init():
  logging.basicConfig(format="%(message)s", level=logging.INFO)
  nvidia.die.log_instead_of_stderr()

  logging.info(f"NPM/PIP SWIPAT tool location: {my_repo}")
  logging.info(f"NPM/PIP SWIPAT tool hash: {my_git_hash}")

  parse_args()

  global docker
  docker = init_docker_conn()
  
  blacklist = os.getenv(blacklist_env_var, "").split(":")

  args.images = get_images_list(args.images, tools_ctx=bin_path, docker=docker, 
                                skips=blacklist)

################################################################################
## Main
################################################################################

def main():
  if(os.path.isdir(args.out_dir)):
    die(f"{args.out_dir} exists: refusing to proceed")

  os.makedirs(args.out_dir)
  logging.info(f"Output root: {args.out_dir}")

  for image in args.images:
    logging.info(f"  > {image}")
    img_dir = image
    img_dir = img_dir.replace(":", "_")
    out_dir = os.path.join(args.out_dir, img_dir)
    logging.info(f"  > output to  {out_dir}")

    os.makedirs(out_dir)
    report = collect_licenses(image, out_dir=out_dir)
    if(not(len(report['license_files']))):
      empty_marker = os.path.join(out_dir, "exists")
      logging.info(f"  > no license files found for this image, placing " +
                   f"empty marker at {empty_marker}")
      with open(empty_marker, 'w') as h:
        h.write('exists')
    else:
      bug_body = gen_swipat_bug(image=image,       
                               licenses = report['license_files'],
                               packages = report['package_lists'])

      bug_out = f"{out_dir}/swipat_bug_body.txt"
      with(open(bug_out, 'w') as h):
        h.write(bug_body)
      logging.info(f"  > SWIPAT bug body written to {bug_out}")

################################################################################
## Functions
################################################################################

def gen_swipat_bug(image, licenses=[], packages=[]):
  return f"""
THIS BUG WAS AUTOMATICALLY GENERATED BY OMNIVERSE BUILD PIPELINE. 
SAID PARTICULAR PIPELINE ENSURES ONLY PACKAGES WITH PERMISSIVE 
(MIT, Apache, et al) LICENSES ARE ALLOWED AND WILL FAIL OTHERWISE.

IF THIS BUG WAS FILED, THAT SIGNIFIES THAT THE BUILD PIPELINE HAS
PASSED AND VALIDATED THAT ALL DEPENDENCIES LISTED HERE WERE LICENSED
PERMISSIVELY. 
---------------------------------------------------------------------

SOFTWARE IP AUDIT TEAM: OPEN SOURCE SOFTWARE (“OSS”) - USING OSS

BACKGROUND
----------
Every piece of software comes with a license. Open source software in particular has a variety of licensing implications to be aware of.  Please fill out the following form if you intend to interact with a piece of open source software to import an existing open source project into NVIDIA, either for internal use or for use in an NVIDIA product.

Name
----
Automated tooling for SWIPAT Pipeline / Docker Containers
PIP and NPM dependencies

Build tooling repo    : {my_repo}
Build tooling GIT hash: {my_git_hash}


Business Unit/Product
---------------------
Omniverse

Summary of the Request
----------------------
Recording usage of permissively licensed dependencies of {image}

Name of Open Source Project
---------------------------
Multiple - see attached lists in {", ".join(packages)}

Version Number of Open Source Project
-------------------------------------
Multiple - see attached lists in {", ".join(packages)}

Does this Open Source Project depend upon additional
Open Source Projects that will also be needed?
----------------------------------------------
See attached lists in {", ".join(packages)}

Target Date for Use
-------------------
ASAP

Origin of the OSS: From whom did NVIDIA receive the software?
-------------------------------------------------------------
PIP and/or NPM

URL or other method through which the OSS was received
------------------------------------------------------
Multiple

Is the OSS also available under a commercial license?
-----------------------------------------------------
No

If OSS was received from an OEM, date of agreement with OEM
-----------------------------------------------------------
N/A

Was the OSS developed as part of a project for which NVIDIA received
government funding?
--------------------------------------------------------------------
Unknown

Overview: how will the OSS be used?
-----------------------------------
Build- and runtime dependencies for the following Omniverse component: {image}

Code Modification
-----------------
USING OSS WITH NO CHANGES


Frequency of Code Modification
------------------------------
N/A

Compilation: Who Will Compile the Source?
-----------------------------------------
* N/A - CODE IS INTERPRETED, NOT COMPILED, NO COMPILATION IS NECESSARY

Interaction with NVIDIA Software
--------------------------------
* OSS IS EMBEDDED, STATICALLY LINKED, OR OTHERWISE INTEGRATED INTO NVIDIA CODE

Does the open source software provide functionality that requires export
control consideration?  Software source code that implements or uses
encryption for confidentiality of either stored data (e.g., AES) or data
in transit (e.g., HTTPS/SSL/TLS) raises export control considerations.
-------------------------------------------------------------------------
Yes - for HTTP transport only

To Whom will NVIDIA Distribute the OSS?
---------------------------------------
* DISTRIBUTED TO THE GENERAL PUBLIC VIA DOWNLOAD OR MEDIA


Will the OSS be distributed by NVIDIA in binary form?
-----------------------------------------------------
YES

Will this software be distributed by NVIDIA in source code form?
----------------------------------------------------------------
YES

License URL
------------
Various permissive: see attached license packs in {", ".join(licenses)}

License Text
------------
See attached license packs in {", ".join(licenses)}

--

Self-Checkout Guidance for Use of Unmodified Permissively-licensed Software

1) The initial commit of this software to revision control should be "as-received" from the source listed above.  If not feasible to submit to revision control, you can attach the unmodified sources to a tracking bug for this library/feature; in either case, indicate the location and date from which the source code was received in the change log or bug comment.

If you submit the source to source control, please cite this SWIPAT bug number in the perforce changelist description or git commit message, so that it is easier to correlate the imported source with this request.

2) Product documentation must indicate this software is present, and the specific copyright and license terms that apply. The technical publications team for your project can provide you guidance with this - if you require further information please contact us again.


"""

def collect_licenses(image, out_dir=None):
  ret = { 'license_files':[], 'package_lists': [] }
  tmp_dir = os.path.join(out_dir, "tmp")
  os.makedirs(tmp_dir)

  logging.info(f"  > copying licensing info out of the container")
  docker.copy_from_image(image, f"/omni/PACKAGE-LICENSES/", 
                         tmp_dir)

  for lic_type in ['npm', 'pip']:
    logging.info(f"  > processing {lic_type}")
    licenses_root = os.path.join(tmp_dir, "PACKAGE-LICENSES", lic_type)
    if(not os.path.isdir(licenses_root)):
      die(f"Can't locate {lic_type} licenses in the container!")

    packages_file = os.path.join(licenses_root, 'packages.txt')
    licenses_file = os.path.join(licenses_root, 'licenses.txt')
    empty_marker = os.path.join(licenses_root, 'empty')
    if(os.path.isfile(packages_file)):
      logging.info(f"    > found package list, copying")
      pkg_file_dest = f"packages.{lic_type}.txt"
      lic_file_dest = f"licenses.{lic_type}.txt"
      shutil.copyfile(packages_file, os.path.join(out_dir, pkg_file_dest))
      shutil.copyfile(licenses_file, os.path.join(out_dir, lic_file_dest))
      ret['license_files'].append(lic_file_dest)
      ret['package_lists'].append(pkg_file_dest)
    elif(os.path.isfile(empty_marker)):
      logging.info(f"    > empty marker found at {empty_marker}, skipping")
      continue
    else:
      die("Something's wrong: can't find neither package lists nor " + 
         f"empty marker in {licenses_root}")

  shutil.rmtree(tmp_dir)
  return(ret)
 

def parse_args():
  argparser = argparse.ArgumentParser(description=description)

  argparser.add_argument("images", metavar="image", nargs='+', default=None,
                         help="Images to process. @ means all last built " + 
                              "ones."
                        )

  argparser.add_argument("-o", "--out-dir", metavar="dir",
                          required=1,
                          dest="out_dir", 
                          help="Output directory")


  argparser.add_argument("-s", "--server", metavar="server",
                          default=None,
                          dest="server", 
                          help="Docker server to use (defaults to environment)")

  argparser.add_argument("--ssh", 
                          default=False, action='store_true',
                          dest="ssh", 
                          help="Use SSH to connect to Docker"
                        )

 

  global args

  args = argparser.parse_args()

def init_docker_conn():
  server = None

  if(args.ssh):
    logging.info("Using SSH to connect to server")
    server = f"ssh://{args.server}"
  else:
    logging.info("Using TCP to connect to server")
    server = args.server

  conn = nvidia.docker.Docker(server=server)
  return(conn)

################################################################################
## Execute
################################################################################

init()
main()
