[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "Replicator Grasping Pipeline UI"
description = "UI for the synthetic data generation workflow for grasping scenarios"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.replicator.grasping.ui"
keywords = ["isaac", "grasping", "replicator", "sdg"]
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"

[dependencies]
"isaacsim.gui.components" = {}
"isaacsim.replicator.grasping" = {}
"isaacsim.util.debug_draw" = {}
"omni.kit.menu.utils" = {}
"omni.ui" = {}
"omni.usd" = {}

[[python.module]]
name = "isaacsim.replicator.grasping.ui"

[[test]]
dependencies = []
