[package]
version = "2.1.9"
category = "Simulation"
title = "Robot Assembler"
description = "Alpha version of Robot Assembler Extension: Assemble multiple Articulations into a single robot"
authors = ["hmazhar@nvidia.com", "qwan@nvidia.com", "arudich@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.robot_setup.assembler"
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.core.deprecation_manager" = {}
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "isaacsim.robot_setup.assembler"

[[test]]

dependencies = [
]

args = [
'--/persistent/isaac/asset_root/default = "omniverse://isaac-dev.ov.nvidia.com"',
]

[[test]]
name = "startup"
args = [
]