// Generated by gencpp from file isaac_ros_messages/BoundingBox3DArray.msg
// DO NOT EDIT!


#ifndef ISAAC_ROS_MESSAGES_MESSAGE_BOUNDINGBOX3DARRAY_H
#define ISAAC_ROS_MESSAGES_MESSAGE_BOUNDINGBOX3DARRAY_H


#include <isaac_ros_messages/BoundingBox3D.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>
#include <std_msgs/Header.h>

#include <map>
#include <string>
#include <vector>

namespace isaac_ros_messages
{
template <class ContainerAllocator>
struct BoundingBox3DArray_
{
    typedef BoundingBox3DArray_<ContainerAllocator> Type;

    BoundingBox3DArray_() : header(), bboxes()
    {
    }
    BoundingBox3DArray_(const ContainerAllocator& _alloc) : header(_alloc), bboxes(_alloc)
    {
        (void)_alloc;
    }


    typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
    _header_type header;

    typedef std::vector<
        ::isaac_ros_messages::BoundingBox3D_<ContainerAllocator>,
        typename ContainerAllocator::template rebind<::isaac_ros_messages::BoundingBox3D_<ContainerAllocator>>::other>
        _bboxes_type;
    _bboxes_type bboxes;


    typedef boost::shared_ptr<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox3DArray_

typedef ::isaac_ros_messages::BoundingBox3DArray_<std::allocator<void>> BoundingBox3DArray;

typedef boost::shared_ptr<::isaac_ros_messages::BoundingBox3DArray> BoundingBox3DArrayPtr;
typedef boost::shared_ptr<::isaac_ros_messages::BoundingBox3DArray const> BoundingBox3DArrayConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>>::stream(s, "", v);
    return s;
}


template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator2>& rhs)
{
    return lhs.header == rhs.header && lhs.bboxes == rhs.bboxes;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator2>& rhs)
{
    return !(lhs == rhs);
}


} // namespace isaac_ros_messages

namespace ros
{
namespace message_traits
{


template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator> const> : TrueType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>>
{
    static const char* value()
    {
        return "feb987c199998ee8f8985d7edd01c88f";
    }

    static const char* value(const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0xfeb987c199998ee8ULL;
    static const uint64_t static_value2 = 0xf8985d7edd01c88fULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_ros_messages/BoundingBox3DArray";
    }

    static const char* value(const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>>
{
    static const char* value()
    {
        return "std_msgs/Header header\n"
               "BoundingBox3D[] bboxes\n"
               "\n"
               "================================================================================\n"
               "MSG: std_msgs/Header\n"
               "# Standard metadata for higher-level stamped data types.\n"
               "# This is generally used to communicate timestamped data \n"
               "# in a particular coordinate frame.\n"
               "# \n"
               "# sequence ID: consecutively increasing ID \n"
               "uint32 seq\n"
               "#Two-integer timestamp that is expressed as:\n"
               "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
               "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
               "# time-handling sugar is provided by the client library\n"
               "time stamp\n"
               "#Frame this data is associated with\n"
               "string frame_id\n"
               "\n"
               "================================================================================\n"
               "MSG: isaac_ros_messages/BoundingBox3D\n"
               "# A 3D bounding box that can be positioned and rotated about its center (6 DOF)\n"
               "# Dimensions of this box are in meters, and as such, it may be migrated to\n"
               "#   another package, such as geometry_msgs, in the future.\n"
               "\n"
               "#\n"
               "string name\n"
               "float64 confidence\n"
               "# The 3D position and orientation of the bounding box center\n"
               "geometry_msgs/Pose center\n"
               "\n"
               "# The size of the bounding box, in meters, surrounding the object's center\n"
               "#   pose.\n"
               "geometry_msgs/Vector3 size\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Pose\n"
               "# A representation of pose in free space, composed of position and orientation. \n"
               "Point position\n"
               "Quaternion orientation\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Point\n"
               "# This contains the position of a point in free space\n"
               "float64 x\n"
               "float64 y\n"
               "float64 z\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Quaternion\n"
               "# This represents an orientation in free space in quaternion form.\n"
               "\n"
               "float64 x\n"
               "float64 y\n"
               "float64 z\n"
               "float64 w\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Vector3\n"
               "# This represents a vector in free space. \n"
               "# It is only meant to represent a direction. Therefore, it does not\n"
               "# make sense to apply a translation to it (e.g., when applying a \n"
               "# generic rigid transformation to a Vector3, tf2 will only apply the\n"
               "# rotation). If you want your data to be translatable too, use the\n"
               "# geometry_msgs/Point message instead.\n"
               "\n"
               "float64 x\n"
               "float64 y\n"
               "float64 z\n";
    }

    static const char* value(const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.header);
        stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct BoundingBox3DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream& s,
                       const std::string& indent,
                       const ::isaac_ros_messages::BoundingBox3DArray_<ContainerAllocator>& v)
    {
        s << indent << "header: ";
        s << std::endl;
        Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
        s << indent << "bboxes[]" << std::endl;
        for (size_t i = 0; i < v.bboxes.size(); ++i)
        {
            s << indent << "  bboxes[" << i << "]: ";
            s << std::endl;
            s << indent;
            Printer<::isaac_ros_messages::BoundingBox3D_<ContainerAllocator>>::stream(s, indent + "    ", v.bboxes[i]);
        }
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_ROS_MESSAGES_MESSAGE_BOUNDINGBOX3DARRAY_H
