// Generated by gencpp from file isaac_ros_messages/IsaacPoseResponse.msg
// DO NOT EDIT!


#ifndef ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSERESPONSE_H
#define ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSERESPONSE_H


#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>

#include <map>
#include <string>
#include <vector>


namespace isaac_ros_messages
{
template <class ContainerAllocator>
struct IsaacPoseResponse_
{
    typedef IsaacPoseResponse_<ContainerAllocator> Type;

    IsaacPoseResponse_()
    {
    }
    IsaacPoseResponse_(const ContainerAllocator& _alloc)
    {
        (void)_alloc;
    }


    typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacPoseResponse_

typedef ::isaac_ros_messages::IsaacPoseResponse_<std::allocator<void>> IsaacPoseResponse;

typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseResponse> IsaacPoseResponsePtr;
typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseResponse const> IsaacPoseResponseConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>>::stream(s, "", v);
    return s;
}


} // namespace isaac_ros_messages

namespace ros
{
namespace message_traits
{


template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator> const> : FalseType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>>
{
    static const char* value()
    {
        return "d41d8cd98f00b204e9800998ecf8427e";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
    static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_ros_messages/IsaacPoseResponse";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>>
{
    static const char* value()
    {
        return "\n";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream&, T)
    {
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream&, const std::string&, const ::isaac_ros_messages::IsaacPoseResponse_<ContainerAllocator>&)
    {
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSERESPONSE_H
