// Generated by gencpp from file isaac_ros_messages/IsaacJSONState.msg
// DO NOT EDIT!


#ifndef ISAAC_ROS_MESSAGES_MESSAGE_ISAACJSONSTATE_H
#define ISAAC_ROS_MESSAGES_MESSAGE_ISAACJSONSTATE_H


#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>
#include <std_msgs/Header.h>

#include <map>
#include <string>
#include <vector>

namespace isaac_ros_messages
{
template <class ContainerAllocator>
struct IsaacJSONState_
{
    typedef IsaacJSONState_<ContainerAllocator> Type;

    IsaacJSONState_() : header(), json()
    {
    }
    IsaacJSONState_(const ContainerAllocator& _alloc) : header(_alloc), json(_alloc)
    {
        (void)_alloc;
    }


    typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
    _header_type header;

    typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other> _json_type;
    _json_type json;


    typedef boost::shared_ptr<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacJSONState_

typedef ::isaac_ros_messages::IsaacJSONState_<std::allocator<void>> IsaacJSONState;

typedef boost::shared_ptr<::isaac_ros_messages::IsaacJSONState> IsaacJSONStatePtr;
typedef boost::shared_ptr<::isaac_ros_messages::IsaacJSONState const> IsaacJSONStateConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>>::stream(s, "", v);
    return s;
}


template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator2>& rhs)
{
    return lhs.header == rhs.header && lhs.json == rhs.json;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator2>& rhs)
{
    return !(lhs == rhs);
}


} // namespace isaac_ros_messages

namespace ros
{
namespace message_traits
{


template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator> const> : TrueType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>>
{
    static const char* value()
    {
        return "bba21b380002512f5222266cbd4dc034";
    }

    static const char* value(const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0xbba21b380002512fULL;
    static const uint64_t static_value2 = 0x5222266cbd4dc034ULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_ros_messages/IsaacJSONState";
    }

    static const char* value(const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>>
{
    static const char* value()
    {
        return "std_msgs/Header header\n"
               "string json\n"
               "\n"
               "================================================================================\n"
               "MSG: std_msgs/Header\n"
               "# Standard metadata for higher-level stamped data types.\n"
               "# This is generally used to communicate timestamped data \n"
               "# in a particular coordinate frame.\n"
               "# \n"
               "# sequence ID: consecutively increasing ID \n"
               "uint32 seq\n"
               "#Two-integer timestamp that is expressed as:\n"
               "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
               "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
               "# time-handling sugar is provided by the client library\n"
               "time stamp\n"
               "#Frame this data is associated with\n"
               "string frame_id\n";
    }

    static const char* value(const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.header);
        stream.next(m.json);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacJSONState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream& s,
                       const std::string& indent,
                       const ::isaac_ros_messages::IsaacJSONState_<ContainerAllocator>& v)
    {
        s << indent << "header: ";
        s << std::endl;
        Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
        s << indent << "json: ";
        Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other>>::stream(
            s, indent + "  ", v.json);
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_ROS_MESSAGES_MESSAGE_ISAACJSONSTATE_H
