// Copyright (c) 2020-2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// Generated by gencpp from file isaac_ros_messages/IsaacPoseRequest.msg
// DO NOT EDIT!


#ifndef ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSEREQUEST_H
#define ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSEREQUEST_H


#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Vector3.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>
#include <std_msgs/Header.h>

#include <map>
#include <string>
#include <vector>

namespace isaac_ros_messages
{
template <class ContainerAllocator>
struct IsaacPoseRequest_
{
    typedef IsaacPoseRequest_<ContainerAllocator> Type;

    IsaacPoseRequest_() : header(), names(), poses(), velocities(), scales()
    {
    }
    IsaacPoseRequest_(const ContainerAllocator& _alloc)
        : header(_alloc), names(_alloc), poses(_alloc), velocities(_alloc), scales(_alloc)
    {
        (void)_alloc;
    }


    typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
    _header_type header;

    typedef std::vector<
        std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other>,
        typename ContainerAllocator::template rebind<
            std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other>>::other>
        _names_type;
    _names_type names;

    typedef std::vector<::geometry_msgs::Pose_<ContainerAllocator>,
                        typename ContainerAllocator::template rebind<::geometry_msgs::Pose_<ContainerAllocator>>::other>
        _poses_type;
    _poses_type poses;

    typedef std::vector<::geometry_msgs::Twist_<ContainerAllocator>,
                        typename ContainerAllocator::template rebind<::geometry_msgs::Twist_<ContainerAllocator>>::other>
        _velocities_type;
    _velocities_type velocities;

    typedef std::vector<::geometry_msgs::Vector3_<ContainerAllocator>,
                        typename ContainerAllocator::template rebind<::geometry_msgs::Vector3_<ContainerAllocator>>::other>
        _scales_type;
    _scales_type scales;


    typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacPoseRequest_

typedef ::isaac_ros_messages::IsaacPoseRequest_<std::allocator<void>> IsaacPoseRequest;

typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseRequest> IsaacPoseRequestPtr;
typedef boost::shared_ptr<::isaac_ros_messages::IsaacPoseRequest const> IsaacPoseRequestConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>>::stream(s, "", v);
    return s;
}


template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator2>& rhs)
{
    return lhs.header == rhs.header && lhs.names == rhs.names && lhs.poses == rhs.poses &&
           lhs.velocities == rhs.velocities && lhs.scales == rhs.scales;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator2>& rhs)
{
    return !(lhs == rhs);
}


} // namespace isaac_ros_messages

namespace ros
{
namespace message_traits
{


template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator> const> : TrueType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>>
{
    static const char* value()
    {
        return "8511adbe7667fc4c8d731c0a60fa04fa";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0x8511adbe7667fc4cULL;
    static const uint64_t static_value2 = 0x8d731c0a60fa04faULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_ros_messages/IsaacPoseRequest";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>>
{
    static const char* value()
    {
        return "std_msgs/Header header\n"
               "string[] names\n"
               "geometry_msgs/Pose[] poses\n"
               "geometry_msgs/Twist[] velocities\n"
               "geometry_msgs/Vector3[] scales\n"
               "\n"
               "================================================================================\n"
               "MSG: std_msgs/Header\n"
               "# Standard metadata for higher-level stamped data types.\n"
               "# This is generally used to communicate timestamped data \n"
               "# in a particular coordinate frame.\n"
               "# \n"
               "# sequence ID: consecutively increasing ID \n"
               "uint32 seq\n"
               "#Two-integer timestamp that is expressed as:\n"
               "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
               "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
               "# time-handling sugar is provided by the client library\n"
               "time stamp\n"
               "#Frame this data is associated with\n"
               "string frame_id\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Pose\n"
               "# A representation of pose in free space, composed of position and orientation. \n"
               "Point position\n"
               "Quaternion orientation\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Point\n"
               "# This contains the position of a point in free space\n"
               "float64 x\n"
               "float64 y\n"
               "float64 z\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Quaternion\n"
               "# This represents an orientation in free space in quaternion form.\n"
               "\n"
               "float64 x\n"
               "float64 y\n"
               "float64 z\n"
               "float64 w\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Twist\n"
               "# This expresses velocity in free space broken into its linear and angular parts.\n"
               "Vector3  linear\n"
               "Vector3  angular\n"
               "\n"
               "================================================================================\n"
               "MSG: geometry_msgs/Vector3\n"
               "# This represents a vector in free space. \n"
               "# It is only meant to represent a direction. Therefore, it does not\n"
               "# make sense to apply a translation to it (e.g., when applying a \n"
               "# generic rigid transformation to a Vector3, tf2 will only apply the\n"
               "# rotation). If you want your data to be translatable too, use the\n"
               "# geometry_msgs/Point message instead.\n"
               "\n"
               "float64 x\n"
               "float64 y\n"
               "float64 z\n";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.header);
        stream.next(m.names);
        stream.next(m.poses);
        stream.next(m.velocities);
        stream.next(m.scales);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream& s,
                       const std::string& indent,
                       const ::isaac_ros_messages::IsaacPoseRequest_<ContainerAllocator>& v)
    {
        s << indent << "header: ";
        s << std::endl;
        Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
        s << indent << "names[]" << std::endl;
        for (size_t i = 0; i < v.names.size(); ++i)
        {
            s << indent << "  names[" << i << "]: ";
            Printer<std::basic_string<char, std::char_traits<char>,
                                      typename ContainerAllocator::template rebind<char>::other>>::stream(s,
                                                                                                          indent + "  ",
                                                                                                          v.names[i]);
        }
        s << indent << "poses[]" << std::endl;
        for (size_t i = 0; i < v.poses.size(); ++i)
        {
            s << indent << "  poses[" << i << "]: ";
            s << std::endl;
            s << indent;
            Printer<::geometry_msgs::Pose_<ContainerAllocator>>::stream(s, indent + "    ", v.poses[i]);
        }
        s << indent << "velocities[]" << std::endl;
        for (size_t i = 0; i < v.velocities.size(); ++i)
        {
            s << indent << "  velocities[" << i << "]: ";
            s << std::endl;
            s << indent;
            Printer<::geometry_msgs::Twist_<ContainerAllocator>>::stream(s, indent + "    ", v.velocities[i]);
        }
        s << indent << "scales[]" << std::endl;
        for (size_t i = 0; i < v.scales.size(); ++i)
        {
            s << indent << "  scales[" << i << "]: ";
            s << std::endl;
            s << indent;
            Printer<::geometry_msgs::Vector3_<ContainerAllocator>>::stream(s, indent + "    ", v.scales[i]);
        }
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSEREQUEST_H
