// Copyright (c) 2021-2023, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//
// Generated by gencpp from file isaac_ros_messages/IsaacPose.msg
// DO NOT EDIT!


#ifndef ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSE_H
#define ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSE_H

#include <isaac_ros_messages/IsaacPoseRequest.h>
#include <isaac_ros_messages/IsaacPoseResponse.h>
#include <ros/service_traits.h>


namespace isaac_ros_messages
{

struct IsaacPose
{

    typedef IsaacPoseRequest Request;
    typedef IsaacPoseResponse Response;
    Request request;
    Response response;

    typedef Request RequestType;
    typedef Response ResponseType;

}; // struct IsaacPose
} // namespace isaac_ros_messages


namespace ros
{
namespace service_traits
{


template <>
struct MD5Sum<::isaac_ros_messages::IsaacPose>
{
    static const char* value()
    {
        return "8511adbe7667fc4c8d731c0a60fa04fa";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPose&)
    {
        return value();
    }
};

template <>
struct DataType<::isaac_ros_messages::IsaacPose>
{
    static const char* value()
    {
        return "isaac_ros_messages/IsaacPose";
    }

    static const char* value(const ::isaac_ros_messages::IsaacPose&)
    {
        return value();
    }
};


// service_traits::MD5Sum< ::isaac_ros_messages::IsaacPoseRequest> should match
// service_traits::MD5Sum< ::isaac_ros_messages::IsaacPose >
template <>
struct MD5Sum<::isaac_ros_messages::IsaacPoseRequest>
{
    static const char* value()
    {
        return MD5Sum<::isaac_ros_messages::IsaacPose>::value();
    }
    static const char* value(const ::isaac_ros_messages::IsaacPoseRequest&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_ros_messages::IsaacPoseRequest> should match
// service_traits::DataType< ::isaac_ros_messages::IsaacPose >
template <>
struct DataType<::isaac_ros_messages::IsaacPoseRequest>
{
    static const char* value()
    {
        return DataType<::isaac_ros_messages::IsaacPose>::value();
    }
    static const char* value(const ::isaac_ros_messages::IsaacPoseRequest&)
    {
        return value();
    }
};

// service_traits::MD5Sum< ::isaac_ros_messages::IsaacPoseResponse> should match
// service_traits::MD5Sum< ::isaac_ros_messages::IsaacPose >
template <>
struct MD5Sum<::isaac_ros_messages::IsaacPoseResponse>
{
    static const char* value()
    {
        return MD5Sum<::isaac_ros_messages::IsaacPose>::value();
    }
    static const char* value(const ::isaac_ros_messages::IsaacPoseResponse&)
    {
        return value();
    }
};

// service_traits::DataType< ::isaac_ros_messages::IsaacPoseResponse> should match
// service_traits::DataType< ::isaac_ros_messages::IsaacPose >
template <>
struct DataType<::isaac_ros_messages::IsaacPoseResponse>
{
    static const char* value()
    {
        return DataType<::isaac_ros_messages::IsaacPose>::value();
    }
    static const char* value(const ::isaac_ros_messages::IsaacPoseResponse&)
    {
        return value();
    }
};

} // namespace service_traits
} // namespace ros

#endif // ISAAC_ROS_MESSAGES_MESSAGE_ISAACPOSE_H
