// Generated by gencpp from file isaac_ros_messages/IsaacBoundingBoxArray.msg
// DO NOT EDIT!


#ifndef ISAAC_ROS_MESSAGES_MESSAGE_ISAACBOUNDINGBOXARRAY_H
#define ISAAC_ROS_MESSAGES_MESSAGE_ISAACBOUNDINGBOXARRAY_H


#include <isaac_ros_messages/IsaacBoundingBox.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>
#include <std_msgs/Header.h>

#include <map>
#include <string>
#include <vector>

namespace isaac_ros_messages
{
template <class ContainerAllocator>
struct IsaacBoundingBoxArray_
{
    typedef IsaacBoundingBoxArray_<ContainerAllocator> Type;

    IsaacBoundingBoxArray_() : header(), bboxes()
    {
    }
    IsaacBoundingBoxArray_(const ContainerAllocator& _alloc) : header(_alloc), bboxes(_alloc)
    {
        (void)_alloc;
    }


    typedef ::std_msgs::Header_<ContainerAllocator> _header_type;
    _header_type header;

    typedef std::vector<
        ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>,
        typename ContainerAllocator::template rebind<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>::other>
        _bboxes_type;
    _bboxes_type bboxes;


    typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacBoundingBoxArray_

typedef ::isaac_ros_messages::IsaacBoundingBoxArray_<std::allocator<void>> IsaacBoundingBoxArray;

typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBoxArray> IsaacBoundingBoxArrayPtr;
typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBoxArray const> IsaacBoundingBoxArrayConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>>::stream(s, "", v);
    return s;
}


template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator2>& rhs)
{
    return lhs.header == rhs.header && lhs.bboxes == rhs.bboxes;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator2>& rhs)
{
    return !(lhs == rhs);
}


} // namespace isaac_ros_messages

namespace ros
{
namespace message_traits
{


template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator> const> : TrueType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>>
{
    static const char* value()
    {
        return "029febdb0406c65cd1e381761a8dd2b9";
    }

    static const char* value(const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0x029febdb0406c65cULL;
    static const uint64_t static_value2 = 0xd1e381761a8dd2b9ULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_ros_messages/IsaacBoundingBoxArray";
    }

    static const char* value(const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>>
{
    static const char* value()
    {
        return "std_msgs/Header header\n"
               "IsaacBoundingBox[] bboxes\n"
               "\n"
               "================================================================================\n"
               "MSG: std_msgs/Header\n"
               "# Standard metadata for higher-level stamped data types.\n"
               "# This is generally used to communicate timestamped data \n"
               "# in a particular coordinate frame.\n"
               "# \n"
               "# sequence ID: consecutively increasing ID \n"
               "uint32 seq\n"
               "#Two-integer timestamp that is expressed as:\n"
               "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
               "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
               "# time-handling sugar is provided by the client library\n"
               "time stamp\n"
               "#Frame this data is associated with\n"
               "string frame_id\n"
               "\n"
               "================================================================================\n"
               "MSG: isaac_ros_messages/IsaacBoundingBox\n"
               "string name\n"
               "float64 confidence\n"
               "int64 xmin\n"
               "int64 ymin\n"
               "int64 xmax\n"
               "int64 ymax\n";
    }

    static const char* value(const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.header);
        stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacBoundingBoxArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream& s,
                       const std::string& indent,
                       const ::isaac_ros_messages::IsaacBoundingBoxArray_<ContainerAllocator>& v)
    {
        s << indent << "header: ";
        s << std::endl;
        Printer<::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
        s << indent << "bboxes[]" << std::endl;
        for (size_t i = 0; i < v.bboxes.size(); ++i)
        {
            s << indent << "  bboxes[" << i << "]: ";
            s << std::endl;
            s << indent;
            Printer<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>::stream(s, indent + "    ", v.bboxes[i]);
        }
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_ROS_MESSAGES_MESSAGE_ISAACBOUNDINGBOXARRAY_H
