// Generated by gencpp from file isaac_ros_messages/IsaacBoundingBox.msg
// DO NOT EDIT!


#ifndef ISAAC_ROS_MESSAGES_MESSAGE_ISAACBOUNDINGBOX_H
#define ISAAC_ROS_MESSAGES_MESSAGE_ISAACBOUNDINGBOX_H


#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>
#include <ros/serialization.h>
#include <ros/types.h>

#include <map>
#include <string>
#include <vector>


namespace isaac_ros_messages
{
template <class ContainerAllocator>
struct IsaacBoundingBox_
{
    typedef IsaacBoundingBox_<ContainerAllocator> Type;

    IsaacBoundingBox_() : name(), confidence(0.0), xmin(0), ymin(0), xmax(0), ymax(0)
    {
    }
    IsaacBoundingBox_(const ContainerAllocator& _alloc)
        : name(_alloc), confidence(0.0), xmin(0), ymin(0), xmax(0), ymax(0)
    {
        (void)_alloc;
    }


    typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other> _name_type;
    _name_type name;

    typedef double _confidence_type;
    _confidence_type confidence;

    typedef int64_t _xmin_type;
    _xmin_type xmin;

    typedef int64_t _ymin_type;
    _ymin_type ymin;

    typedef int64_t _xmax_type;
    _xmax_type xmax;

    typedef int64_t _ymax_type;
    _ymax_type ymax;


    typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>> Ptr;
    typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct IsaacBoundingBox_

typedef ::isaac_ros_messages::IsaacBoundingBox_<std::allocator<void>> IsaacBoundingBox;

typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBox> IsaacBoundingBoxPtr;
typedef boost::shared_ptr<::isaac_ros_messages::IsaacBoundingBox const> IsaacBoundingBoxConstPtr;

// constants requiring out of line definition


template <typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>& v)
{
    ros::message_operations::Printer<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>::stream(s, "", v);
    return s;
}


template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator2>& rhs)
{
    return lhs.name == rhs.name && lhs.confidence == rhs.confidence && lhs.xmin == rhs.xmin && lhs.ymin == rhs.ymin &&
           lhs.xmax == rhs.xmax && lhs.ymax == rhs.ymax;
}

template <typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator1>& lhs,
                const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator2>& rhs)
{
    return !(lhs == rhs);
}


} // namespace isaac_ros_messages

namespace ros
{
namespace message_traits
{


template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct IsFixedSize<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator> const> : FalseType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>> : TrueType
{
};

template <class ContainerAllocator>
struct IsMessage<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator> const> : TrueType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>> : FalseType
{
};

template <class ContainerAllocator>
struct HasHeader<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator> const> : FalseType
{
};


template <class ContainerAllocator>
struct MD5Sum<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>
{
    static const char* value()
    {
        return "35aed43c98414d6d8e8bc8fbc4048d28";
    }

    static const char* value(const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>&)
    {
        return value();
    }
    static const uint64_t static_value1 = 0x35aed43c98414d6dULL;
    static const uint64_t static_value2 = 0x8e8bc8fbc4048d28ULL;
};

template <class ContainerAllocator>
struct DataType<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>
{
    static const char* value()
    {
        return "isaac_ros_messages/IsaacBoundingBox";
    }

    static const char* value(const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>&)
    {
        return value();
    }
};

template <class ContainerAllocator>
struct Definition<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>
{
    static const char* value()
    {
        return "string name\n"
               "float64 confidence\n"
               "int64 xmin\n"
               "int64 ymin\n"
               "int64 xmax\n"
               "int64 ymax\n";
    }

    static const char* value(const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>&)
    {
        return value();
    }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template <class ContainerAllocator>
struct Serializer<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>
{
    template <typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
        stream.next(m.name);
        stream.next(m.confidence);
        stream.next(m.xmin);
        stream.next(m.ymin);
        stream.next(m.xmax);
        stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct IsaacBoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template <class ContainerAllocator>
struct Printer<::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>>
{
    template <typename Stream>
    static void stream(Stream& s,
                       const std::string& indent,
                       const ::isaac_ros_messages::IsaacBoundingBox_<ContainerAllocator>& v)
    {
        s << indent << "name: ";
        Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other>>::stream(
            s, indent + "  ", v.name);
        s << indent << "confidence: ";
        Printer<double>::stream(s, indent + "  ", v.confidence);
        s << indent << "xmin: ";
        Printer<int64_t>::stream(s, indent + "  ", v.xmin);
        s << indent << "ymin: ";
        Printer<int64_t>::stream(s, indent + "  ", v.ymin);
        s << indent << "xmax: ";
        Printer<int64_t>::stream(s, indent + "  ", v.xmax);
        s << indent << "ymax: ";
        Printer<int64_t>::stream(s, indent + "  ", v.ymax);
    }
};

} // namespace message_operations
} // namespace ros

#endif // ISAAC_ROS_MESSAGES_MESSAGE_ISAACBOUNDINGBOX_H
