isaacsim.replicator.agent:
  version: 0.5.0
  global:
    seed: 123456
    simulation_length: 1800
  sensor:
    camera_num: 4
    lidar_num: 0
  character:
    asset_path:
    command_file: default_command.txt
    filters:
    num: 8
  robot:
    command_file: default_robot_command.txt
    nova_carter_num: 0
    transporter_num: 0
    write_data: false
  replicator:
    writer: IRABasicWriter
    parameters:
      object_info_bounding_box_2d_tight: false
      object_info_bounding_box_2d_loose: false
      object_info_bounding_box_3d: false
      agent_info_skeleton_data: false
      semantic_filter_predicate: class:character|robot;id:*
      rgb: true
      camera_params: true