[cloner]
reloadable = true
order = 0

[package]
version = "0.4.1"
category = "Simulation"
title = "Isaac Sim Cloner"
description = "Cloner"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.cloner"
keywords = ["isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.usd" = {}
"omni.usd.libs" = {}
"omni.physx" = {}

[[python.module]]
name = "omni.isaac.cloner"