// Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
//
// NVIDIA CORPORATION and its licensors retain all intellectual property
// and proprietary rights in and to this software, related documentation
// and any modifications thereto. Any use, reproduction, disclosure or
// distribution of this software and related documentation without an express
// license agreement from NVIDIA CORPORATION is strictly prohibited.
//

// ============================================================
// Note the name of the generated include file, taken from the name of the file with "Database.h" appended.
// The build system should have added the include path that picks this file up directly.
#include <OgnROS1EmptyDatabase.h>

// ============================================================
// The class name should match the file name to avoid confusion as the file name will be used
// as a base for the names in the generated interface.
//
class OgnROS1Empty
{
public:
    // Called once when the OG node is created
    static void initialize(const GraphContextObj& contextObj, const NodeObj& nodeObj)
    {
        // Get access to any private variables using sInternalState
        auto& state = OgnROS1EmptyDatabase::sInternalState<OgnROS1Empty>(nodeObj);
        state.mInitialized = false;
    }

    // ------------------------------------------------------------
    // Note the name of the generated computation database, the same as the name of the include file,
    // auto-generated by appending "Database" to the file name.
    //
    static bool compute(OgnROS1EmptyDatabase& db)
    {
        // Get access to any private variables using sInternalState
        auto& state = db.internalState<OgnROS1Empty>();

        // This node correctly does nothing, but it must return true to indicate a successful compute.
        //
        return true;
    }

    // Called when we release the node, do any cleanup here
    static void release(const NodeObj& nodeObj)
    {
    }

private:
    bool mInitialized = false;
};

// ============================================================
// Now that the node has been defined it can be registered for use. This registration takes care of
// automatic registration of the node when the extension loads and deregistration when it unloads.
REGISTER_OGN_NODE()
