[filtering]
nofollow=
  # cross-portal references
  ^https:\/\/docs.omniverse.nvidia.com\/app_audio2face\/(?!app_audio2face)
  ^https:\/\/docs.omniverse.nvidia.com\/app_code\/(?!app_code)
  ^https:\/\/docs.omniverse.nvidia.com\/app_create\/(?!app_create)
  ^https:\/\/docs.omniverse.nvidia.com\/app_farm\/(?!app_farm)
  ^https:\/\/docs.omniverse.nvidia.com\/app_isaacsim\/(?!app_isaacsim)
  ^https:\/\/docs.omniverse.nvidia.com\/app_kaolin\/(?!app_kaolin)
  ^https:\/\/docs.omniverse.nvidia.com\/app_machinima\/(?!app_machinima)
  ^https:\/\/docs.omniverse.nvidia.com\/app_navigator\/(?!app_navigator)
  ^https:\/\/docs.omniverse.nvidia.com\/app_omniverse-xr\/(?!app_omniverse-xr)
  ^https:\/\/docs.omniverse.nvidia.com\/app_scene-optimizer\/(?!app_scene-optimizer)
  ^https:\/\/docs.omniverse.nvidia.com\/app_showroom\/(?!app_showroom)
  ^https:\/\/docs.omniverse.nvidia.com\/app_streaming-client\/(?!app_streaming-client)
  ^https:\/\/docs.omniverse.nvidia.com\/app_usdview\/(?!app_usdview)
  ^https:\/\/docs.omniverse.nvidia.com\/app_view\/(?!app_view)
  ^https:\/\/docs.omniverse.nvidia.com\/con_connect\/(?!con_connect)
  ^https:\/\/docs.omniverse.nvidia.com\/plat_omniverse\/(?!plat_omniverse)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_deployment\/(?!prod_deployment)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_digital-twins\/(?!prod_digital-twins)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_enterprise\/(?!prod_enterprise)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_extensions\/(?!prod_extensions)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_install-guide\/(?!prod_install-guide)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_kit\/(?!prod_kit)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_launcher\/(?!prod_launcher)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_materials-and-rendering\/(?!prod_materials-and-rendering)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_nucleus\/(?!prod_nucleus)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_services\/(?!prod_services)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_simready\/(?!prod_simready)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_usd\/(?!prod_usd)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_utilities\/(?!prod_utilities)
  ^https:\/\/docs.omniverse.nvidia.com\/prod_workflows\/(?!prod_workflows)
ignore=
  content/\d+$
  \.js$
  \.ico$
  \.png$
  \.(jpg|jpeg)$
  \.download$
  \.s?css$
  \/js$
  \.txt$
  \.usd$
checkextern=1

[output]
ignoreerrors=
  ^omniverse://
  ^omniverse-launcher://
  localhost
  host:port
  @
fileoutput=csv

[csv]
separator=,
