[core]
reloadable = true
order = 0

[package]
version = "0.1.1"
category = "Simulation"
title = "Isaac Sim RTX Sensor Simulation UI Components"
description = "Provides UI components for Isaac Sim RTX-based sensor simulation, eg. menu options."
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.sensors.rtx.ui"
keywords = ["isaac", "physics", "robotics", "ui"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.gui.components" = {}
"isaacsim.sensors.rtx" = {}

[[python.module]]
name = "isaacsim.sensors.rtx.ui"

[[test]]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
'--/persistent/isaac/asset_root/default = "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5"',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
    '--/persistent/isaac/asset_root/default = "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5"',
]