[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Robotics"
title = "Omni Isaac Cortex"
description = "Decision framework and organizational structures for using Omni Isaac Sim as the mind of a physical robot."
authors = ["Nathan Ratliff"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.cortex"
keywords = ["isaac", "robotics", "collaborative robotics", "digital twins"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.cortex.framework" = {}

[[python.module]]
name = "omni.isaac.cortex"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.cortex.framework."
