[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Utility"
title = "Jupyter notebook integration"
description = "Jupyter notebook version of Omniverse's script editor"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.jupyter_notebook"
keywords = ["isaac", "python", "jupyter", "notebook"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.code_editor.jupyter" = {}

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.code_editor.jupyter."
