#!/bin/bash
set -e

SCRIPT_DIR=$(dirname ${BASH_SOURCE})
# first argument to script must be the folder to run this in
pushd $1

source setup_python_env.sh

IFS=':' read -r -a array <<< "$PYTHONPATH"

EXTRAPATHS=""
for element in "${array[@]}"
do
# check for any developer string, and if its an empty string
    if [[ "$element" != *"packman-common"* && $element ]]; then
        EXTRAPATHS+="\t\t\"$element\",\n"
    fi
done

sed -i "s|AUTOGENERATED_EXTRAPATHS|$EXTRAPATHS|g" ".vscode/settings.json"
popd