#!/bin/bash

set -e

error_exit()
{
    echo "There was an error running python"
    exit 1
}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# MY_DIR="$(realpath -s "$SCRIPT_DIR")"

# Setup python env from generated file (generated by tools/repoman/build.py)
export EXP_PATH=$SCRIPT_DIR/apps
source ${SCRIPT_DIR}/setup_python_env.sh

# By default use our python, but allow overriding it by checking if PYTHONEXE env var is defined:
python_exe=${PYTHONEXE:-"${SCRIPT_DIR}/kit/python/bin/python3"}


if ! [[ -z "${CONDA_PREFIX}" ]]; then
  echo "Warning: running in conda env, please deactivate before executing this script"
  echo "If conda is desired please source python_samples/setenv.sh in your python 3.7 conda env and run python normally"
fi

# Check if we are running as root (usually in a docker container)
if ! [[ $EUID -ne 0 ]]; then
# Check to make sure we have an argument before appending --allow-root
  if [ $# -eq 1 ]; then
    echo "running as root"
    args="$args --allow-root"
  fi
fi

# Show icon if not running headless
export RESOURCE_NAME="IsaacSim"

$python_exe $@ $args || error_exit
