[package]
version = "1.0.4"
category = "Simulation"
title = "Lula Test Widget"
description = "Run Simple Tests Using Lula Algorithms"
authors = ["hmazhar@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.lula_test_widget"
keywords = ["isaac", "lula"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.robot_motion.lula_test_widget."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot_motion.lula_test_widget" = {}

[[python.module]]
name = "omni.isaac.lula_test_widget"