[core]
reloadable = true
order = 0

[package]
version = "0.1.6"
category = "Simulation"
title = "Articulation Inspector"
description = "This extension can inspect and modify the properties of an articulation."
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/omni.isaac.articulation_inspector"
keywords = ["isaac", "physics", "analyze", "inspect"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.physx" = {}
"omni.isaac.core" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.ui" = {}

[[python.module]]
name = "omni.isaac.articulation_inspector"
