[package]
version = "0.1.2"
category = "Simulation"
title = "Isaac Sim Core (Materials)"
description = "The Core Materials extension provides a set of APIs to create and/or wrap one or more USD materials in the stage..."
authors = ["hmazhar@nvidia.com","aserranomuno@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.core.materials"
keywords = ["isaacsim", "core", "materials"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.core.experimental.prims" = {}
"isaacsim.core.utils" = {}
"omni.isaac.core_archive" = {}
"omni.kit.material.library" = {}
"omni.kit.usd.mdl" = {}
"omni.warp.core" = {}

[[python.module]]
name = "isaacsim.core.experimental.materials"

# define the Python module for tests
[[python.module]]
name = "isaacsim.core.experimental.materials.tests"

[[test]]
timeout = 1000
dependencies = [
    "omni.physx.commands",
]
pythonTests.include = ["isaacsim.core.experimental.materials.tests.*"]
