[core]
reloadable = true
order = 0

[package]
version = "0.1.6"
category = "Simulation"
title = "Isaac Sim Physics Inspector"
description = "Inspect Physics Objects During Simulation"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/deprecated/omni.isaac.physics_inspector"
keywords = ["isaac", "physics", "inspect",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.0.0. Replaced by Physics Visualization tools"

[dependencies]
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "omni.isaac.physics_inspector"

