[package]
version = "0.2.0"
category = "other"
title = "Content Browser"
description = "Extends the Omniverse content browser with an Isaac Sim collection providing quick access to curated robot models, environments, materials, and sensor assets."
authors = ["qwan@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.gui.content_browser"
keywords = ["browser","assets","content"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.widget.filebrowser" = {}
"omni.kit.window.content_browser" = {}
"omni.kit.window.filepicker" = {}
"omni.simready.content.browser" = {}
"omni.usd.core" = {}

[[python.module]]
name = "isaacsim.gui.content_browser"

# define the Python module for tests
[[python.module]]
name = "isaacsim.gui.content_browser.tests"

[settings]
# time out for resolving the content browser settings
exts."isaacsim.gui.content_browser".timeout = 5
# SimReady assets search locations list. Currently only the first entry is used.
exts."omni.simready.content.browser".content_root_urls = [
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/IsaacReady/isaac_content"
]

# define the folders to be shown in the content browser
exts."isaacsim.gui.content_browser".folders = [
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/Robots",
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/Environments",
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/IsaacLab",
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/Materials",
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/People",
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/Props",
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/Samples",
    "omniverse://isaac-dev.ov.nvidia.com/Isaac/Sensors",
]

[[test]]
name = "startup"
enabled = false

[[test]]
enabled = true

# disable startup test