[package]
version = "0.3.3"
category = "other"
title = "Content Browser"
description = "Extends the Omniverse content browser with an Isaac Sim collection providing quick access to curated robot models, environments, materials, and sensor assets."
authors = ["qwan@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.gui.content_browser"
keywords = ["browser","assets","content"]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.kit.widget.filebrowser" = {}
"omni.kit.window.content_browser" = {}
"omni.kit.window.filepicker" = {}
"omni.simready.content.browser" = {}
"omni.usd.core" = {}

[[python.module]]
name = "isaacsim.gui.content_browser"

# define the Python module for tests
[[python.module]]
name = "isaacsim.gui.content_browser.tests"

[settings]
# Timeout for resolving the content browser settings.
exts."isaacsim.gui.content_browser".timeout = 5
# List of SimReady asset search locations. Currently, only the first entry is used.
exts."omni.simready.content.browser".content_root_urls = [
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/SimReady"
]
# Default content root URL index into the `content_root_urls` list above.
exts."omni.simready.content.browser".default_content_root_url_index = 0

# Specifies the USD search server endpoint.
exts."omni.simready.content.browser".usd_search_endpoint = "https://search.stg.simready.omniverse.nvidia.com/"

# Defines the list of Omniverse folders to be displayed in the content browser.
exts."isaacsim.gui.content_browser".folders = [
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/Robots",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/Environments",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/IsaacLab",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/Materials",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/People",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/Props",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/Samples",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/Sensors",
    "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/6.0/Isaac/SimReady",
]

[[test]]
name = "startup"
enabled = false

[[test]]
enabled = true

# disable startup test
[documentation]
pages = ["docs/Overview.md","docs/SETTINGS.md", "docs/CHANGELOG.md"]
