[core]
reloadable = true
order = 0

[package]
version = "1.0.4"
category = "Simulation"
title = "Camera Inspector"
description = "This extension can inspect and modify the properties of cameras in the scene."
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.util.camera_inspector"
keywords = ["isaac", "camera", "analyze", "inspect", "manager"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
writeTarget.kit = true

[dependencies]
"isaacsim.sensors.camera" = {}
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.deprecation_manager" = {}
"omni.physx" = {}

[[python.module]]
name = "isaacsim.util.camera_inspector"

[[test]]
stdoutFailPatterns.exclude = [
    '*[Error] [carb] [Plugin: omni.sensors.nv.lidar.ext.plugin] Dependency: [omni::sensors::lidar::IGenericModelOutputIOFactory v0.1] failed to be resolved.*', # feature not included in Windows
]
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]