[package]
title = "Isaac Sim Setup Extension"
description = "This Extension does the final setup of the Isaac Sim Apps"
authors = ["Isaac Sim Team"]
toggleable = false

[dependencies]
"omni.usd" = {}
"omni.ui" = { order = -100 }

# Isaac Sim Core Extensions 
"omni.kit.search.service" = {}
"omni.kit.context_menu" = {}
"omni.kit.selection" = {}
"omni.kit.stage_templates" = {}
"omni.kit.window.title" = {}

[[python.module]]
name = "omni.isaac.app.setup"

[[python.module]]
name = "omni.isaac.app.setup.tests"

[settings]
exts."omni.isaac.app.setup".serverCheck = true
