[core]
reloadable = true
order = 0

[package]
version = "4.0.2"
category = "Simulation"
title = "Wheeled Robots"
description = "This extension provides wheeled robot utilities"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.robot.wheeled_robots"
keywords = ["isaac", "physics", "analyze", "tune"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"omni.physx" = {}
"isaacsim.core.api" = {}
"isaacsim.core.nodes" = {}
"isaacsim.gui.components" = {}
"omni.isaac.dynamic_control" = {}
"omni.isaac.core_archive" = {} # scipy, osqp, qdldl
"omni.graph" = {}
"omni.graph.tools" = {}
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "isaacsim.robot.wheeled_robots"

[[python.module]]
name = "isaacsim.robot.wheeled_robots.tests"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[[test]]
timeout = 900
stdoutFailPatterns.exclude = [
    "*Invalid Bundle object in Py_Bundle in getPrimPath*", # Per node tests won't have valid bundles
    "*AttributeError: 'NoneType' object has no attribute 'GetPrimAtPath'*", # For ackermann node omnigraph tests
]

dependencies = [
    "isaacsim.storage.native" # test only
]

args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
'--/persistent/isaac/asset_root/default = "https://omniverse-content-staging.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5"',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]