display_name = "Internal Tools"

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.menu.utils" = {}
# "omni.physx.vehicle" = {}
"omni.isaac.core" = {}

[[python.module]]
name = "omni.isaac.internal_tools"

[[python.module]]
name = "omni.isaac.internal_tools.tests"

# [[python.module]]
# name = "omni.isaac.internal_tools.create_vehicle"
