#!/bin/bash -e

module_relative_filepath=$1
arg=$2

call_dir=`pwd`
module_filepath="$call_dir/$module_relative_filepath"

if [[ -L $0 ]]; then
    # The activate script has been symlinked.
    script_dir="$(dirname "$(readlink -f "$0")")"
else
    # The activate script is being called directly.
    script_dir="$(cd "$(dirname "$0")" && pwd)"
fi
pushd $script_dir/.. > /dev/null

src=$module_filepath
dest=df_behavior_module.py

verbose=false
if $verbose; then
    echo "src: $src"
    echo "dest: $dest"
    echo "call_dir: $call_dir"
    echo "script_dir: $script_dir"
    echo "module_relative_filepath: $module_relative_filepath"
    echo "module_filepath: $module_filepath"
fi

if [[ ! -e $src ]]; then
    echo "ERROR -- cannot find module file at path $src"
    exit 1
fi

if [[ $arg == "latch" ]]; then
    echo "latching $module_file"
    ln -sf $src $dest
else
    echo "activating $module_file"
    if [[ -L $dest ]]; then
        rm $dest
    fi
    cp $src $dest
fi

popd > /dev/null
