[core]
reloadable = true
order = 0

[package]
version = "0.1.1"
category = "Utility"
title = "Deprecation manager"
description = "Manage deprecated OmniGraph nodes and app/extension settings"
authors = ["Isaac Sim Team"]
repository = "https://gitlab-master.nvidia.com/Isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.core.deprecation_manager"
keywords = ["isaacsim", "deprecation", "manager"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.usd" = {}
"omni.graph.core" = { optional = true }
"omni.kit.notification_manager" = { optional = true }

[[python.module]]
name = "isaacsim.core.deprecation_manager"

[settings]
# settings
exts."isaacsim.core.deprecation_manager".settings = [
    # omni.isaac.benchmark.services -> isaacsim.benchmark.services
    { deprecated = "/exts/omni.isaac.benchmark.services/metrics/metrics_output_folder", new = "/exts/isaacsim.benchmark.services/metrics/metrics_output_folder", update = true },
    { deprecated = "/exts/omni.isaac.benchmark.services/metrics/nvdataflow_default_test_suite_name", new = "/exts/isaacsim.benchmark.services/metrics/nvdataflow_default_test_suite_name", update = true },
    { deprecated = "/exts/omni.isaac.benchmark.services/metrics/randomize_filename_prefix", new = "/exts/isaacsim.benchmark.services/metrics/randomize_filename_prefix", update = true },
    # omni.isaac.vscode -> isaacsim.code_editor.vscode
    { deprecated = "/exts/omni.isaac.vscode/host", new = "/exts/isaacsim.code_editor.vscode/host", update = true },
    { deprecated = "/exts/omni.isaac.vscode/port", new = "/exts/isaacsim.code_editor.vscode/port", update = true },
    { deprecated = "/exts/omni.isaac.vscode/carb_logs", new = "/exts/isaacsim.code_editor.vscode/carb_logs", update = true },
    # omni.isaac.jupyter_notebook -> isaacsim.code_editor.jupyter
    { deprecated = "/exts/omni.isaac.jupyter_notebook/host", new = "/exts/isaacsim.code_editor.jupyter/host", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/port", new = "/exts/isaacsim.code_editor.jupyter/port", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/kill_processes_with_port_in_use", new = "/exts/isaacsim.code_editor.jupyter/kill_processes_with_port_in_use", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/classic_notebook_interface", new = "/exts/isaacsim.code_editor.jupyter/classic_notebook_interface", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/notebook_ip", new = "/exts/isaacsim.code_editor.jupyter/notebook_ip", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/notebook_port", new = "/exts/isaacsim.code_editor.jupyter/notebook_port", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/notebook_token", new = "/exts/isaacsim.code_editor.jupyter/notebook_token", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/notebook_dir", new = "/exts/isaacsim.code_editor.jupyter/notebook_dir", update = true },
    { deprecated = "/exts/omni.isaac.jupyter_notebook/command_line_options", new = "/exts/isaacsim.code_editor.jupyter/command_line_options", update = true },
    # omni.isaac.ros2_bridge -> isaacsim.ros2.bridge
    { deprecated = "/exts/omni.isaac.ros2_bridge/ros_distro", new = "/exts/isaacsim.ros2.bridge/ros_distro", update = true },
    { deprecated = "/exts/omni.isaac.ros2_bridge/publish_without_verification", new = "/exts/isaacsim.ros2.bridge/publish_without_verification", update = true },
    { deprecated = "/exts/omni.isaac.ros2_bridge/publish_multithreading_disabled", new = "/exts/isaacsim.ros2.bridge/publish_multithreading_disabled", update = true },
    # omni.isaac.tf_viewer -> isaacsim.ros2.tf_viewer
    { deprecated = "/exts/omni.isaac.tf_viewer/cpp", new = "/exts/isaacsim.ros2.tf_viewer/cpp", update = true },
    { deprecated = "/exts/omni.isaac.asset_browser/folder", new = "/exts/isaacsim.asset.browser/folder", update = true },
    { deprecated = "/exts/omni.isaac.asset_browser/instanceable", new = "/exts/isaacsim.asset.browser/instanceable", update = true },
    { deprecated = "/exts/omni.isaac.asset_browser/data/timeout", new = "/exts/isaacsim.asset.browser/data/timeout", update = true },
    { deprecated = "/exts/omni.isaac.asset_browser/visible_after_startup", new = "/exts/isaacsim.asset.browser/visible_after_startup", update = true },
]
# OmniGraph nodes
exts."isaacsim.core.deprecation_manager".omnigraph = [
    { deprecated = "omni.isaac.debug_draw", new = "isaacsim.util.debug_draw" },
    { deprecated = "omni.isaac.core_nodes.IsaacComputeOdometry", new = "isaacsim.core.nodes.IsaacComputeOdometry" },
    { deprecated = "omni.isaac.core_nodes.IsaacConvertDepthToPointCloud", new = "isaacsim.core.nodes.IsaacConvertDepthToPointCloud" },
    { deprecated = "omni.isaac.core_nodes.IsaacConvertRGBAToRGB", new = "isaacsim.core.nodes.IsaacConvertRGBAToRGB" },
    { deprecated = "omni.isaac.core_nodes.IsaacGenerate32FC1", new = "isaacsim.core.nodes.IsaacGenerate32FC1" },
    { deprecated = "omni.isaac.core_nodes.IsaacPassthroughImagePtr", new = "isaacsim.core.nodes.IsaacPassthroughImagePtr" },
    { deprecated = "omni.isaac.core_nodes.IsaacReadCameraInfo", new = "isaacsim.core.nodes.IsaacReadCameraInfo" },
    { deprecated = "omni.isaac.core_nodes.IsaacReadSimulationTime", new = "isaacsim.core.nodes.IsaacReadSimulationTime" },
    { deprecated = "omni.isaac.core_nodes.IsaacReadSystemTime", new = "isaacsim.core.nodes.IsaacReadSystemTime" },
    { deprecated = "omni.isaac.core_nodes.IsaacReadTimes", new = "isaacsim.core.nodes.IsaacReadTimes" },
    { deprecated = "omni.isaac.core_nodes.IsaacReadWorldPose", new = "isaacsim.core.nodes.IsaacReadWorldPose" },
    { deprecated = "omni.isaac.core_nodes.IsaacRealTimeFactor", new = "isaacsim.core.nodes.IsaacRealTimeFactor" },
    { deprecated = "omni.isaac.core_nodes.OgnIsaacRunOneSimulationFrame", new = "isaacsim.core.nodes.OgnIsaacRunOneSimulationFrame" },
    { deprecated = "omni.isaac.core_nodes.IsaacSimulationGate", new = "isaacsim.core.nodes.IsaacSimulationGate" },
    { deprecated = "omni.isaac.core_nodes.IsaacTimeSplitter", new = "isaacsim.core.nodes.IsaacTimeSplitter" },
    { deprecated = "omni.isaac.core_nodes.OnPhysicsStep", new = "isaacsim.core.nodes.OnPhysicsStep" },
    { deprecated = "omni.isaac.range_sensor.IsaacReadLidarBeams", new = "isaacsim.sensors.physx.IsaacReadLidarBeams" },
    { deprecated = "omni.isaac.range_sensor.IsaacReadLidarPointCloud", new = "isaacsim.sensors.physx.IsaacReadLidarPointCloud" },
    { deprecated = "omni.isaac.ros2_bridge", new = "isaacsim.ros2.bridge" },
    { deprecated = "omni.isaac.sensor.IsaacComputeRTXLidarFlatScan", new = "isaacsim.sensors.rtx.IsaacComputeRTXLidarFlatScan" },
    { deprecated = "omni.isaac.sensor.IsaacComputeRTXLidarPointCloud", new = "isaacsim.sensors.rtx.IsaacComputeRTXLidarPointCloud" },
    { deprecated = "omni.isaac.sensor.IsaacComputeRTXRadarPointCloud", new = "isaacsim.sensors.rtx.IsaacComputeRTXRadarPointCloud" },
    { deprecated = "omni.isaac.sensor.IsaacCreateRTXLidarScanBuffer", new = "isaacsim.sensors.rtx.IsaacCreateRTXLidarScanBuffer" },
    { deprecated = "omni.isaac.sensor.IsaacPrintRTXSensorInfo", new = "isaacsim.sensors.rtx.IsaacPrintRTXSensorInfo" },
    { deprecated = "omni.isaac.sensor.IsaacReadContactSensor", new = "isaacsim.sensors.physics.IsaacReadContactSensor" },
    { deprecated = "omni.isaac.sensor.IsaacReadEffortSensor", new = "isaacsim.sensors.physics.IsaacReadEffortSensor" },
    { deprecated = "omni.isaac.sensor.IsaacReadIMU", new = "isaacsim.sensors.physics.IsaacReadIMU" },
    { deprecated = "omni.isaac.sensor.IsaacReadLightBeamSensor", new = "isaacsim.sensors.physx.IsaacReadLightBeamSensor" },
    { deprecated = "omni.isaac.sensor.IsaacReadRTXLidarData", new = "isaacsim.sensors.rtx.IsaacReadRTXLidarData" },
    { deprecated = "omni.replicator.isaac", new = "isaacsim.replicator" },
]
