[package]
version = "1.2.4"
category = "Simulation"
title = "Isaac Sim Asset Transformer"
description = "Python-only extension providing asset transformation utilities"
authors = ["gasoto@nvidia.com"]
repository = "https://gitlab-master.nvidia.com/omniverse/isaac/omni_isaac_sim/-/tree/develop/source/extensions/isaacsim.asset.transformer"
keywords = ["isaac", "assets", "transform"]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
preview_image = "data/preview.png"
icon = "data/icon.png"

[dependencies]
"omni.usd.libs" = {}

[[python.module]]
name = "isaacsim.asset.transformer"

[[python.module]]
name = "isaacsim.asset.transformer.tests"

[[test]]
stdoutFailPatterns.exclude = [
    "*[isaacsim.asset.transformer.manager] Rule '*' failed*",
]

[documentation]
pages = ["docs/Overview.md", "docs/CHANGELOG.md"]
